{include file='../common/header.phtml'}
<div class="wrap">
    <div class="row">
        <div align="center">
            <p><div class="fb-like" data-href="https://www.facebook.com/Christian Transfers" data-send="true" data-width="700" data-show-faces="false" data-action="recommend">
            </div>
            </p>
        </div>

        <div align="center">
            <h1>Minivan and minibus hire with driver in Montenegro - Podgorita Airport, Tivat Airport, Dubrovnik Airport to Kotor, Budva, Herceg Novi</h1>
        </div>

        <div class="wrapper">
            <article class="cols400">
                <figure><img src="images/montenegro/montenegro podgorica airport.jpg" width="240" alt="podgorica airport in montenegro" title="Podgorica Airport in Montenegro" class="pad_bot2"></figure>
                <p class="pad_bot1"><strong>If you have an organized group, do not hesitate to rent a private minvan or minibus of 5, 8 or 16 seater with our chauffeur included.</strong></p>
                <p>You can communicate the programme for vehicles rental and we will do as soon as possible a complete offer according with your request. Rent conditions and exceptional value for money make this version a very good alternative.</p>
            </article>

            <article class="cols400 pad_left1">
                <p>In Montenegro, a top 10 destination on a "to see" list in last 20 years, our company provides minivans or minbuses for any type of event: Transfers to / from airport, city tours, travel in Montenegro, business trips, transportation for delegates, holidays at Adriatic coast or mountainous northern region, teambuilding for companies, private tours or special events.</p> 
                <p>All the cars and minibuses offered in Montenegro can be rented only with our chauffeur service included. At this time we don't have the option to rent a car to be driven by client. On request we can offer specialized travel guide for english language.</p>
                <a href="contact.html" class="button1"><strong>Contact us</strong></a>
            </article>

            <article class="cols400 pad_left1">
                <figure></figure>
                <figure><img src="images/montenegro/montenegro budva beach sveti stefan.jpg" width="240" alt="budva beach with island sveti stefan in montenegro" title="Budva is one of the main tourist destinations, here with island Sveti Stefan - Montenegro" class="pad_bot2"></figure>
                <p>We offer pickups from all 3 airports serve the country Podgorita Airport, Tivat Airport, Dubrovnik Airport to all destinations you may need, just some of them been Podgorita, Tivat, Kotor, Budva, Herceg Novi, Bar, Sumtomore, Ulcinj, Durmitor National Park, Tara river canyon or Perast.</p>
            </article>
        </div>

        <table class="responsive" width="100%" border="0" cellpadding="0" cellspacing="0">
            <tr>
                <td valign="top" align="right" colspan="8">
                    <p><a href="minibus.html"><font color="#000">Back to all Minibus list</font></a></p>
                </td>
            </tr>
        </table>

        <table class="responsive" width="100%" border="5" cellpadding="5" cellspacing="5">
            <tr>
                <th valign="top" align="Left" colspan="8">
                    <p><font color="#1616E9"></font></p>
                </th>
            </tr>
            <tr>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <img src="images/crafter 2013 exterior.JPG" width="110" alt="minibus 1-16 seats rental with driver in montenegro" title="Minibus 1-16 places" class="pad_bot2"> 
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Available pick-up</b></br>Podgorita Airport</br>Podgorita</br>Tara river</br>Durmitor National Park</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Minivan 8 seater</b></br></br>Available for inquiries</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Minibus 16 seater</b></br></br>Available for inquiries</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Send your request</b></br></br><a href="contact.html" class="button1"><strong>Contact us</strong></a></font>
                </td>
            </tr>
            <tr>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <img src="images/vito gri.jpg" width="110" alt="minibus 1-8 seats rental with driver in montenegro" title="Minivan 1-8 places" class="pad_bot2"> 
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Available pick-up</b></br>Tivat Airport</br>Kotor</br>Budva</br>Bar</br>Helceg Novi</br>Ulcinj</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>MVP 5 seater</b></br></br>Available for inquiries</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Minibus 7 seater</b></br></br>Available for inquiries</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Send your request</b></br></br><a href="contact.html" class="button1"><strong>Contact us</strong></a></font>
                </td>
            </tr> 
        </table>
        <table class="responsive" width="100%" border="0" cellpadding="5" cellspacing="5">
            <tr>
                <td valign="top" align="center" colspan="8">
                    <img src="images/montenegro/montenegro perast bay of kotor.jpg" width="220" alt="perast bay of kotor" title="Perast in Bay of Kotor - Montenegro" class="pad_bot2">
                    <img src="images/montenegro/montenegro tara river canyon.jpg" width="220" alt="tara river canyon" title="Tara Canyon, deepest canyon in Europe - Montenegro" class="pad_bot2">
                    <img src="images/montenegro/montenegro durmitor park.jpg" width="220" alt="durmitor national park" title="Durmitor national park in northwestern Montenegro" class="pad_bot2">
                    </br>
                    <img src="images/montenegro/montenegro bay of kotor in the night.jpg" width="220" alt="bay of kotor at night" title="Bay of Kotor at night - Montenegro" class="pad_bot2">
                    <img src="images/montenegro/montenegro sutomore.jpg" width="220" alt="sutomore sandy beach" title="Sutomore 2 km long sandy beach and vibrant nightlife - Montenegro" class="pad_bot2">
                    <img src="images/montenegro/montenegro ulcinj beach.jpg" width="220" alt="ulcinj long beach" title="Ulcinj is a famous destination for tourists, because of its Long Beach, Lake Shas, Ada Bojana Island and for its two-millennia-old Ulcinj Castle - Montenegro" class="pad_bot2">
                </td>
            </tr>
        </table>

        <table class="responsive" width="100%" border="0" cellpadding="0" cellspacing="0">
            <tr>
                <td valign="top" align="center"><p>
                        <a href="minibusingermany.html"><font color="#000">Minibus in Germany</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusincroatia.html"><font color="#000">Minibus in Croatia</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusinromania.html"><font color="#000">Minibus in Romania</font></a></p>
                </td>
            </tr>
            <tr>
                <td valign="top" align="center"><p>
                        <a href="minibusinhungary.html"><font color="#000">Minibus in Hungary</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusinaustria.html"><font color="#000">Minibus in Austria</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusinslovakia.html"><font color="#000">Minibus in Slovakia</font></a></p>
                </td>
            </tr>
            <tr>
                <td valign="top" align="center"><p>
                        <a href="minibusinbulgaria.html"><font color="#000">Minibus in Bulgaria</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusinserbia.html"><font color="#000">Minibus in Serbia</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusinmontenegro.html"><font color="#000">Minibus in Montenegro</font></a></p>
                </td>
            </tr>
        </table> 

        <div align="center">
            <p><div class="fb-like" data-href="https://www.facebook.com/Christian Transfers" data-send="true" data-width="700" data-show-faces="false" data-action="recommend">
            </div>
            </p>
        </div>
    </div>
</div>

{include file='../common/footer.phtml'}