{include file='../common/header_with_form_breadcrumbs.phtml'}

		<div class="wrap">
			<div class="row">
			
				<!--- Content -->
                <div class="full-width content">
                        <!-- Post -->
                        <article class="single hentry">
                                <div class="entry-content">
                                    <h2>Shuttle bus timetable Budapest Airport Oradea Cluj Turda Aiud</h2>
                                    <p class="lead">In this page we are presenting the shuttle bus schedule with hours, dates and stations details. For shuttle buses the hours and dates are fixed and cannot be changed. You can order private transfers from to your desire hours using the website menu. Please find below all information you need.</p>
                                        
                                </div>
                        </article>
                        <!-- //Post -->
                </div>
                <!--- //Content -->			
			
				<!--- Content -->
				<div class="one-half content offset">
					<table class="hover">
						<tr>
							<th>Start City</th>
							<th>Transit</th>
							<th>Arrival City</th>
						</tr>
						<tr>
							<td><a href="/airport_transfer/romania-cluj-budapest_airport"><b>02:00(RO)</br> Turda </b></br>Sens Vest</br><b>03:00(RO)</br> Cluj </b></br>Beta Station</a></td>
							<td><a href="/airport_transfer/romania-cluj-budapest_airport"><b>03:15(RO)</br> Cluj </b></br>OMV Bila</br><b>06:00(RO)</br> Oradea </b></br>TVS Station</a></td>
							<td><a href="/airport_transfer/romania-cluj-budapest_airport"><b>09:00(HU)</br> Budapest </b></br>Ferihegy Airport</br><b>09:30(HU)</br> Budapest</b></br>Nepliget Station</a></td>
						</tr>
						<tr>
							<td><a href="/airport_transfer/romania-cluj-budapest_airport"><b>06:30(RO)</br> Cluj </b></br>Beta Station</br><b>07:00(RO)</br> Cluj </b></br>Hotel Napoca</a></td>
							<td><a href="/airport_transfer/romania-cluj-budapest_airport"><b>07:10(RO)</br> Cluj </b></br>Bila Parking</br><b>09:30(RO)</br> Oradea </b></br>TVS Station</a></td>
							<td><a href="/airport_transfer/romania-cluj-budapest_airport"><b>13:00(HU)</br> Budapest </b></br>Ferihegy Airport</br><b>14:00(HU)</br> Budapest</b></br>Nepliget Station</a></td>
						</tr>
						<tr>
							<td><a href="/airport_transfer/romania-cluj-budapest_airport"><b>08:00(RO)</br> Turda </b></br>Sens Vest</br><b>09:00(RO)</br> Cluj </b></br>Beta Station</a></td>
							<td><a href="/airport_transfer/romania-cluj-budapest_airport"><b>09:30(RO)</br> Cluj </b></br>OMV Bila</br><b>11:00(RO)</br> Oradea </b></br>TVS Station</a></td>
							<td><a href="/airport_transfer/romania-cluj-budapest_airport"><b>15:00(HU)</br> Budapest </b></br>Ferihegy Airport</br><b>15:30(HU)</br> Budapest</b></br>Nepliget Station</a></td>
						</tr>
						<tr>
							<td><a href="/airport_transfer/romania-cluj-budapest_airport"><b>21:00(RO)</br> Turda </b></br>Sens Vest</br><b>22:00(RO)</br> Cluj </b></br>Beta Station</a></td>
							<td><a href="/airport_transfer/romania-cluj-budapest_airport"><b>22:10(RO)</br> Cluj </b></br>Bila Parking</br><b>01:30(RO)</br> Oradea </b></br>TVS Station</a></td>
							<td><a href="/airport_transfer/romania-cluj-budapest_airport"><b>05:00(HU)</br> Budapest </b></br>Ferihegy Airport</br><b>05:30(HU)</br> Budapest</b></br>Nepliget Station</a></td>
						</tr>
						<tr>
							<td><a href="/airport_transfer/romania-cluj-budapest_airport"><b>22:30(RO)</br> Cluj </b></br>Beta Station</br><b>23:00(RO)</br> Cluj </b></br>Hotel Napoca</a></td>
							<td><a href="/airport_transfer/romania-cluj-budapest_airport"><b>23:10(RO)</br> Cluj </b></br>Bila Parking</br><b>03:30(RO)</br> Oradea </b></br>TVS Station</a></td>
							<td><a href="/airport_transfer/romania-cluj-budapest_airport"><b>05:00(HU)</br> Budapest </b></br>Ferihegy Airport</br><b>05:30(HU)</br> Budapest</b></br>Nepliget Station</a></td>
						</tr>
						<tr>
							<td><a href="/airport_transfer/romania-cluj-budapest_airport"><b>22:30(RO)</br> Turda </b></br>Sens Vest</br><b>01:00(RO)</br> Cluj </b></br>Beta Station</a></td>
							<td><a href="/airport_transfer/romania-cluj-budapest_airport"><b>01:10(RO)</br> Cluj </b></br>Bila Parking</br><b>03:30(RO)</br> Oradea </b></br>TVS Station</a></td>
							<td><a href="/airport_transfer/romania-cluj-budapest_airport"><b>07:00(HU)</br> Budapest </b></br>Ferihegy Airport</br><b>07:30(HU)</br> Budapest</b></br>Nepliget Station</a></td>
						</tr>
					</table>
				</div>
				<div class="one-half content offset">
					<table class="hover">
						<tr>
							<th>Start City</th>
							<th>Transit</th>
							<th>Arrival City</th>
						</tr>
						<tr>
						    <td><a href="/airport_transfer/romania-budapest_airport-cluj"><b>10:30(HU)</br> Budapest </b></br>Nepliget Station</br><b>11:00(HU)</br> Budapest </b></br>Ferihegy Airport</a></td>
							<td><a href="/airport_transfer/romania-budapest_airport-cluj"><b>16:00(RO)</br> Oradea </b></br>TVS Station</br><b>19:00(RO)</br> Cluj </b></br>Bila Parking</a></td>
							<td><a href="/airport_transfer/romania-budapest_airport-cluj"><b>19:30(RO)</br> Cluj </b></br>Hotel Napoca</br><b>20:00(RO)</br> Cluj</b></br>Beta Station</a></td>
						</tr>
						<tr>
						    <td><a href="/airport_transfer/romania-budapest_airport-cluj"><b>12:00(HU)</br> Budapest </b></br>Nepliget Station</br><b>13:00(HU)</br> Budapest </b></br>Ferihegy Airport</a></td>
							<td><a href="/airport_transfer/romania-budapest_airport-cluj"><b>16:30(RO)</br> Oradea </b></br>TVS Station</br><b>20:30(RO)</br> Cluj </b></br>OMV Bila</a></td>
							<td><a href="/airport_transfer/romania-budapest_airport-cluj"><b>20:50(RO)</br> Cluj </b></br>Beta Station</br><b>21:20(RO)</br> Turda</b></br>Sens Vest</a></td>
						</tr>
						<tr>
						    <td><a href="/airport_transfer/romania-budapest_airport-cluj"><b>14:00(HU)</br> Budapest </b></br>Nepliget Station</br><b>15:00(HU)</br> Budapest </b></br>Ferihegy Airport</a></td>
							<td><a href="/airport_transfer/romania-budapest_airport-cluj"><b>20:30(RO)</br> Oradea </b></br>TVS Station</br><b>22:50(RO)</br> Cluj </b></br>OMV Bila</a></td>
							<td><a href="/airport_transfer/romania-budapest_airport-cluj"><b>23:00(RO)</br> Cluj </b></br>Beta Station</br><b>23:30(RO)</br> Turda</b></br>Sens Vest</a></td>
						</tr>
						<tr>
						    <td><a href="/airport_transfer/romania-budapest_airport-cluj"><b>16:30(HU)</br> Budapest </b></br>Nepliget Station</br><b>17:00(HU)</br> Budapest </b></br>Ferihegy Airport</a></td>
							<td><a href="/airport_transfer/romania-budapest_airport-cluj"><b>21:30(RO)</br> Oradea </b></br>TVS Station</br><b>00:10(RO)</br> Cluj </b></br>OMV Bila</a></td>
							<td><a href="/airport_transfer/romania-budapest_airport-cluj"><b>00:30(RO)</br> Cluj </b></br>Beta Station</br><b>01:00(RO)</br> Turda</b></br>Sens Vest</a></td>
						</tr>
						<tr>
						    <td><a href="/airport_transfer/romania-budapest_airport-cluj"><b>17:00(HU)</br> Budapest </b></br>Nepliget Station</br><b>17:30(HU)</br> Budapest </b></br>Ferihegy Airport</a></td>
							<td><a href="/airport_transfer/romania-budapest_airport-cluj"><b>21:30(RO)</br> Oradea </b></br>TVS Station</br><b>01:00(RO)</br> Cluj </b></br>Bila Parking</a></td>
							<td><a href="/airport_transfer/romania-budapest_airport-cluj"><b>01:30(RO)</br> Cluj </b></br>Hotel Napoca</br><b>02:00(RO)</br> Cluj</b></br>Beta Station</a></td>
						</tr>
						<tr>
						    <td><a href="/airport_transfer/romania-budapest_airport-cluj"><b>23:50(HU)</br> Budapest </b></br>Nepliget Station</br><b>01:00(HU)</br> Budapest </b></br>Ferihegy Airport</a></td>
							<td><a href="/airport_transfer/romania-budapest_airport-cluj"><b>05:00(RO)</br> Oradea </b></br>TVS Station</br><b>08:00(RO)</br> Cluj </b></br>OMV Bila</a></td>
							<td><a href="/airport_transfer/romania-budapest_airport-cluj"><b>08:15(RO)</br> Cluj </b></br>Beta Station</br><b>09:00(RO)</br> Turda</b></br>Sens Vest</a></td>
						</tr>
					</table>
				</div>
				<div class="one-half content textongrey">
					<h2>About Shuttle Budapest Cluj route</h2>
					<p class="lead">Shuttle is running every day. Hours - Romania Cities = Romania Time - Hungary Cities = Hungary Time</p>
					<p>For winter holidays shuttle buses are NOT running in 24.12, 25.12, 31.12 and 01.01.</p>
					<p>For Easter holidays shuttle buses are NOT running in first and second day.</p>
					<p>Shuttle bus is running after this schedulle and cannot wait for late tourists.</p>
					<p>Shuttle bus can pick you up and drop of only in the stations listed below.</p>
					<p>After you choose the transfer from this list below please make the bookings and payments online using the website menu. We cannot make bookings on the phone and without prepayment.</p>
					<p>Please make reservations at least 48 hours prior to your transfer. For weekend transfers (Saturday and Sunday) transfers please do your bookings from Thursday or Friday.</p>
				</div>
				<div class="one-half content textongrey">
					<h2>About Budapest and Budapest Airport</h2>
					<p>Budapest, the capital of Hungary and considered by many to be the "Paris of the East," is one of the most culturally important metropolises in Eastern Europe and home to numerous UNESCO World Heritage Sites. Although humans have lived here since the Stone Age, this beautiful city only formally came into being in 1872 with the amalgamation of three previously independent towns - Old Buda (Óbuda), Buda, and Pest - to become the administrative, commercial, and industrial center of Hungary. Straddling the River Danube, Budapest is famous for its thermal springs, some of which have been used for therapeutic purposes since prehistory.</p>
					<p>Budapest has so many things to do that you will want to spend at least a few days exploring the city. Popular attractions range from impressive architecture and poignant reminders of 20th-century history to a vibrant cultural and entertainment scene, with everything from street buskers to classical concerts in beautiful churches.</p>
					<p>Budapest is served by Budapest Ferenc Liszt International Airport (BUD) (named after Franz Liszt, the notable Hungarian composer), one of the busiest airports in Central and Eastern Europe. The airport offers international connections among all major European cities, and also to North America, Africa and the Middle East.</p>
				</div>
				<div class="one-half content textongrey">
					<h2>About Oradea</h2>
					<p>Oradea is one the few undiscovered gems of Romania's tourism. Despite being one of the largest and most important cities in Transylvania, and having a high degree of administrative, economic and commercial importance, it is often overlooked by tourists in favor of other Transylvanian cities.</p>
					<p>Is a cultural centre, with a state theatre, puppet theatre, philharmonic orchestra, regional library, and  museum. Five miles east of Oradea are the spas of Baile 1 Mai and Baile Felix. Since World War II, Oradea has become a major industrial centre, producing machine tools, mining equipment, chemicals, processed foods, and footwear.</p>
					<p>Fans of art nouveau and Viennese and Hungarian Secession architecture dating from the late 19th and early 20th centuries will want to make a special stop in Oradea. Visitors with a sharp eye will see Secession’s signature lyric design elements and inlaid enamelwork on buildings up and down the main pedestrian walkway, Calea Republicii, and across the Crisul Repede river in Piaţa Unirii.</p>
				</div>
				<div class="one-half content textongrey">
					<h2>About Cluj</h2>
					<p>Cluj-Napoca is the unofficial capital of Transylvania, and though you (probably) won’t find vampires here, you can explore castles, fortresses, botanical gardens, museums and parks.</p>
					<p>Bohemian cafes, music festivals and vigorous nightlife are the soul of city. Cluj-Napoca has a vibrant arts scene that embraces both the traditional and the progressive. There are plenty of opportunities to enjoy classical concerts, theatrical performances, puppet shows and music of every genre, from jazz to modern pop to electronica.</p>
					<p>With increasing flight links to European cities, Cluj is welcoming more and more travellers, who usually shoot off to the Apuseni Mountains, Maramures or more popular towns in southern Transylvania. But once arrived, first-time visitors inevitably lament their failure to allow enough time in Cluj.</p>
				</div>
				<!--- //Content -->
			</div>
		</div>
{include file='../common/footer.phtml'}