{include file='../common/header_with_form_breadcrumbs.phtml'}
        <div class="wrap">
                <div class="row">
				
				<!--- Content -->
                <div class="full-width content">
                        <!-- Post -->
                        <article class="single hentry">
                                <div class="entry-content">
                                    <h2>Shuttle bus timetable Budapest Airport Szeged Arad Timisoara</h2>
                                    <p class="lead">In this page we are presenting the shuttle bus schedule with hours, dates and stations details. For this route shuttle hours are approximate because we pick you up from your adress. You can order private transfers from to your desire hours using the website menu. Please find below all information you need.</p>
                                        
                                </div>
                        </article>
                        <!-- //Post -->
                </div>
                <!--- //Content -->
				
                <!--- Content -->
                        <div class="one-half content offset">
                                <table class="hover">
                                        <tr>
                                                <th>Start City</th>
                                                <th>Transit</th>
                                                <th>Arrival City</th>
                                        </tr>
                                        <tr>
                                                <td><a href="/airport_transfer/romania-timisoara-budapest_airport"><b>00:30(RO)</br> Timisoara </b></br>Your Adress</br><b>01:30(RO)</br> Arad </b></br>Your Adress</a></td>
                                                <td><a href="/airport_transfer/romania-timisoara-budapest_airport"><b>02:00(HU)</br> Szeged </b></br>Your Adress</br><b>03:00(HU)</br> Kecskemet</b></br>Your Adress</a></td>
                                                <td><a href="/airport_transfer/romania-timisoara-budapest_airport"><b>04:00(HU)</br> Budapest </b></br>Ferihegy Airport</br><b>04:30(HU)</br> Budapest</b></br>Nepliget Station</a></td>
                                        </tr>
                                        <tr>
                                                <td><a href="/airport_transfer/romania-timisoara-budapest_airport"><b>04:00(RO)</br> Timisoara </b></br>Your Adress</br><b>05:00(RO)</br> Arad </b></br>Your Adress</a></td>
                                                <td><a href="/airport_transfer/romania-timisoara-budapest_airport"><b>05:30(HU)</br> Szeged </b></br>Your Adress</br><b>06:30(HU)</br> Kecskemet</b></br>Your Adress</a></td>
                                                <td><a href="/airport_transfer/romania-timisoara-budapest_airport"><b>07:30(HU)</br> Budapest </b></br>Ferihegy Airport</br><b>08:00(HU)</br> Budapest</b></br>Nepliget Station</a></td>
                                        </tr>
                                        <tr>
                                                <td><a href="/airport_transfer/romania-timisoara-budapest_airport"><b>07:00(RO)</br> Timisoara </b></br>Your Adress</br><b>08:00(RO)</br> Arad </b></br>Your Adress</a></td>
                                                <td><a href="/airport_transfer/romania-timisoara-budapest_airport"><b>08:30(HU)</br> Szeged </b></br>Your Adress</br><b>09:30(HU)</br> Kecskemet</b></br>Your Adress</a></td>
                                                <td><a href="/airport_transfer/romania-timisoara-budapest_airport"><b>10:30(HU)</br> Budapest </b></br>Ferihegy Airport</br><b>11:00(HU)</br> Budapest</b></br>Nepliget Station</a></td>
                                        </tr>
                                        <tr>
                                                <td><a href="/airport_transfer/romania-timisoara-budapest_airport"><b>09:30(RO)</br> Timisoara </b></br>Your Adress</br><b>10:30(RO)</br> Arad </b></br>Your Adress</a></td>
                                                <td><a href="/airport_transfer/romania-timisoara-budapest_airport"><b>11:00(HU)</br> Szeged </b></br>Your Adress</br><b>12:00(HU)</br> Kecskemet</b></br>Your Adress</a></td>
                                                <td><a href="/airport_transfer/romania-timisoara-budapest_airport"><b>13:00(HU)</br> Budapest </b></br>Ferihegy Airport</br><b>13:30(HU)</br> Budapest</b></br>Nepliget Station</a></td>
                                        </tr>
                                        <tr>
                                                <td><a href="/airport_transfer/romania-timisoara-budapest_airport"><b>13:30(RO)</br> Timisoara </b></br>Your Adress</br><b>15:00(RO)</br> Arad </b></br>Your Adress</a></td>
                                                <td><a href="/airport_transfer/romania-timisoara-budapest_airport"><b>15:30(HU)</br> Szeged </b></br>Your Adress</br><b>16:30(HU)</br> Kecskemet</b></br>Your Adress</a></td>
                                                <td><a href="/airport_transfer/romania-timisoara-budapest_airport"><b>17:30(HU)</br> Budapest </b></br>Ferihegy Airport</br><b>18:00(HU)</br> Budapest</b></br>Nepliget Station</a></td>
                                        </tr>
                                </table>
                        </div>
                        <div class="one-half content offset">
                                <table class="hover">
                                        <tr>
                                                <th>Start City</th>
                                                <th>Transit</th>
                                                <th>Arrival City</th>
                                        </tr>
                                        <tr>
                                                <td><a href="/airport_transfer/romania-budapest_airport-timisoara"><b>00:00(HU)</br> Budapest </b></br>Nepliget Station</br><b>00:30(HU)</br> Budapest</b></br>Ferihegy Airport</a></td>
                                                <td><a href="/airport_transfer/romania-budapest_airport-timisoara"><b>01:30(HU)</br> Kecskemet </b></br>Your Adress</br><b>02:30(HU)</br> Szeged</b></br>Your Adress</a></td>
                                                <td><a href="/airport_transfer/romania-budapest_airport-timisoara"><b>05:00(RO)</br> Arad </b></br>Your Adress</br><b>06:00(RO)</br> Timisoara </b></br>Your Adress</a></td>
                                        </tr>
                                        <tr>
                                                <td><a href="/airport_transfer/romania-budapest_airport-timisoara"><b>09:30(HU)</br> Budapest </b></br>Nepliget Station</br><b>10:00(HU)</br> Budapest</b></br>Ferihegy Airport</a></td>
                                                <td><a href="/airport_transfer/romania-budapest_airport-timisoara"><b>11:00(HU)</br> Kecskemet </b></br>Your Adress</br><b>12:00(HU)</br> Szeged</b></br>Your Adress</a></td>
                                                <td><a href="/airport_transfer/romania-budapest_airport-timisoara"><b>14:30(RO)</br> Arad </b></br>Your Adress</br><b>16:00(RO)</br> Timisoara </b></br>Your Adress</a></td>
                                        </tr>
                                        <tr>
                                                <td><a href="/airport_transfer/romania-budapest_airport-timisoara"><b>13:30(HU)</br> Budapest </b></br>Nepliget Station</br><b>14:00(HU)</br> Budapest</b></br>Ferihegy Airport</a></td>
                                                <td><a href="/airport_transfer/romania-budapest_airport-timisoara"><b>15:00(HU)</br> Kecskemet </b></br>Your Adress</br><b>16:00(HU)</br> Szeged</b></br>Your Adress</a></td>
                                                <td><a href="/airport_transfer/romania-budapest_airport-timisoara"><b>18:30(RO)</br> Arad </b></br>Your Adress</br><b>20:00(RO)</br> Timisoara </b></br>Your Adress</a></td>
                                        </tr>
                                        <tr>
                                                <td><a href="/airport_transfer/romania-budapest_airport-timisoara"><b>16:30(HU)</br> Budapest </b></br>Nepliget Station</br><b>17:00(HU)</br> Budapest</b></br>Ferihegy Airport</a></td>
                                                <td><a href="/airport_transfer/romania-budapest_airport-timisoara"><b>18:00(HU)</br> Kecskemet </b></br>Your Adress</br><b>19:00(HU)</br> Szeged</b></br>Your Adress</a></td>
                                                <td><a href="/airport_transfer/romania-budapest_airport-timisoara"><b>21:30(RO)</br> Arad </b></br>Your Adress</br><b>22:30(RO)</br> Timisoara </b></br>Your Adress</a></td>
                                        </tr>
                                        <tr>
                                                <td><a href="/airport_transfer/romania-budapest_airport-timisoara"><b>19:30(HU)</br> Budapest </b></br>Nepliget Station</br><b>20:00(HU)</br> Budapest</b></br>Ferihegy Airport</a></td>
                                                <td><a href="/airport_transfer/romania-budapest_airport-timisoara"><b>21:00(HU)</br> Kecskemet </b></br>Your Adress</br><b>22:00(HU)</br> Szeged</b></br>Your Adress</a></td>
                                                <td><a href="/airport_transfer/romania-budapest_airport-timisoara"><b>00:30(RO)</br> Arad </b></br>Your Adress</br><b>01:30(RO)</br> Timisoara </b></br>Your Adress</a></td>
                                        </tr>
                                </table>
                        </div>
                        <div class="one-half content textongrey">
                                <h2>About Shuttle Budapest Timisoara route</h2>
                                <p class="lead">Shuttle is running every day. Hours - Romania Cities = Romania Time - Hungary Cities = Hungary Time</p>
                                <p>For winter holidays shuttle buses are NOT running in 24.12, 25.12, 31.12 and 01.01.</p>
                                <p>For Easter holidays shuttle buses are NOT running in first and second day.</p>
                                <p>Shuttle bus is running after this schedulle and cannot wait for late tourists.</p>
                                <p>Shuttle bus can pick you up and drop of only in the stations listed below.</p>
                                <p>After you choose the transfer from this list below please make the bookings and payments online using the website menu. We cannot make bookings on the phone and without prepayment.</p>
                                <p>Please make reservations at least 48 hours prior to your transfer. For weekend transfers (Saturday and Sunday) transfers please do your bookings from Thursday or Friday.</p>
                        </div>
                        <div class="one-half content textongrey">
                                <h2>About Budapest and Budapest Airport</h2>
                                <p>Budapest, the capital of Hungary and considered by many to be the "Paris of the East," is one of the most culturally important metropolises in Eastern Europe and home to numerous UNESCO World Heritage Sites. Although humans have lived here since the Stone Age, this beautiful city only formally came into being in 1872 with the amalgamation of three previously independent towns - Old Buda (Óbuda), Buda, and Pest - to become the administrative, commercial, and industrial center of Hungary. Straddling the River Danube, Budapest is famous for its thermal springs, some of which have been used for therapeutic purposes since prehistory.</p>
                                <p>Budapest has so many things to do that you will want to spend at least a few days exploring the city. Popular attractions range from impressive architecture and poignant reminders of 20th-century history to a vibrant cultural and entertainment scene, with everything from street buskers to classical concerts in beautiful churches.</p>
                                <p>Budapest is served by Budapest Ferenc Liszt International Airport (BUD) (named after Franz Liszt, the notable Hungarian composer), one of the busiest airports in Central and Eastern Europe. The airport offers international connections among all major European cities, and also to North America, Africa and the Middle East.</p>
                        </div>
						<div class="one-half content textongrey">
                                <h2>About Szeged</h2>
                                <p>Szeged is the third largest city of Hungary, the largest city and regional centre of the Southern Great Plain and the county seat of Csongrád county.</p>
                                <p>It’s hard to name the single thing that makes Szeged such an appealing city. Is it the shady, gardenlike main square with all the park benches or the abundant streetside-cafe seating in a pedestrian area that seems to stretch on forever? Maybe it’s the interesting architecture of the palaces in the old town. Then again, it could be the year-round cultural performances and lively university-town vibe (students marched here in 1956 before their classmates in Budapest did). Szeged – a corruption of the Hungarian word sziget (island) – sits astride the Tisza River, with a thermal-bath complex and park opposite the old town. Another thing that makes the city unique is the unusual Szeged accent in Hungarian, which sounds strange in a country with so few dialectical differences.</p>
                        </div>
                        <div class="one-half content textongrey">
                                <h2>About Arad</h2>
                                <p>Straddling the Mures River and occupying parts of both Crisana province and Banat, Arad traces its history back to the 11th century. Churches and cathedrals in the city span four centuries, several denominations, and architectural styles ranging from baroque to neoclassic.</p>
                                <p>Arad is a city of impressive buildings and architecture, with many of the main sights located along the principal thoroughfare, the broad, tree-lined, Bulevardul Revolutiei with trams running along it. Today, Arad is an important industrial center and transportation hub, as well as home to two universities, a Romanian Orthodox theological seminary, a training school for teachers, and a music conservatory.</p>
                        </div>						
                        <!--- //Content -->
                </div>
        </div>
{include file='../common/footer.phtml'}