{include file='../common/header.phtml'}
    <!-- Main -->
	<!-- Page info -->
	<main class="main" role="main">
		<!-- Page info -->
		<header class="site-title color">
            <div class="wrap">
                <div class="container">
                    <h1>Timetables for Budapest Airport and Otopeni Airport</h1>
                    <nav role="navigation" class="breadcrumbs">
                        <ul>
                            <li><a href="/" title="Christian Transfers - Airport Transfers">Go to Home</a></li>
                            <li>You are on Timetables</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
    <!-- //Page info -->


        <div class="wrap">
            <div class="row">			
                <!--- Content -->
                <div class="full-width content">
                        <!-- Post -->
                        <article class="single hentry">
                                <div class="entry-content">
                                        <h2>Timetable Budapest Szeged Timisoara Belgrade Oradea Cluj Otopeni Constanta</h2>
                                        <p class="lead">In this page we are presenting the shuttle bus schedule with hours, dates and stations addresses. For every route details are different, please follow your desire route page to see the details. For private or tailor transfers, to your desire time and locations please make the booking by using website menu.</p>
                                        <h3>Bus programme departures from HUNGARY</h3>
                                        <p><a href="/budapest-timisoara">HUNGARY - ROMANIA = Budapest - Szeged - Arad - Timisoara and return</a></p>
                                        <p><a href="/budapest-cluj">HUNGARY - ROMANIA = Budapest - Oradea - Cluj - Turda - Aiud and return</a></p>
                                        <h3>Bus programme departures from ROMANIA</h3>
                                        <p><a href="/budapest-timisoara">ROMANIA - HUNGARY = Timisoara - Arad - Szeged - Budapest and return</a></p>
                                        <p><a href="/budapest-cluj">ROMANIA - HUNGARY = Aiud - Turda - Oradea - Cluj - Budapest and return</a></p>
                                        <p><a href="/timisoara-belgrade">ROMANIA - SERBIA = Timisoara - Belgrade and return</a></p>
                                        <p><a href="/otopeni-constanta">Otopeni Henri Coanda Airport (Bucharest Airport) - Constanta and return</a></p>
                                        <h3>Bus programme departures from SERBIA</h3>
                                        <p><a href="/timisoara-belgrade">SERBIA - ROMANIA = Belgrade - Timisoara and return</a></p>
                                </div>
                        </article>
                        <!-- //Post -->
                </div>
                <!--- //Content -->
            </div>
        </div>
	</main>
	<!-- //Main -->
	
	<!-- MAIN Gallery including Titles start -->
    <div class="maingallery">
        <h5>Shared Shuttles and Bus Tickets service list</h5>
          <p>... 
		  </p>

    <!-- Portfolio Gallery Start -->
    <div class="rowgallery">
        <div class="columngallery">
            <div class="contentgallery">
                <img src="images/hungary/budapest.jpg" alt="shared shuttle budapest airport" title="Shared shuttle Budapest Airport" style="width:100%">
	            <p><a href="/budapest-timisoara">Click for details ...</a></p>
                <h3>Shared shuttle Budapest</h3>
                <p><a href="/christian-transfers-hungary">Shuttle bus in Hungary from Budapest Airport or city center to Szeged, Timisoara and Arad. Click for other services ...</a></p>
            </div>
        </div>
        <div class="columngallery">
            <div class="contentgallery">
                <img src="images/serbia/belgrad1.jpg" alt="shared shuttle belgrade airport" title="Shared shuttle Belgrade Airport" style="width:100%">
	            <p><a href="/timisoara-belgrade">Click for details ...</a></p>
                <h3>Shared shuttle Belgrade</h3>
                <p><a href="/christian-transfers-serbia">Shuttle bus in Serbia from Belgrade Airport or Belgrade City to Timisoara Airport or city. Click for other services ...</a></p>
            </div>
        </div>
        <div class="columngallery">
            <div class="contentgallery">
                <img src="images/romania/otopeni airport.jpg" alt="shared shuttle otopeni airport" title="Shared shuttle Otopeni Airport" style="width:100%">
                <p><a href="/otopeni-constanta">Click for details ...</a></p>
	            <h3>Shared shuttle Otopeni</h3>
                <p><a href="/christian-transfers-romania">Shuttle bus in Romania, from Otopeni Airport to Constanta, Mamaia or some Black Sea resorts. Click for other services ...</a></p>
            </div>
        </div>
		<div class="columngallery">
            <div class="contentgallery">
                <img src="images/hungary/budapest.jpg" alt="bus tickets in budapest airport" title="Bus tickets in Budapest Airport" style="width:100%">
	            <p><a href="/budapest-cluj">Click for details ...</a></p>
                <h3>Bus tickets in Budapest</h3>
                <p><a href="/christian-transfers-hungary">Shuttle bus in Hungary, from Budapest city or Budapest Airport, to Oradea, Cluj, Aiud, Turda. Click for other services ...</a></p>
            </div>
        </div>
    </div>

        <!--<div class="contentgallery">
                <img src="img/shop/women3.jpg" alt="Nike Wholesale Shoes" title="Nike Wholesale shoes" style="width:100%">
	            <p><a href="contact.html">£19,99 Click for details ...</a></p>
                <h3>Nike Women Wholesale Shoes</h3>
                <p><a href="contact.html">Wholesale shoes for every small shop, please contact us for best options at various quantities. Click for details ...</a></p>
            </div> -->
         <!-- Gallery END -->
    </div>
    <!-- MAIN Gallery including Titles end -->
	
	
	<!-- Page info -->
		<header class="site-title color">
			<div class="wrap">
				<div class="container">
					<h1>Christian Transfers Services</h1>
					<nav role="navigation" class="breadcrumbs">
						<ul>
							<li><a href="/" title="Christian Transfers - Airport Transfers">Go to Home</a></li>
                            <li>You are on Timetables</li>
						</ul>
					</nav>
				</div>
			</div>
		</header>
	<!-- //Page info -->
{include file='../common/sidebar3.phtml'}
{include file='../common/footer.phtml'}