{include file='../common/header_with_form_breadcrumbs.phtml'}
<div class="wrap">
        <div class="row">
		
				<!--- Content -->
                <div class="full-width content">
                        <!-- Post -->
                        <article class="single hentry">
                                <div class="entry-content">
                                    <h2>Shuttle bus timetable Timisoara to Belgrade Airport</h2>
                                    <p class="lead">In this page we are presenting the shuttle bus schedule with hours, dates and stations details. For this route shuttle hours are approximate because in Timisoara and also Belgrade we pick you up from your adress. 
									You can order private transfers from to your desire hours using the website menu. Please find below all information you need.</p>
                                        
                                </div>
                        </article>
                        <!-- //Post -->
                </div>
                <!--- //Content -->		
                
				<!--- Content -->
                <div class="one-half content offset">
                        <table class="hover">
                                <tr>
                                        <th>Details</th>
                                        <th>Start City</th>
                                        <th>Arrival City</th>
                                </tr>
                                <tr>
                                        <td><b>Hour</br>City</b></br>Station</td>
                                        <td><a href="/airport_transfer/romania-timisoara-belgrade_airport"><b>01:15</br>Timisoara</b></br>Your Adress</a></td>
                                        <td><a href="/airport_transfer/romania-timisoara-belgrade_airport"><b>04:00</br>Belgrade</b></br>Your Adress</a></td>
                                </tr>
                                <tr>
                                        <td><b>Hour</br>City</b></br>Station</td>
                                        <td><a href="/airport_transfer/romania-timisoara-belgrade_airport"><b>07:15</br>Timisoara</b></br>Your Adress</a></td>
                                        <td><a href="/airport_transfer/romania-timisoara-belgrade_airport"><b>09:15</br>Belgrade</b></br>Your Adress</a></td>
                                </tr>
                                <tr>
                                        <td><b>Hour</br>City</b></br>Station</td>
                                        <td><a href="/airport_transfer/romania-timisoara-belgrade_airport"><b>13:15</br>Timisoara</b></br>Your Adress</a></td>
                                        <td><a href="/airport_transfer/romania-timisoara-belgrade_airport"><b>15:15</br>Belgrade</b></br>Your Adress</a></td>
                                </tr>
                                <tr>
                                        <td><b>Hour</br>City</b></br>Station</td>
                                        <td><a href="/airport_transfer/romania-timisoara-belgrade_airport"><b>14:30</br>Timisoara</b></br>Your Adress</a></td>
                                        <td><a href="/airport_transfer/romania-timisoara-belgrade_airport"><b>16:45</br>Belgrade</b></br>Your Adress</a></td>
                                </tr>
                        </table>
                </div>
                <div class="one-half content offset">
                        <table class="hover">
                                <tr>
                                        <th>Details</th>
                                        <th>Start City</th>
                                        <th>Arrival City</th>
                                </tr>
                                <tr>
                                        <td><b>Hour</br>City</b></br>Station</td>
                                        <td><a href="/airport_transfer/romania-belgrade_airport-timisoara"><b>00:15</br>Belgrade</b></br>Your Adress</a></td>
                                        <td><a href="/airport_transfer/romania-belgrade_airport-timisoara"><b>04:30</br>Timisoara</b></br>Your Adress</a></td>
                                </tr>
                                <tr>
                                        <td><b>Hour</br>City</b></br>Station</td>
                                        <td><a href="/airport_transfer/romania-belgrade_airport-timisoara"><b>07:30</br>Belgrade</b></br>Your Adress</a></td>
                                        <td><a href="/airport_transfer/romania-belgrade_airport-timisoara"><b>11:45</br>Timisoara</b></br>Your Adress</a></td>
                                </tr>
                                <tr>
                                        <td><b>Hour</br>City</b></br>Station</td>
                                        <td><a href="/airport_transfer/romania-belgrade_airport-timisoara"><b>13:30</br>Belgrade</b></br>Your Adress</a></td>
                                        <td><a href="/airport_transfer/romania-belgrade_airport-timisoara"><b>17:45</br>Timisoara</b></br>Your Adress</a></td>
                                </tr>
                                <tr>
                                        <td><b>Hour</br>City</b></br>Station</td>
                                        <td><a href="/airport_transfer/romania-belgrade_airport-timisoara"><b>20:30</br>Belgrade</b></br>Your Adress</a></td>
                                        <td><a href="/airport_transfer/romania-belgrade_airport-timisoara"><b>00:45</br>Timisoara</b></br>Your Adress</a></td>
                                </tr>
                        </table>
                </div>
                <div class="one-half content textongrey">
                        <h2>About Shuttle Timisoara Belgrade route</h2>
                        <p class="lead">Shuttle is running every day. Hours - Romania Cities = Romania Time - Serbia Cities = Serbia Time</p>
                        <p>Shuttle bus is running after this schedulle and cannot wait for late tourists.</p>
                        <p>Shuttle bus can pick you up and drop of only in the stations listed below.</p>
                        <p>After you choose the transfer from this list below please make the bookings and payments online using the left website menu. We cannot make bookings on the phone and without prepayment.</p>
                        <p>Please make reservations at least 48 hours prior to your transfer.</p>
                        <p>For weekend transfers (Saturday and Sunday) transfers please do your bookings from Thursday or Friday.</p>
                </div>
                <div class="one-half content textongrey">
                        <h2>About Timisoara</h2>
                        <p>Timisoara is the capital city of Timis County, and the main social, economic and cultural centre in western Romania, been is the biggest university city and industrial center.</p>
                        <p>Timisoara the most cosmopolitan city in Romania,is the city of roses and parks,  having a very green face, especially in spring, when tulips abound. On sunny days locals refresh themselves on the terraces of Unirii Square or along the Bega shores, chill around the pools, drink and enjoy the laid-back atmosphere.</p>
                        <p>Timisoara was the first European city to introduce horse-drawn trams (in 1869) and electrical street lighting (in 1889). It is often described as a little Vienna, because has similar architecture.</p>
						<p>The third most populous city in the Romania is the informal capital city of the historical region of Banat. With western Romania's nicest hotels and finest restaurants, it makes a perfect base for exploring the Banat region.</p>
						<p>In September 2016, Timisoara was selected as the European Capital of Culture for 2021.</p>
						<p>Timisoara is served by Timisoara Traian Vuia International Airport, who has a passengers trafic of aproximate 1.5 millions yearly. It is the third-busiest Romanian airport in terms of air traffic, and the main air transportation hub for the western part of Romania and for the Danube-Cris-Mures-Tisa Euroregion.</p>
                </div>
				<div class="one-half content textongrey">
                        <h2>About Belgrade</h2>
                        <p>Outspoken, adventurous, proud and audacious: Belgrade is by no means a 'pretty' capital, but its gritty exuberance makes it one of the most happening cities in Europe. While it hurtles towards a brighter future, it's chaotic past unfolds before your eyes: socialist blocks are squeezed between art nouveau masterpieces, and remnants of the Habsburg legacy contrast with Ottoman relics. He historic areas and buildings of Belgrade are among the city's premier attractions.</p>
                        <p>Belgrade has a reputation for offering a vibrant nightlife; many clubs that are open until dawn can be found throughout the city.</p>
                        <p>On top of this, there are many parks, monuments, museums, cafes, restaurants and shops on both sides of the river.</p>
                </div>
                <!--- //Content -->
        </div>
</div>
{include file='../common/footer.phtml'}