{include file='../common/header.phtml'}
<!-- Page info -->
<header class="site-title color">
    <div class="wrap">
        <div class="container">
            <h1>Thank you. Your booking is now confirmed.</h1>
        </div>
    </div>
</header>
<!-- //Page info -->

<div class="wrap">
    <div class="row">
        <div class="three-fourth">
            <form class="box readonly">
                <h3>Passenger details</h3>
                <div class="f-row">
                    <div class="one-fourth">Name and surname</div>
                    <div class="three-fourth">{$name}</div>
                </div>
                <div class="f-row">
                    <div class="one-fourth">Company</div>
                    <div class="three-fourth">{$company}</div>
                </div>
                <div class="f-row">
                    <div class="one-fourth">Mobile number</div>
                    <div class="three-fourth">{$phone}</div>
                </div>
                <div class="f-row">
                    <div class="one-fourth">Email address</div>
                    <div class="three-fourth">{$email}</div>
                </div>

                <h3>Departure Transfer details</h3>
                <div class="f-row">
                    <div class="one-fourth">Date</div>
                    <div class="three-fourth">{$date_transfer}</div>
                </div>
                <div class="f-row">
                    <div class="one-fourth">From</div>
                    <div class="three-fourth">{$nume_aeroport_transfer}</div>
                </div>
                <div class="f-row">
                    <div class="one-fourth">Pickup address</div>
                    <div class="three-fourth">{$aeroport_transfer}</div>
                </div>
                <div class="f-row">
                    <div class="one-fourth">Flight number</div>
                    <div class="three-fourth">{$flight_number_transfer}</div>
                </div>
                <div class="f-row">
                    <div class="one-fourth">To</div>
                    <div class="three-fourth">{$destinatie_transfer}</div>
                </div>
                <div class="f-row">
                    <div class="one-fourth">Destination address</div>
                    <div class="three-fourth">{$adresa_destinatie_transfer}</div>
                </div>
                <div class="f-row">
                    <div class="one-fourth">Passengers</div>
                    <div class="three-fourth">{$pasageri_transfer}</div>
                </div>
                <div class="f-row">
                    <div class="one-fourth">Vehicle</div>
                    <div class="three-fourth">{$vehicle_transfer}</div>
                </div>
                {if $big_transfer > 0}
                <div class="f-row">
                    <div class="one-fourth">Big bags</div>
                    <div class="three-fourth">{$big_transfer}</div>
                </div>
                {/if}
                {if $normal_transfer > 0}
                <div class="f-row">
                    <div class="one-fourth">Normal bags</div>
                    <div class="three-fourth">{$normal_transfer}</div>
                </div>
                {/if}
                {if $bicycle_transfer > 0}
                <div class="f-row">
                    <div class="one-fourth">Bicyle</div>
                    <div class="three-fourth">{$bicycle_transfer}</div>
                </div>
                {/if}
                {if $ski_transfer > 0}
                <div class="f-row">
                    <div class="one-fourth">Ski equipment</div>
                    <div class="three-fourth">{$ski_transfer}</div>
                </div>
                {/if}
                {if $pet_transfer > 0}
                <div class="f-row">
                    <div class="one-fourth">Pets</div>
                    <div class="three-fourth">{$pet_transfer}</div>
                </div>
                {/if}
{if $oneway == 0}
                <h3>Return Transfer details</h3>
                <div class="f-row">
                    <div class="one-fourth">Date</div>
                    <div class="three-fourth">{$date_return}</div>
                </div>
                <div class="f-row">
                    <div class="one-fourth">From</div>
                    <div class="three-fourth">{$nume_aeroport_return}</div>
                </div>
                <div class="f-row">
                    <div class="one-fourth">Pickup address</div>
                    <div class="three-fourth">{$aeroport_return}</div>
                </div>
                <div class="f-row">
                    <div class="one-fourth">Flight number</div>
                    <div class="three-fourth">{$flight_number_return}</div>
                </div>
                <div class="f-row">
                    <div class="one-fourth">To</div>
                    <div class="three-fourth">{$destinatie_return}</div>
                </div>
                <div class="f-row">
                    <div class="one-fourth">Destination address</div>
                    <div class="three-fourth">{$adresa_destinatie_return}</div>
                </div>
                <div class="f-row">
                    <div class="one-fourth">Passengers</div>
                    <div class="three-fourth">{$pasageri_return}</div>
                </div>
                <div class="f-row">
                    <div class="one-fourth">Vehicle</div>
                    <div class="three-fourth">{$vehicle_return}</div>
                </div>
                {if $big_return > 0}
                <div class="f-row">
                    <div class="one-fourth">Big bags</div>
                    <div class="three-fourth">{$big_return}</div>
                </div>
                {/if}
                {if $normal_return > 0}
                <div class="f-row">
                    <div class="one-fourth">Normal bags</div>
                    <div class="three-fourth">{$normal_return}</div>
                </div>
                {/if}
                {if $bicycle_return > 0}
                <div class="f-row">
                    <div class="one-fourth">Bicyle</div>
                    <div class="three-fourth">{$bicycle_return}</div>
                </div>
                {/if}
                {if $ski_return > 0}
                <div class="f-row">
                    <div class="one-fourth">Ski equipment</div>
                    <div class="three-fourth">{$ski_return}</div>
                </div>
                {/if}
                {if $pet_return > 0}
                <div class="f-row">
                    <div class="one-fourth">Pets</div>
                    <div class="three-fourth">{$pet_return}</div>
                </div>
                {/if}
{/if}
                <h3>TOTAL: {$price} {$worldpay_currency}</h3>
            </form>

			{literal}		
				<script src="https://checkout.stripe.com/checkout.js"></script>

				<button id="customButton" class="btn grey fullsize">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Go to payment &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</button>

				<script>
				var handler = StripeCheckout.configure({
				  key: 'pk_live_PEww6JkTJs9gf7GI4YQzFPIG',
				  image: 'https://www.christiantransfers.eu/images/logo1.png',
				  locale: 'auto',
				  token: function(token) {
					  if(token.id)
						  window.location.replace("https://www.christiantransfers.eu/success");
					// You can access the token ID with `token.id`.
					// Get the token ID to your server-side code for use.
				  }
				});

				document.getElementById('customButton').addEventListener('click', function(e) {
				  // Open Checkout with further options:
				  handler.open({
					name: 'Pay for {/literal}{$date_transfer}{literal}',
					description: '{/literal}{$nume_aeroport_transfer} to {$destinatie_transfer} {if $oneway == 0} / {$nume_aeroport_return} to {$destinatie_return}{/if}{literal}',
					zipCode: false,
					currency: 'GBP',
					allowRememberMe: false,
					email: '{/literal}{$email}{literal}',
					amount: {/literal}{$price*100}{literal}
				  });
				  e.preventDefault();
				});

				// Close Checkout on page navigation:
				window.addEventListener('popstate', function() {
				  handler.close();
				});
				</script>
				{/literal}
        </div>

        <!--- Sidebar -->
        <aside class="one-fourth sidebar right">
            <!-- Widget -->
            <div class="widget">
                <h4>Company details</h4>
                <div class="textwidget">
				    <p><img src="/images/logo1.png" width="85" height="35">&nbsp;Christian Transfers Ltd - Number 10137098</p>
                    <p>Office hours (Monday - Friday): 09:00 - 18:00</p>
                    <p>Bookings are made to the website menu and confirmations only by email</p>
                </div>
            </div>
            <!-- //Widget -->

            <!-- Widget -->
            <div class="widget">
                <h4>Please Read</h4>
                <div class="textwidget">
                    <p><font color="#C90000"><strong>
                    - Bookings without the payments will can't be processed.<br>
                    - We sent you the booking you made to the email registered at the previous step (please check the spam folder also).<br> 
                    - After you'll complete the online payment by card you will receive the payment confirmation by email from payment processor company.<br>
                    - Confirmation or infirmation of the service you booked will be sent by email by one of our agent.<br>
                    - We DO NOT keep records with sensitive card details, they'll be saved by payment processor company on their website.
                    </strong></font></p>
                </div>
            </div>
            <!-- //Widget -->
        </aside>
        <!--- //Sidebar -->
    </div>
</div>
{include file='../common/footer.phtml'}