{include file='../common/header.phtml'}
<header class="site-title color">
        <div class="wrap">
                <div class="container">
                        <h1>Customer Help - Christian Transfers</h1>
                        <nav role="navigation" class="breadcrumbs">
                                <ul>
                                        <li><a href="/" title="Home">Home</a></li>
                                        <li>Help</li>
                                </ul>
                        </nav>
                </div>
        </div>
</header>
<!-- //Page info -->

<div class="wrap">
        <div class="row">
                <!--- Content -->
                <div class="three-fourth content">
                        <h3 id="faqs1">Before you book</h3>
                        <dl class="faqs">
                                <!-- Item -->
                                <dt>How do I contact the Christian Transfers reservations office ?</dt>
                                <dd>
                                        <p>Please use the email from the contact page or click this link <a href="contact.htm"><font color="#FFAA01">email form </font></a></p>

                                </dd>
                                <!-- //Item -->

                                <!-- Item -->
                                <dt>How do I know if I have a reservation ?</dt>
                                <dd>
                                        <p>t the time of booking you will receive an email with your booking (<b>please see in the spam/junk folder also</b>). Please make a short reply to that email with your confirmation. In 2-48 hours we will send confirmation by email for your booking.</p>

                                </dd>
                                <!-- //Item -->

                                <!-- Item -->
                                <dt>How do I know if my payment was accepted ?</dt>
                                <dd>
                                        <p>At the time of booking you will receive an email with your payment. Please go in the email used in the booking and see the email. You dont to send us that email, we receive it also.</p>

                                </dd>
                                <!-- //Item -->

                                <!-- Item -->
                                <dt>How do I make my reservation ?</dt>
                                <dd>
                                        <p>Reservation must be made online using: the menu on the left of the site or the contact form.</p>

                                <!-- //Item -->


                                <dt>Do you offer discounted rates for children or babies ?</dt>
                                <dd>
                                        <p>We will charge the same rate for all occupied seats. Please note that babies may not travel for free on an adults lap.</p>
                                </dd>

                                <!-- //Item -->
                                <dt>Can I have a refund if I cancel my booking ?</dt>
                                <dd>
                                        <p>Under certain circumstances. If you cancel your transfer more than 7 days in advance, you will receive what you was payed back.</p>
                                </dd>
                                <!-- //Item -->
                        </dl>

                        <h3 id="faqs2">Before you travel</h3>
                        <dl class="faqs">
                        <!-- Item -->
                                <dt>How do I find my driver?</dt>
                                <dd>
                                        <p>For the private transfers our driver will be waiting inside of the arrival terminal with a banner with your name or your group leader name. In case of the shuttle bus transfers driver will have the shuttle bus company name on the baner at the meeting point. Details of the meeting point are sent in the confirmation email.</p>

                                </dd>

                                <!-- Item -->
                                <dt>What happens if I cannot find my driver?</dt>
                                <dd>
                                        <p>If your plane was coming earlier please be patience until the agreed time. Having ensured that you have correctly followed the instructions on your transport reservation, call our agent on the contact number after 10 minutes if you cant see the banner. Usually we instruct all the customers to go near the Information office to the arrival terminals.</p>

                                </dd>
                                <!-- //Item -->

                                <!-- Item -->
                                <dt>I have lost my luggage. Will you collect it for me later ?</dt>
                                <dd>
                                        <p>All the airlines have handling agents. They will organize for any luggage to be forwarded to your resort address.</p>

                                </dd>
                                <!-- //Item -->

                                <!-- Item -->
                                <dt>I have left something in the vehicle. How do I get it back ?</dt>
                                <dd>
                                        <p>Please contact our agent on the number provided. We will then endeavour to have the items returned to you. A charge may be applicable for the transportation and NOT as penalty.</p>

                                </dd>
                                <!-- //Item -->
                        </dl>
                                <h3 id="faqs3">More information</h3>

                        <dl class="faqs">
                                <!-- Item -->
                                <dt>Can I have a receipt ?</dt>
                                <dd>
                                        <p>For sure. Either you was paying online by credit/debit card or by bank transfer you will receive a invoice/receipt direct to your email and you can print it very easy for your accounting. Invoices are issued in 3-15 days after your payment.</p>
                                </dd>
                                <!-- //Item -->

                                <!-- Item -->
                                <dt>Can we stop off at the supermarket or to pick up property keys en route ?</dt>
                                <dd>
                                        <p>Only by prior arrangement with our agent and only if you are travelling by Private Transfer. Subject to availability, additional supplements may apply.</p>
                                </dd>
                                <!-- //Item -->

                                <!-- Item -->
                                <dt>Is the transfer direct or do we stop en route ?</dt>
                                <dd>
                                        <p>Private Transfers are normally direct and door-to-door. </p>

                                </dd>
                                <!-- //Item -->

                                <!-- Item -->
                                <dt>Does the driver speak English ?</dt>
                                <dd>
                                        <p>In most cases our drivers speak English, although scheduling requirements may mean that occasionally a non-English speaking driver may carry out a transfer.</p>
                                </dd>
                                <!-- //Item -->


                                <!-- //Item -->
                        </dl>
                </div>
                <!--- //Content -->

                <!--- Sidebar -->
                <aside class="one-fourth sidebar right offset">
                        <!-- Widget -->
                        <div class="widget">
                                <ul class="categories">
                                        <li class="active"><a href="#faqs1" class="anchor">Before you book</a></li>
                                        <li><a href="#faqs2" class="anchor">Before you travel</a></li>
                                        <li><a href="#faqs3" class="anchor">More information</a></li>
                                </ul>
                        </div>
                        <!-- //Widget -->
                </aside>
                <!--- //Sidebar -->
        </div>
</div>

{include file='../common/footer.phtml'}