{include file='../common/header.phtml'}
<div class="wrap">
    <div class="row"><div align="center">
            <p><div class="fb-like" data-href="https://www.facebook.com/Christian Transfers" data-send="true" data-width="700" data-show-faces="false" data-action="recommend">
            </div>
            </p>
        </div>

        <div align="center">
            <h1>Minivan, minibus or coach hire with driver in Romania - Bucharest, Otopeni, Timisoara, Cluj, Constanta, Iasi</h1>
        </div>

        <div class="wrapper">
            <article class="cols400">
                <figure><img src="images/sprinter_2013_exterior_generic 2.jpg" width="240" alt="bucharest rental minibus 19 places Mercedes Sprinter" title="Bucharest minibus 19 places Mercedes Sprinter" class="pad_bot2"></figure>
                <p class="pad_bot1"><strong>If you have an organized group, do not hesitate to rent a private minivan, minibus or coach with driver.</strong></p>
                <p>You can communicate the programme for vehicles rental and we will do as soon as possible a complete offer according with your request. Rent conditions and exceptional value for money make this version a very good alternative.</p>
            </article>

            <article class="cols400 pad_left1">
                <p>Our company provides minivans for any type of event: Transfers to / from airport, city tours, travel in Romania, Bulgaria, Hungary, Serbia and all European Union countries, business trips, transportation for delegates, conferences, holidays at home and abroad, teambuilding for companies, private tours or special events.</p> 
                <p>We also offer through our local partners vans, mininbus or full coaches for rent starting from Bucharest, Timisoara, Cluj, Constanta, Iasi, Satu Mare, Oradea or Suceava and to follow the client assigned route.</p>
                <a href="contact.html" class="button1"><strong>Contact us</strong></a>
            </article>

            <article class="cols400 pad_left1">
                <figure></figure>
                <figure><img src="images/sprinter_2013_3.jpg" width="240" alt="bucharest rental minibus 19 places Mercedes Sprinter interior" title="Bucharest minibus 19 places Mercedes Sprinter interior" class="pad_bot2"></figure>
                <p>All minibuses offered by us are renting only with our driver. Optional on request we can offer specialized travel guide for languages : Greek, English, French, Spanish, German.</p>
            </article>
        </div>

        <table class="responsive" width="100%" border="0" cellpadding="0" cellspacing="0">
            <tr>
                <td valign="top" align="right" colspan="8">
                    <p><a href="minibus.html"><font color="#000">Back to all Minibus list</font></a></p>
                </td>
            </tr>
        </table>

        <table class="responsive" width="100%" border="5" cellpadding="5" cellspacing="5">
            <tr>
                <th valign="top" align="Left" colspan="8">
                    <p><font color="#1616E9"></font></p>
                </th>
            </tr>
            <tr>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <img src="images/sprinter_2013_exterior_generic 2.jpg" width="110" alt="minibus mercedes sprinter rental with driver in bucharest and otopeni" title="Minibus Mercedes Sprinter 2013 in Bucharest & Otopeni" class="pad_bot2"> 
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Available pick-up</b></br>from Bucharest</br>or Bucharest Airport</br>or Brasov</br>or Dracula Castle</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Minivan 1-8 places </br></br>Minibus 1-16 places</b></br></br>Available for inquiries</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Coach 25-35 places </br></br>Coach 40-50 places</b></br></br>Available for inquiries</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Click here</b></br></br><a href="contact.html" class="button1"><strong>Contact us</strong></a></font>
                </td>
            </tr>
            <tr>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <img src="images/sprinter_2013_exterior_generic 2.jpg" width="110" alt="minibus mercedes sprinter rental with driver in cluj napoca" title="Minibus Mercedes Sprinter 2013 in Cluj Napoca" class="pad_bot2"> 
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Available pick-up</b></br>from Cluj</br>or Cluj Airport</br>or Oradea</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Minivan 1-8 places </br></br>Minibus 1-16 places</b></br></br>Available for inquiries</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Coach 25-35 places </br></br>Coach 40-50 places</b></br></br>Available for inquiries</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Click here</b></br></br><a href="contact.html" class="button1"><strong>Contact us</strong></a></font>
                </td>
            </tr>
            <tr>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <img src="images/sprinter_2013_exterior_generic 2.jpg" width="110" alt="minibus mercedes sprinter rental with driver in timisoara and arad" title="Minibus Mercedes Sprinter 2013 in Timisoara & Arad" class="pad_bot2"> 
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Available pick-up</b></br>from Timisoara</br>or Timisoara Airport</br>or Arad</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Minivan 1-8 places </br></br>Minibus 1-16 places</b></br></br>Available for inquiries</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Coach 25-35 places </br></br>Coach 40-50 places</b></br></br>Available for inquiries</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Click here</b></br></br><a href="contact.html" class="button1"><strong>Contact us</strong></a></font>
                </td>
            </tr>
            <tr>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <img src="images/sprinter_2013_exterior_generic 2.jpg" width="110" alt="minibus mercedes sprinter rental with driver in constanta mamaia" title="Minibus Mercedes Sprinter 2013 in Constanta & Mamaia" class="pad_bot2"> 
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Available pick-up</b></br>from Constanta</br>or Constanta Airport</br>or Mamaia</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Minivan 1-8 places </br></br>Minibus 1-16 places</b></br></br>Available for inquiries</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Coach 25-35 places </br></br>Coach 40-50 places</b></br></br>Available for inquiries</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Click here</b></br></br><a href="contact.html" class="button1"><strong>Contact us</strong></a></font>
                </td>
            </tr>
            <tr>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <img src="images/sprinter_2013_exterior_generic 2.jpg" width="110" alt="minibus mercedes sprinter rental with driver in cluj napoca" title="Minibus Mercedes Sprinter 2013 in Cluj Napoca" class="pad_bot2"> 
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Available pick-up</b></br>from Iasi</br>or Iasi Airport</br>or Suceava Monasteries</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Minivan 1-8 places </br></br>Minibus 1-16 places</b></br></br>Available for inquiries</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Coach 25-35 places </br></br>Coach 40-50 places</b></br></br>Available for inquiries</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Click here</b></br></br><a href="contact.html" class="button1"><strong>Contact us</strong></a></font>
                </td>
            </tr>
        </table>

        <table class="responsive" width="100%" border="0" cellpadding="5" cellspacing="5">
            <tr>
                <td valign="top" align="center" colspan="8">
                    <img src="images/sprinter_2013_1.jpg" width="240" alt="minibus mercedes sprinter rental with driver in bucharest and otopeni" title="Minibus Mercedes Sprinter 2013 in Bucharest & Otopeni" class="pad_bot2">
                    <img src="images/sprinter_2013_4.jpg" width="240" alt="minibus mercedes sprinter rental with driver in cluj napoca" title="Minibus Mercedes Sprinter 2013 in Cluj Napoca" class="pad_bot2">
                    </br>
                    <img src="images/sprinter_2013_2.jpg" width="240" alt="minibus mercedes sprinter rental with driver in timisoara and arad" title="Minibus Mercedes Sprinter 2008 in Timisoara & Arad" class="pad_bot2">
                    <img src="images/sprinter_2013_3.jpg" width="240" alt="minibus mercedes sprinter rental with driver in constanta mamaia" title="Minibus Mercedes Sprinter 2008 in Constanta & Mamaia" class="pad_bot2">
                </td>
            </tr>
        </table>

        <table class="responsive" width="100%" border="0" cellpadding="0" cellspacing="0">
            <tr>
                <td valign="top" align="center"><p>
                        <a href="minibusingermany.html"><font color="#000">Minibus in Germany</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusincroatia.html"><font color="#000">Minibus in Croatia</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusinromania.html"><font color="#000">Minibus in Romania</font></a></p>
                </td>
            </tr>
            <tr>
                <td valign="top" align="center"><p>
                        <a href="minibusinhungary.html"><font color="#000">Minibus in Hungary</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusinaustria.html"><font color="#000">Minibus in Austria</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusinslovakia.html"><font color="#000">Minibus in Slovakia</font></a></p>
                </td>
            </tr>
            <tr>
                <td valign="top" align="center"><p>
                        <a href="minibusinbulgaria.html"><font color="#000">Minibus in Bulgaria</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusinserbia.html"><font color="#000">Minibus in Serbia</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusinmontenegro.html"><font color="#000">Minibus in Montenegro</font></a></p>
                </td>
            </tr>
        </table> 


        <div align="center">
            <p><div class="fb-like" data-href="https://www.facebook.com/Christian Transfers" data-send="true" data-width="700" data-show-faces="false" data-action="recommend">
            </div>
            </p>
        </div>
    </div>
</div>

{include file='../common/footer.phtml'}