{include file='../common/header.phtml'}
<header class="site-title color">
        <div class="wrap">
                <div class="container">
                        <h1>Partners & Suppliers - Christian Transfers</h1>
                        <nav role="navigation" class="breadcrumbs">
                                <ul>
                                        <li><a href="/" title="Home">Home</a></li>
                                        <li>Partners & Suppliers</li>
                                </ul>
                        </nav>
                </div>
        </div>
</header>
<!-- //Page info -->


<div class="wrap">
        <div class="row">			
                <!--- Content -->
                <div class="full-width content">
                        <!-- Post -->
                        <article class="single hentry">
                                <div class="entry-content">
                                        <h3><b>For transporters in Europe - We are interested in reselling your service.</b></h3>
                                        <p>If you are a company that sells private or shared transfers to or from the airports with limusines, taxis, minivan, minibus or coaches and you dont have an excellent internet exposure, people are not able to find your service very easy, we invite you to join to our dinamic and fast expanding team.</p>
                                        <p>The procedure is very simple as you only have to contact us to start publish your transport services and car pictures on our website. After this we will able to receive job requets for your area and assign them to you.</p>
                                        <h3><b>For private and limo airport transfers providers.</b></h3>
                                        <p>If you are a company that offer private transfers to or from the airports with limusines, taxis, minivans, private rentals for your customer needs, we would love to hear from you and to have you in our team. We can deliver jobs for your areas on top of the work you already have.</p>
										<h3><b>For minibus and coaches rentals companies.</b></h3>
                                        <p>If you are a company that offer tailor made rentals for clients, tours with minibus or coaches, private transfers to or from the airports we invite you to join our network. During busy periods or summers so many jobs are lost because sometimes we can't find reliable options for transport at all our clients needs.</p>
										<h3><b>For Taxi.</b></h3>
                                        <p>For taxi companies or for independent (self employed) taxis, it is now possible to pre-register for the South of England area for the APP we are launching in the first quarter of 2018.</p>
                                        <h3><b>For same day Couriers.</b></h3>
                                        <p>For same day Couriers with bikes, vans and trucks, it is now possible to pre-register for the South of England area for the APP we are launching in the first quarter of 2018.</p>
                                        <h3><b>For recovery platforms and breakdown service.</b></h3>
                                        <p>For recovery platforms and breakdown service, it is now possible to pre-register for England and Wales area for the APP we are launching in the first quarter of 2018.</p>
                                        <h3><b>Our APP - Maya Mix.</b></h3>
                                        <p>We have been working for over a year on our application, together with a strong and brilliant team. We have included the most common services that people need today: taxis, airport and city cars and minivans, bicycle courier, van courier, relocation luton, long run trucks and recovery cars.</p>
                                        <h3><b>Want to join ?  Please drop us a message using the form on the<a href="/contact"  target="_blank"> contact page or click here</a>.</h3>
                                </div>
                        </article>
                        <!-- //Post -->
                </div>
                <!--- //Content -->
        </div>
</div>
{include file='../common/footer.phtml'}
