</main>
<footer class="footer black" role="contentinfo">
        <div class="wrap">
                <div class="row">
                        <!-- Column -->
                        <article class="one-half">
                                <h6>About us</h6>
                                <p>Christian Transfers - With a 15 years of experience in travel and transfers industry, we offer you one of the best transport options. You can choose: a private airport transfer, a regular shuttle, rent a minibus or a coach, all at just a few clicks away.</p>
                        </article>
                        <!-- //Column -->

                        <!-- Column -->
                        <article class="one-fourth">
                                <h6>Need help?</h6>
                                <p>Contact us via phone or email:</p>
                                <p class="contact-data"><span class="icon fa fa-phone"></span> +1 555 555 555</p>
                                <p class="contact-data"><span class="icon fa fa-envelope-o"></span> <a href="mailto:help@transfers.com">help@transfers.com</a></p>
                        </article>
                        <!-- //Column -->

                        <!-- Column -->
                        <article class="one-fourth">
                                <h6>Follow us</h6>
                                <ul class="social">
                                        <li><a href="#" title="facebook"><i class="fa fa-fw fa-facebook"></i></a></li>
                                        <li><a href="#" title="twitter"><i class="fa fa-fw fa-twitter"></i></a></li>
                                        <li><a href="#" title="gplus"><i class="fa fa-fw fa-google-plus"></i></a></li>
                                        <li><a href="#" title="linkedin"><i class="fa fa-fw fa-linkedin"></i></a></li>
                                        <li><a href="#" title="pinterest"><i class="fa fa-fw fa-pinterest-p"></i></a></li>
                                        <li><a href="#" title="vimeo"><i class="fa fa-fw fa-vimeo"></i></a></li>
                                </ul>
                        </article>
                        <!-- //Column -->
                </div>

                <div class="copy">
                        <p>Copyright 2016, Themeenergy. All rights reserved. </p>

                        <nav role="navigation" class="foot-nav">
                                <ul>
                                        <li><a href="#" title="Home">Home</a></li>
                                        <li><a href="#" title="Blog">Blog</a></li>
                                        <li><a href="#" title="About us">About us</a></li>
                                        <li><a href="#" title="Contact us">Contact us</a></li>
                                        <li><a href="#" title="Terms of use">Terms of use</a></li>
                                        <li><a href="#" title="Help">Help</a></li>
                                        <li><a href="#" title="For partners">For partners</a></li>
                                </ul>
                        </nav>
                </div>
        </div>
</footer>
{literal}	
	 <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-ui-timepicker-addon@1.6.3/dist/jquery-ui-timepicker-addon.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.17.0/dist/jquery.validate.min.js"></script>
    <script src="/js/functions.js"></script>

<script language='JavaScript' type='text/javascript'>
 $.ajax({
   url: "/application/search_table.php",
   type: "get",
   dataType: "html",
   data: {},
   success: function(returnData){
     $("#booking").html(returnData);
   },
   error: function(e){
     //alert(e);
   }
});
</script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-16218826-15']);
  _gaq.push(['_setDomainName', '.christiantransfers.eu']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<!-- Google Analytics END-->
{/literal}