<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<HTML>
<HEAD>
 <meta name="google-site-verification" content="Cw5reSoF0ZiKm_Xk6FMIrj5i-Ls_UzBiRR5QCaCKho4" />
 <meta name="msvalidate.01" content="20A862EDE06E9DCD7AC835A4D8CBBC71" />
 <meta name="yandex-verification" content="9712271bd60c8344" />
 <meta name="baidu-site-verification" content="" />

 <meta name="language" content="en">
 <meta http-equiv="content-language" content="ll-cc">
 <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
 <meta http-equiv="X-UA-Compatible" content="IE=edge" />
 
 <TITLE>{$title}</TITLE>
 <meta name="description" content="{$description}" />
 <meta name="keywords" content="airport transfers, christian transfers, christiantransfers eu" />
 <meta name="robots" content="index, follow, all" />
 <meta name="revisit-after" content="7days" />
 <link rel="cannonical" href="https://www.christiantransfers.eu" />
 
 <meta name="headline" content="Christian Transfers" />
 <meta name="subject" content="Christian Transfers - Airport to city transfers, international ground transportation" />
 <meta name="section" content="www.ChristianTransfers.eu" />
 <meta name="author" content="Christian Transfers - Christian Transfers Ltd - Airport transfer ground transportation network" />
  
 <meta name="owner" content="Christian Transfers Ltd" />
 <meta name="copyright" content="copyright 2006-2016 Christian Transfers - Airport transfer ground transportation network. All rights reserved" />
 <meta http-equiv ="creation-date" content="1 September 2006 12:00:00 GMT" />
 <meta http-equiv="reply-to" content="" />

<link rel="stylesheet" href="/css/reset.css" type="text/css" media="all">
<link rel="stylesheet" href="/css/layout.css" type="text/css" media="all">
<link rel="stylesheet" href="/css/style.css" type="text/css" media="all">
<link href="/include/aqua/calendar.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/include/prototype.js"></script>
<script type="text/javascript" src="/include/functions.js"></script>
<script type="text/javascript" src="/include/calendar.js"></script>
<script type="text/javascript" src="/include/calendar1.js"></script>
<script type="text/javascript" src="/include/calendar-setup.js"></script>
	
	<!-- Banner rotator top begin -->
	<script type="text/javascript" src="/js/banners.min.js"></script>
    <!-- Banner rotator top end -->	

<!--<LINK REL="SHORTCUT ICON" HREF="">-->

{literal}
<script type="text/JavaScript">
function validate_form(){
err = 'The following fields are not correctly filled:\n';
if (document.formpay.first_name.value == ''){
	err += 'No name.\n';
}
if (document.formpay.telephone.value == ''){
	err  += 'No Telephone.\n';
}
if (document.formpay.email.value == ''){
	err  += 'Email Address have to be completed.\n';
}
var filter = /^([a-zA-Z0-9_\.\-])+\@((?!aol).)[\w\.-]+\.\w{2,4}\b/;

    if (!filter.test(document.formpay.email.value)) {
    err  +='Emails from AOL.com and Hotmail.com are not accepted, please provide a valid email address.\n';
    }
if (document.formpay.flight_departure_from.value == ''){
	err += 'No Flight departure from.\n';
}
if (document.formpay.flight_number.value == ''){
	err += 'No Flight arrival number.\n';
}
if (document.formpay.address.value == ''){
	err += 'No Address.\n';
}
if (typeof document.formpay.pickup_time2 != 'undefined') {
 // use varName
 
 	if (document.formpay.flight_departure_to.value == ''){
	err += 'No Flight departure to.\n';
	}
	if (document.formpay.flight_number2.value == ''){
		err += 'No Flight departure number.\n';
	}
	if (document.formpay.address2.value == ''){
		err += 'No Address where you want to be taken.\n';
	}	
}
if (err != 'The following fields are not correctly filled:\n'){
	alert (err);
	return false;
}
else{
		return true;
	}
}
</script>

<!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute('charset','utf-8');
$.src='//cdn.zopim.com/?NKoHPskGhnBBZf1CHtCHiWnrlEXFfzlh';z.t=+new Date;$.
type='text/javascript';e.parentNode.insertBefore($,e)})(document,'script');
</script>
<!--End of Zopim Live Chat Script-->
{/literal}

</HEAD>
<body id="page1">
{literal}
<!--[if IE]> <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script> <style type="text/css"> .clear { zoom: 1;display: block;} </style> <![endif]-->{/literal}
<!--<{$varptcautare}>-->
<div class="main">
<header>
        <div class="wrapper">
		    <a href="/" title="Christian Transfers - Airport Transfers"><img src="/images/logo1.png" width="180" height="85" alt="Christian Transfers logo"/></a>
        </div>
	<nav><ul id="menu">
			<li{$timetable_active}><a href="/timetable.html"><span><span>Bus Programme</span></span></a></li>
			<li{$transfers_active}><a href="/transfers.html"><span><span>Transfers</span></span></a></li>
			<li{$minibus_active}><a href="/minibus.html"><span><span>Minibus</span></span></a></li>
			<li{$coaches_active}><a href="/blog"><span><span>Blog</span></span></a></li>
			<li{$contact_active} class="end"><a href="/contact.html"><span><span>Contact</span></span></a></li>
	</ul></nav>
</header>
	<div class="grey_border">
		<div class="{$latime_tabel_dreapta}">
		<section id="content">
			<div class="for_banners">