

<!-- Widget -->
	<div class="widget">
		<div class="textwidget">
     		<p>If you need to make a booking like an <strong>Airport Transfer</strong> please use the website booking menu by <a href="/#booking">clicking here</a></p>
			<p>If we dont have your transfer on the booking menu yet or if you need to make an enquiry for a tour with a special <strong>coach or minibus rental</strong> 
			programme please use the website <strong>tailor made</strong> menu by <a href="/tailor-made">clicking here</a>.</p>
			<p><a href="https://play.google.com/store/apps/details?id=christian.transfers.maya&hl=en_IN" target="_blank"><img src="/images/zcards/_app-google.png" alt="maya mix app for android"></a>
			</br></br></br><a href="https://itunes.apple.com/us/app/maya-mix/id1330460397?mt=8" target="_blank"><img src="/images/zcards/_app-apple.png" alt="maya mix app for ios"></a></p>
			<p>If you need to contact us with other enquiries or to join our team please use the contact form by <a href="/contact">clicking here</a></p>
		</div>
	</div>
<!-- //Widget -->
