
    <!--- Sidebar -->
        <aside class="one-fourth sidebar right">
            <!-- Widget -->
            <div class="widget">
                <h4>Company details</h4>
                <div class="textwidget">
				    <p><img src="/images/logo1.png" width="85" height="35">&nbsp;Christian Transfers Ltd - Number 10137098</p>
                    <p>Office hours (Monday - Friday): 09:00 - 18:00</p>
                    <p>Bookings are made to the website menu and confirmations only by email</p>
                </div>
            </div>
            <!-- //Widget -->

            <!-- Widget -->
            <div class="widget">
            <!--<h4>Advertisment</h4>
                <a href="#"><img src="images/uploads/advertisment.jpg" alt="" /></a> -->
            </div>
            <!-- //Widget -->

            <!-- Widget -->
            <div class="widget">
                <h4>Contact details</h4>
                <div class="textwidget">
                    <h5>Location</h5>
                    <p>Gatwick, London, Uk</p>
                    <h5>Phones</h5>
				<!--<p class="contact-data"><a href="tel:+4401293823141"><span class="icon fa fa-mobile black"></span> +44(0)1293823141</a></p>-->
					<p class="contact-data"><a href="tel:+4407463715859"><span class="icon fa fa-mobile black"></span> +44(0)7463715859</a></p>
					<p>Due to high volume of calls we'll not always be able to answer your call, that's why this number it's working in Whatsapp messaging system. If your price is not on the website already, the offer will always be sent by email.</p>
                </div>
            </div>
            <!-- //Widget -->
        </aside>
    <!--- //Sidebar -->