
    <!-- Services -->
		<div class="services boxed white" id="services">
			
			<!-- Item -->
			<article class="columngallery wow fadeIn">
				<figure class="featured-image">
					<img src="images/uploads/airport transfers.jpg" alt="car and minivans for airport transfers" title="Car and minivans for airport transfers" />
					<div class="overlay">
						<a href="/airport-transfers" class="expand">+</a>
					</div>
				</figure>
				<div class="details">
					<h4><a href="/airport-transfers">Airport transfers</a></h4>
					<p>The cars and the minivans used day by day for decades, for airport transfers and ground transportation needs.</p>
					<a class="more" title="Read more" href="/airport-transfers">Read more</a>
				</div>
			</article>
			<!-- //Item -->
			
			<!-- Item -->
			<article class="columngallery wow fadeIn" data-wow-delay=".2s">
				<figure class="featured-image">
					<img src="images/uploads/executive and vip cars hire.jpg" alt="executive and vip cars hire" title="Executive and vip cars hire" />
					<div class="overlay">
						<a href="/limousines" class="expand">+</a>
					</div>
				</figure>
				<div class="details">
					<h4><a href="/limousines">EXECUTIVE and VIP CARS HIRE</a></h4>
					<p>Private car for luxury travel in EXECUTIVE and VIP vehicle. Mercedes-Benz, Audi, BMW or better for high expectations.</p>
					<a class="more" title="Read more" href="/limousines">Read more</a>
				</div>
			</article>
			<!-- //Item -->
			
			<!-- Item -->
			<article class="columngallery wow fadeIn" data-wow-delay=".4s">
				<figure class="featured-image">
					<img src="images/uploads/coach rentals and airport transfers.jpg" alt="coach rentals and airport transfers" title="Coach rentals and airport transfers" />
					<div class="overlay">
						<a href="/coaches" class="expand">+</a>
					</div>
				</figure>
				<div class="details">
					<h4><a href="/coaches">Coach rentals</a></h4>
					<p>A wide range of quality vehicles, a simple renting process, rental periods which suit your plan really is the ultimate way to your coaches hire.</p>
					<a class="more" title="Read more" href="/coaches">Read more</a>
				</div>
			</article>
			<!-- //Item -->
			
			<!-- Item -->
			<article class="columngallery wow fadeIn" data-wow-delay=".6s">
				<figure class="featured-image">
					<img src="images/uploads/minibus rentals and airport transfers.jpg" alt="minibus rentals" title="Minibus rentals" />
					<div class="overlay">
						<a href="/minibus" class="expand">+</a>
					</div>
				</figure>
				<div class="details">
					<h4><a href="/minibus">Minibus rentals</a></h4>
					<p>Accessible for hire from the leading specialists, minibus airport transfers, minibus rentals for tours or tailor made requests and all other types of travel.</p>
					<a class="more" title="Read more" href="/minibus">Read more</a>
				</div>
			</article>
			<!-- //Item -->
        
		</div>
		<div class="services boxed white" id="services">
			
			<!-- Item -->
			<article class="columngallery wow fadeIn">
				<figure class="featured-image">
					<img src="images/uploads/shuttle and shared transfers.jpg" alt="shuttle and shared transfers" title="Shuttle and shared transfers" />
					<div class="overlay">
						<a href="/timetable" class="expand">+</a>
					</div>
				</figure>
				<div class="details">
					<h4><a href="/timetable">Shuttle transfers</a></h4>
					<p>Shared services operated only on specific routes with fixed stops and timetables, with cars, minivans, minibuses or coaches.</p>
					<a class="more" title="Read more" href="/timetable">Read more</a>
				</div>
			</article>
			<!-- //Item -->
			
			<!-- Item -->
			<article class="columngallery wow fadeIn" data-wow-delay=".2s">
				<figure class="featured-image">
					<img src="images/uploads/taxi.jpg" alt="taxi and taxi assist" title="Taxi and taxi assist" />
					<div class="overlay">
						<a href="/taxi" class="expand">+</a>
					</div>
				</figure>
				<div class="details">
					<h4><a href="/taxi">TAXI & TAXI ASSIST</a></h4>
					<p>The classic taxi as we know it, the assist option been for disabled persons, taxis which can embark you with your wheel chair.</p>
					<a class="more" title="Read more" href="/taxi">Read more</a>
				</div>
			</article>
			<!-- //Item -->
			
			<!-- Item -->
			<article class="columngallery wow fadeIn" data-wow-delay=".4s">
				<figure class="featured-image">
					<img src="images/uploads/same day couriers.jpg" alt="same day couriers and urgent couriers" title="Same day couriers and urgent couriers" />
					<div class="overlay">
						<a href="/couriers" class="expand">+</a>
					</div>
				</figure>
				<div class="details">
					<h4><a href="/couriers">SAME DAY COURIERS</a></h4>
					<p>Same day delivery gives you options, 365 days a year. Providing flexible, reliable and cost-effective solutions.</p>
					<a class="more" title="Read more" href="/couriers">Read more</a>
				</div>
			</article>
			<!-- //Item -->
			
			<!-- Item -->
			<article class="columngallery wow fadeIn" data-wow-delay=".6s">
				<figure class="featured-image">
					<img src="images/uploads/recovery cars.jpg" alt="recovery cars" title="Recovery cars" />
					<div class="overlay">
						<a href="/recovery-car" class="expand">+</a>
					</div>
				</figure>
				<div class="details">
					<h4><a href="/recovery-car">RECOVERY CARS</a></h4>
					<p>You need it on average 1-5 times in your life, why should you pay monthly for decades ? Download our App and pay only when you need it.</p>
					<a class="more" title="Read more" href="/recovery-car">Read more</a>
				</div>
			</article>
			<!-- //Item -->		
		</div>
    <!-- //Services -->
