{include file='../common/header_with_form_breadcrumbs.phtml'}
<div class="wrap">
        <div class="row">
                <!--- Content -->
                <div class="one-half content offset">
                        <table class="hover">
                                <tr>
                                        <th>Details</th>
                                        <th>Start City</th>
                                        <th>Arrival City</th>
                                </tr>
                                <tr>
                                        <td><b>Hour</br>City</b></br>Station</td>
                                        <td><a href="/airport_transfer/romania-constanta-otopeni_airport"><b>01:00</br>Constanta</b></br>Your Adress</a></td>
                                        <td><a href="/airport_transfer/romania-constanta-otopeni_airport"><b>04:00</br>Otopeni Airport</b></br>Departures</a></td>
                                </tr>
                                <tr>
                                        <td><b>Hour</br>City</b></br>Station</td>
                                        <td><a href="/airport_transfer/romania-constanta-otopeni_airport"><b>03:30</br>Constanta</b></br>Your Adress</a></td>
                                        <td><a href="/airport_transfer/romania-constanta-otopeni_airport"><b>06:30</br>Otopeni Airport</b></br>Departures</a></td>
                                </tr>
                                <tr>
                                        <td><b>Hour</br>City</b></br>Station</td>
                                        <td><a href="/airport_transfer/romania-constanta-otopeni_airport"><b>05:30</br>Constanta</b></br>Your Adress</a></td>
                                        <td><a href="/airport_transfer/romania-constanta-otopeni_airport"><b>08:30</br>Otopeni Airport</b></br>Departures</a></td>
                                </tr>
                                <tr>
                                        <td><b>Hour</br>City</b></br>Station</td>
                                        <td><a href="/airport_transfer/romania-constanta-otopeni_airport"><b>08:30</br>Constanta</b></br>Your Adress</a></td>
                                        <td><a href="/airport_transfer/romania-constanta-otopeni_airport"><b>11:30</br>Otopeni Airport</b></br>Departures</a></td>
                                </tr>
                                <tr>
                                        <td><b>Hour</br>City</b></br>Station</td>
                                        <td><a href="/airport_transfer/romania-constanta-otopeni_airport"><b>11:30</br>Constanta</b></br>Your Adress</a></td>
                                        <td><a href="/airport_transfer/romania-constanta-otopeni_airport"><b>14:30</br>Otopeni Airport</b></br>Departures</a></td>
                                </tr>
                                <tr>
                                        <td><b>Hour</br>City</b></br>Station</td>
                                        <td><a href="/airport_transfer/romania-constanta-otopeni_airport"><b>13:30</br>Constanta</b></br>Your Adress</a></td>
                                        <td><a href="/airport_transfer/romania-constanta-otopeni_airport"><b>16:30</br>Otopeni Airport</b></br>Departures</a></td>
                                </tr>
                                <tr>
                                        <td><b>Hour</br>City</b></br>Station</td>
                                        <td><a href="/airport_transfer/romania-constanta-otopeni_airport"><b>15:30</br>Constanta</b></br>Your Adress</a></td>
                                        <td><a href="/airport_transfer/romania-constanta-otopeni_airport"><b>18:30</br>Otopeni Airport</b></br>Departures</a></td>
                                </tr>
                        </table>
                </div>
                <div class="one-half content offset">
                        <table class="hover">
                                <tr>
                                        <th>Details</th>
                                        <th>Start City</th>
                                        <th>Arrival City</th>
                                </tr>
                                <tr>
                                        <td><b>Hour</br>City</b></br>Station</td>
                                        <td><a href="/airport_transfer/romania-bucharest_airport-constanta"><b>01:00</br>Otopeni Airport</b></br>Arrivals</a></td>
                                        <td><a href="/airport_transfer/romania-bucharest_airport-constanta"><b>04:00</br>Constanta</b></br>Your Adress</a></td>
                                </tr>
                                <tr>
                                        <td><b>Hour</br>City</b></br>Station</td>
                                        <td><a href="/airport_transfer/romania-bucharest_airport-constanta"><b>03:00</br>Otopeni Airport</b></br>Arrivals</a></td>
                                        <td><a href="/airport_transfer/romania-bucharest_airport-constanta"><b>06:00</br>Constanta</b></br>Your Adress</a></td>
                                </tr>
                                <tr>
                                        <td><b>Hour</br>City</b></br>Station</td>
                                        <td><a href="/airport_transfer/romania-bucharest_airport-constanta"><b>08:00</br>Otopeni Airport</b></br>Arrivals</a></td>
                                        <td><a href="/airport_transfer/romania-bucharest_airport-constanta"><b>11:00</br>Constanta</b></br>Your Adress</a></td>
                                </tr>
                                <tr>
                                        <td><b>Hour</br>City</b></br>Station</td>
                                        <td><a href="/airport_transfer/romania-bucharest_airport-constanta"><b>12:30</br>Otopeni Airport</b></br>Arrivals</a></td>
                                        <td><a href="/airport_transfer/romania-bucharest_airport-constanta"><b>15:30</br>Constanta</b></br>Your Adress</a></td>
                                </tr>
                                <tr>
                                        <td><b>Hour</br>City</b></br>Station</td>
                                        <td><a href="/airport_transfer/romania-bucharest_airport-constanta"><b>15:00</br>Otopeni Airport</b></br>Arrivals</a></td>
                                        <td><a href="/airport_transfer/romania-bucharest_airport-constanta"><b>18:00</br>Constanta</b></br>Your Adress</a></td>
                                </tr>
                                <tr>
                                        <td><b>Hour</br>City</b></br>Station</td>
                                        <td><a href="/airport_transfer/romania-bucharest_airport-constanta"><b>17:30</br>Otopeni Airport</b></br>Arrivals</a></td>
                                        <td><a href="/airport_transfer/romania-bucharest_airport-constanta"><b>20:30</br>Constanta</b></br>Your Adress</a></td>
                                </tr>
                                <tr>
                                        <td><b>Hour</br>City</b></br>Station</td>
                                        <td><a href="/airport_transfer/romania-bucharest_airport-constanta"><b>19:00</br>Otopeni Airport</b></br>Arrivals</a></td>
                                        <td><a href="/airport_transfer/romania-bucharest_airport-constanta"><b>22:00</br>Constanta</b></br>Your Adress</a></td>
                                </tr>
                                <tr>
                                        <td><b>Hour</br>City</b></br>Station</td>
                                        <td><a href="/airport_transfer/romania-bucharest_airport-constanta"><b>20:30</br>Otopeni Airport</b></br>Arrivals</a></td>
                                        <td><a href="/airport_transfer/romania-bucharest_airport-constanta"><b>23:30</br>Constanta</b></br>Your Adress</a></td>
                                </tr>
                                <tr>
                                        <td><b>Hour</br>City</b></br>Station</td>
                                        <td><a href="/airport_transfer/romania-bucharest_airport-constanta"><b>22:30</br>Otopeni Airport</b></br>Arrivals</a></td>
                                        <td><a href="/airport_transfer/romania-bucharest_airport-constanta"><b>01:30</br>Constanta</b></br>Your Adress</a></td>
                                </tr>
                        </table>
                </div>
                <div class="one-half content textongrey">
                        <h2>About Shuttle Otopeni Constanta route</h2>
                        <p class="lead">Shuttle is running every day. Hours = (RO) Romania Time.</p>
                        <p>Shuttle bus is running after this schedulle and cannot wait for late tourists.</p>
                        <p>Shuttle bus can pick you up and drop of only in the stations listed below.</p>
                        <p>After you choose the transfer from this list below please make the bookings and payments online using the left website menu. We cannot make bookings on the phone and without prepayment.</p>
                        <p>Please make reservations at least 48 hours prior to your transfer.</p>
                        <p>For weekend transfers (Saturday and Sunday) transfers please do your bookings from Thursday or Friday.</p>
                </div>
				<div class="one-half content textongrey">
                        <h2>About Otopeni Airport</h2>
                        <p>Bucharest Henri Coanda International Airport is Romania's busiest international airport, located in Otopeni, 16.5 km north of Bucharest's city centre. It is currently one of two airports serving the capital of Romania. The other is Aurel Vlaicu Airport, which no longer serves scheduled passenger traffic. Airport serves as headquarters for TAROM, the country's national airline.</p>
                        <p>The airport is named after Romanian flight pioneer Henri Coanda, builder of Coanda-1910 aircraft and discoverer of the Coanda effect of fluidics.</p>
                        <p>Until 1965, it was a major airfield for the Romanian Air Force, with Baneasa Airport serving as Bucharest's commercial airport. In 1965, with the growth of air traffic, the Otopeni airbase was converted to a commercial airport. The runway was modernized and extended to 3,500 metres , making it one of the longest in Europe at that time.</p>
                        <p>A new passenger terminal, with a capacity of 1,200,000 passengers per year, was opened on 13 April 1970, for domestic and international flights. An improvement program added a second runway in 1986, expanding capacity to 35 aircraft movements per hour. In 1992, Otopeni Airport became a regular member of Airports Council International.</p>
                        <p>In March 2012, all air traffic except for business air traffic was transferred from Aurel Vlaicu Airport to Henri Coanda International Airport.</p>
                </div>
                <div class="one-half content textongrey">
                        <h2>About Constanta city</h2>
                        <p>Constanta it is the capital of Constanta county and Romania's largest sea port, a great city to begin to explore the wonders of the sea, in summer it's also the gateway to the country's seaside resorts. It is a place with a long and interesting past, attested by its many Roman vestiges, historic buildings, facades and mosques that color the Old City Centre. While in the area, one can relax on the sandy beaches of the Black Sea or visit old villages, wineries, ancient monuments and the Danube Delta, a bird-lover's paradise.</p>
                        <p>You can do sunbathing or you can swim in the Black Sea. The most significant beaches are in the Mamaia resort which is in the north part of Constanta. It consists of about 6-7 kilometers of sandy beaches with absolutely no rocks. It's also full of hotels, clubs and bars and extremely popular and fashionable in the summer. More over in the off season, they are a great place for taking pictures walks, or rides with the atv or enduro motorcycle.</p>
                        <p>To the south there are a string of summer resorts: Eforie North, Eforie South, Costinesti, Neptun, Olimp, Venus, being recommended because it has a more relaxed atmosphere and for its lush forests that end near the sea.</p>
                        <p>Vama Veche to the south, close to the Bulgarian border is a former hippie/bohemian beach village turned into a commercial venture over the years but still one of the few places on the Romanian coast where camping is still valid.</p>
                </div>
                <!--- //Content -->
        </div>
</div>
{include file='../common/footer.phtml'}