<?php

$titluri=array(
	"indexCopiedTitle" => "Airport Transfers - Christian Transfers - ChristianTransfers.eu",
    "indexTitle" => "Airport Transfers - Christian Transfers - ChristianTransfers.eu",
	"contactTitle" => "Christian Transfers contact page ChristianTransfers.eu",
	"tailorTitle" => "Christian Transfers tailor made transfers ChristianTransfers.eu",
    
	"indexMeta" => "Airport transfers, cars, minivans, minibus, coaches rentals, ground transportation in Croatia Serbia Bulgaria Romania Hungary Germany Austria",
	"contactMeta" => "Christian Transfers contact details, contact form on contact page - Christian Transfers ltd, London Gatwick Airport, Uk - ChristianTransfers.eu",
	"tailorMeta" => "Custom and tailor made form page for airport transfers, executive & vip cars, minibus, coach private rentals - Christian Transfers - ChristianTransfers.eu",
	
	"timetableTitle" => "Timetable Budapest Szeged Timisoara Belgrade Oradea Cluj Otopeni Constanta",
	"timetableMeta" => "Shuttle bus timetable and coach travel programme from Budapest to Szeged Timisoara Belgrade, from Budapest to Oradea Cluj and from Otopeni Airport to Constanta",
	"budapesttimisoaraTitle" => "Shuttle bus timetable Budapest Airport Szeged Arad Timisoara",
	"budapesttimisoaraMeta" => "Shuttle bus travel programme for route Budapest Airport, Kecskemet, Szeged, Arad, Timisoara, buses, van, minibus and taxi transport - Christian Transfers",
	"budapestclujTitle" => "Shuttle bus timetable Budapest Airport Oradea Cluj Turda Aiud",
	"budapestclujMeta" => "Shuttle bus travel programme for route Budapest Nepliget, Budapest Airport, Oradea, Cluj, Aiud, Turda, buses, minibus, taxi transport - Christian Transfers",
	"timisoarabelgradeTitle" => "Shuttle bus timetable Timisoara to Belgrade Airport",
	"timisoarabelgradeMeta" => "Shuttle bus travel programme for route Timisoara to Belgrade Airport find here the shuttle bus schedule, buses, van, minibus and taxi transport - Christian Transfers",
	"otopeniconstantaTitle" => "Shuttle bus timetable Otopeni Bucharest Airport to Constanta",
	"otopeniconstantaMeta" => "Shuttle bus travel programme for route Otopeni Airport Constanta find here the shuttle bus schedule, buses, van, minibus and taxi transport - Christian Transfers",	

	"transfersTitle" => "Airport transfers and cars or minivans private hire or rentals",
	"transfersMeta" => "Christian Transfers organize airport transfers and private rentals with cars and minivans, group transportation London, Bucharest, Sofia, Vienna, Zagreb, Munich, Dusseldorf",
	"limousinesTitle" => "Executive and vip airport transfers and private car hire",
	"limousinesMeta" => "Christian Transfers organize executive and vip airport transfers in London, Gatwick, Heathrow, Bucharest, Belgrade, Munich, Dusseldorf, Vienna, Zagreb, Zurich, Paris",
	"minibusTitle" => "Minibus airport transfers and minibus rentals - Christian Transfers",
	"minibusMeta" => "Christian Transfers offer minbus rentals and airport transfers in Uk, Spain, France, Germany, Croatia, Romania, Serbia, Hungary, Bulgaria, Austria, Slovakia, Belgium",	
	"coachesTitle" => "Coach airport transfers and coach rentals - Christian Transfers",
	"coachesMeta" => "Coach, bus and minicoach rentals or airport transfers in Uk, Hungary, Bulgaria, Austria, Slovakia, Belgium, Spain, France, Germany, Croatia, Romania, Serbia",
	"taxiTitle" => "Taxi app for Gatwick London Crawley Brighton Redhill Portsmouth",
	"taxiMeta" => "Taxi app for taxi owners or private hire minicab offices in Gatwick Crawley Redhill Brighton Portsmouth Southampton Guilford Bristol Birmingham Cheltenham Gloucester",
	"couriersTitle" => "Urgent and same day courier service Gatwick Crawley London",
	"couriersMeta" => "Express courier service or same day courier service app in Gatwick Crawley Brighton London Wimbledon Fulham Chelsea Portsmouth Southampton Guilford Birmingham Bristol",
	"recoverycarTitle" => "Digital roadside assistance service | recovery car | towing trucks app in Gatwick",
	"recoverycarMeta" => "Digital roadside assistance service, recovery car, towing trucks app in Brighton London Southampton Birmingham Bristol Manchester Liverpool Newcastle Cardiff Swansea Glasgow Edinburgh",

	"aboutusTitle" => "About us - Christian Transfers", 
	"aboutusMeta" => "Christian Transfers offer: airport transfers, executive & vip transfers, minibus & coach rentals, taxi courier and recovery car app, shuttle transfers",
	"helpTitle" => "Faq & Help - Frequently asked questions - Christian Transfers",
	"helpMeta" => "Faq and help for Christian Transfers services, frequently asked questions for Christian Transfers services - Christian Transfers",
	"howitworksTitle" => "How it works - Christian Transfers",
	"howitworksMeta" => "How it works, how the bookings system work, how to hire a coach, how to book a long transfer or airport transfer with Christian Transfers?",
	"privacyTitle" => "Privacy Policy - Christian Transfers",
	"privacyMeta" => "Privacy Policy page for Christian Transfers, privacy policy for book transfers and ground transportation services - Christian Transfers",
	"termsTitle" => "Terms and Conditions - Christian Transfers",
	"termsMeta" => "Terms and Conditions page for Christian Transfers, terms and conditions to book a transfer or ground transportation services - Christian Transfers",
	"errorTitle" => "Error page - Christian Transfers",
	"errorMeta" => "Error page from Christian Transfers website, christiantransfers.eu",
	
	"partnersTitle" => "Partners drivers & Suppliers companies for Christian Transfers",
	"partnersMeta" => "Partners suppliers companies for ariport transfers, minibus coaches and bus rental companies, taxi individual drivers, couriers or recovery cars join Christian Transfers",
	"countriesTitle" => "Countries and cities where Christian Transfers operate",
	"countriesMeta" => "Christian Transfers airport transfers in Uk Germany Croatia Romania Serbia Hungary Bulgaria Austria Spain France Italy Greece Belgium Netherlands Cyprus Czech Republic Poland",

	"ukTitle" => "Heathrow Gatwick Stansted Luton airport taxi & minicab transfer service", 
	"ukMeta" => "Christian Transfers offer airport transfers, taxis, minicabs in Gatwick Crawley Heathrow Brighton Portsmouth Southampton Guilford Bristol Birmingham Manchester Gloucester",
	"germanyTitle" => "Munich Dusseldorf airport taxi transfers Christian Transfers Germany",
	"germanyMeta" => "Christian Transfers Germany offer offer private taxi and minvan airport transfers in Munich and Stuttgart Airport, Duseldorf and Frankfurt Airports, Berlin Tegel and Schonefeld Airport - Christian Transfers Germany",
	"spainTitle" => "Airport transfers minivans minibus coach rental Christian Transfers Spain",
	"spainMeta" => "Christian Transfers Spain offer private taxi and minvan airport transfers in Madrid Airport, Barcelona Airport, Valencia Airport or Sevilla Airport - Christian Transfers Spain",
	"franceTitle" => "Airport transfers minivans minibus coach rental Christian Transfers France",
	"franceMeta" => "Christian Transfers France offer private taxi and minvan airport transfers in Paris Charles de Gaulle Airport, Orly and Beauvais Airport, Lyon, Nice and Chambery Airport - Christian Transfers France",
	"italyTitle" => "Airport transfers minivans minibus coach rental Christian Transfers Italy",
	"italyMeta" => "Christian Transfers Italy offer private taxi and minvan airport transfers in Milan Malpensa and Linate Airports, Bergamo and Trieste Airports, Treviso or Venice Airport - Christian Transfers Italy",
	"croatiaTitle" => "Minibus coach bus minivan private hire in Zagreb Christian Transfers Croatia",
	"croatiaMeta" => "Christian Transfers Croatia offer private taxi and minvan airport transfers in Zagreb and Rijeka Airports, Dubrovnik and Pula Airports, Zadar and Split Airports - Christian Transfers Croatia",
	"greeceTitle" => "Airport transfers minivans and private taxis Christian Transfers Greece",
	"greeceMeta" => "Christian Transfers Greece offer private taxi and minvan airport transfers in Athens Airport, Thessaloniki Airport, Katerini and Kalamaria Transfers - Christian Transfers Greece",
	"romaniaTitle" => "Minibus coach bus minivan private hire in Bucharest Christian Transfers Romania",
	"romaniaMeta" => "Christian Transfers Romania offer private taxi and minvan airport transfers in Bucharest Otopeni Airport, Timisoara and Cluj Airport, Iasi or Constanta Airport - Christian Transfers Romania",

	"albaniaTitle" => "Airport taxi transfers minivans in Albania Christian Transfers",
	"albaniaMeta" => "Christian Transfers offer airport taxi transfers and minivans of 1-8 places city transfers in Albania from Tirana to Skopje and Ohrid - Christian Transfers Albania",
	"austriaTitle" => "Airport taxi transfers and minivans in Vienna Salzburg Innsbruck",
	"austriaMeta" => "Christian Transfers offer airport taxi transfers and minivans in Vienna Airport to Vienna or Linz, Salzburg Airport to Passau or Salzburg, Innsbruck Airport to Zell am See, Kaprun or Kitzbuhel",
	"belgiumTitle" => "Airport taxi transfers and minivans in Brussels and Charleroi Airport",
	"belgiumMeta" => "Christian Transfers offer airport taxi transfers and minivans for groups to travel from Brussels Airport and Charleroi Airport to Brussels - Christian Transfers Belgium",
	"bulgariaTitle" => "Airport taxi transfers and minivan in Sofia Varna Burgas Plovdiv",
	"bulgariaMeta" => "Christian Transfers offer airport taxi and minivan transfers in Sofia Varna and Burgas Airports to travel to Veliko Tarnovo, Plovdiv, Russe, Albena, Golden Sands, Sunny Beach, Nessebar",
	"cyprusTitle" => "Airport taxi and minivans transfer services in Larnaca Paphos Airports",
	"cyprusMeta" => "Christian Transfers offer airport taxi transfers and minivans for Larnaca and Paphos Airports to travel to Nicosia, Limassol, Lefkara, Famagusta, Larnaca Bay or Ercan Airport in Cyprus",
	"czechTitle" => "Airport taxi and minivans transfer services in Prague Brno Airports",
	"czechMeta" => "Christian Transfers offer airport taxi and minivans transfers in Prague and Brno Airports to travel to Prague, Brno, Pardubice, Ostrava, Cesky Krumlov, Karlovy Vary",
	"hungaryTitle" => "Airport taxi transfers and minivans in Budapest & Szeged",
	"hungaryMeta" => "Christian Transfers offer airport taxi transfers and minivans with drivers to travel in Budapest, Szeged, Kecskemet, Balaton, Pecs, Gyor, Siofok - Christian Transfers Hungary",
	"irelandTitle" => "Airport taxi transfers and minivans in Dublin Ireland",
	"irelandMeta" => "Christian Transfers offer airport taxi and minivans transfers in Ireland from Dublin Airport to Dublin and back to Dublin Airport - Christian Transfers Ireland",
	
	"macedoniaTitle" => "Taxi minibus coach bus minivan service in Skopje and Ohrid Macedonia",
	"macedoniaMeta" => "Christian Transfers offer taxi minibus coach bus minivan hire service in Skopje and Ohrid Airports to travel to Sofia, Thessaloniki, Belgrade, Podgorita, Tirana, Zagreb",
	"montenegroTitle" => "Taxi minibus coach bus minivan service in Podgorita Tivat Airport",
	"montenegroMeta" => "Christian Transfers offer taxi minibus coach bus minivan hire service from Podgorita, Dubrovnik and Tivat Airport to travel to Kotor, Budva, Bar, Becici, Herceg Novi, Igalo, Sutomore",
	"netherlandsTitle" => "Airport taxi and minivans transfers in Amsterdam and Eidhoven Airports",
	"netherlandsMeta" => "Christian Transfers offer airport taxi and minivans transfers in Amsterdam and Eidhoven Airports to travel to Amsterdam, Venlo, Maastricht, Rotterdam, Dusseldorf, Koln, Essen",
	"polandTitle" => "Airport taxi and minivan transfers in Warsaw Krakow Airports",
	"polandMeta" => "Christian Transfers offer airport taxi and minivan transfers in Warsaw Chopin and Modulin Airports, Krakow Airport to travel to Warsaw and Krakow",
	"serbiaTitle" => "Airport taxi minivan coach bus transfers from Belgrade Airport",
	"serbiaMeta" => "Christian Transfers offer airport taxi minivan minibus coach transfers from Belgrade Airport to Belgrade, Novi Sad, Subotica, Cacak, Jagodina, Kapaonik, Kragujevac, Pristina",
	"slovakiaTitle" => "Airport taxi minivan coach bus transfers from Bratislava Airport",
	"slovakiaMeta" => "Christian Transfers offer airport taxi minivan minibus coach transfers from Bratislava, Vienna, Budapest or Prague Airports to travel to Bratislava, Kosice, Trnava",
	"sloveniaTitle" => "Airport taxi and minivans transfers from Ljubliana Airport",
	"sloveniaMeta" => "Christian Transfers offer airport taxi and minivans transfers from Ljubliana Airport to travel to Ljubliana, Maribor, Bled, Zagreb, Pula, Graz, Vienna, Budapest",
	"switzerlandTitle" => "Airport taxi and minivans transfers from Zurich Airport",
	"switzerlandMeta" => "Christian Transfers offer airport taxi and minivans transfers from Zurich and Geneva Airports to travel to Zurich, St Gallen, Lucerne, Basel, Lausanne, Geneva, Innsbruck, Munich",
	
	"chinaTitle" => "Airport taxi and minivans transfers from Shanghai Pudong and Hongqiao",
	"chinaMeta" => "Christian Transfers offer airport taxi and minivans transfers from Shanghai Pudong Airport and Shanghai Hongqiao Airport to travel to Shanghai or fly to Beijing",
	"russiaTitle" => "Airport taxi and minivans transfer services from Moscow Airports",
	"russiaMeta" => "Christian Transfers offer airport taxi and minivans transfers from Moscow Airports Domodedovo, Sheremetyevo, Vnukovo and Zhukovsky to travel to Moscow city center",
    "turkeyTitle" => "Airport taxi and minivans transfers from Ataturk and Sabiha Gokcen Airports",
	"turkeyMeta" => "Christian Transfers offer airport taxi and minivans transfers from Istanbul Ataturk Airport, Sabiha Gokcen Airport and Antalya Airport to travel to Istanbul, Antalya, Alanya",
	"indiaTitle" => "Airport taxi and minivans transfers from Christian Transfers India",
	"indiaMeta" => "Christian Transfers offer airport taxi and minivans transfers - Christian Transfers India",
	
);
?>