{include file='../common/header.phtml'}

	<!-- Main -->
	<main class="main" role="main">
		<!-- Page info -->
		<header class="site-title color">
			<div class="wrap">
				<div class="container">
					<h1>Minibus rentals and minibus airport transfers - Christian Transfers</h1>
					<nav role="navigation" class="breadcrumbs">
						<ul>
							<li><a href="index.html" title="Home">Home</a></li>
							<li>Minibus</li>
						</ul>
					</nav>
				</div>
			</div>
		</header>
		<!-- //Page info -->
		
		
		<div class="wrap">
			<div class="row">
				
				<!--- Sidebar -->
				<aside class="one-fourth sidebar left">
					
					<!-- Widget -->
					<div class="widget">
						<h4>Minibus rentals</h4>
						<a href="#"><img src="images/uploads/minibus rentals.jpg" alt="minibus rentals" title="Minibus rentals" /></a>
					</div>
					<!-- //Widget -->
					
					<!-- Widget -->
					<div class="widget">
						<h4>How to make a booking?</h4>
						<div class="textwidget">
							<p>If you need to make a booking like an Airport Transfers please use the website booking menu by <a href="/">clicking here</a></p>
							<p>If we dont have yet your transfer on the booking menu or if you need to make a booking like a tour with a special minibus rental programme please use the website tailor made menu by <a href="/tailor-made">clicking here</a></p>
							<p>If you need to contact us with other enquiries or to join our team please use the contact form by <a href="/contact">clicking here</a></p>
						</div>
					</div>
					<!-- //Widget -->
					
					<!-- Widget -->
					<div class="widget">
						<h4>Airport transfers</h4>
						<a href="#"><img src="images/uploads/minibus airport transfers.jpg" alt="minibus airport transfers" title="Minibus airport transfers" /></a>
					</div>
					<!-- //Widget -->
				</aside>
				<!--- //Sidebar -->
				
				<!--- Content -->
				<div class="three-fourth content">
					<!-- Post -->
					<article class="single hentry">
						<div class="entry-featured">
							<img src="images/uploads/minibus rentals and airport transfers.jpg" alt="minibus rentals and airport transfers" title="Minibus rentals and airport transfers" />
						</div>
						<div class="entry-content">
							<h2>Minibus rental (only with our driver)</h2>
							<p class="lead">If you have an organized group, do not hesitate to rent a private minibus with driver. </p>
							<p>All minibuses offered by us are renting only with driver. Optional on request we can offer specialized travel guide for foreign languages.</p>
							<p>Our company provides minivans for any type of event: Transfers to / from airport, city tours, travel in Germany, Croatia, Austria, Slovakia, Romania, Bulgaria, Hungary, Serbia, Montenegro or abroad, business trips, transportation for delegates, conferences, holidays at home and abroad, teambuilding for companies, private tours or special events.</p>
							<p>We provide minivans of various types and sizes at highly competitive rates in the countries listed below with few days confirmation.</p>
                            <p>You can communicate the budget for vehicles rental and we will do as soon as possible a complete offer according with your request. Rent conditions and exceptional value for money make this version a very good alternative.</p>
						</div>
					</article>
					<!-- //Post -->
				</div>
				<!--- //Content -->
			</div>
		</div>
	</main>
	<!-- //Main -->
	
	<!-- Services iconic -->
    <div class="services iconic white">
        <div class="wrap">
            <div class="row">
				<!-- Item -->
				<div class="one-third wow fadeIn">
					<span class="circle"><span class="icon fa fa-heart-o"></span></span>
					<h3>Shuttle Buses</h3>
					<p>Shuttle bus services. These services operate only on specific routes with fixed stops and fixed timetable, with minibuses or coaches.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".2s">
					<span class="circle"><span class="icon fa fa-magic"></span></span>
					<h3>Cars & Minivans hire</h3>
					<p>The cars and the minivans used day by day, for decades, for your business transfers or airport transfers.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".4s">
					<span class="circle"><span class="icon fa fa-paperclip"></span></span>
					<h3>Taxi & taxi assist</h3>
					<p>The classic taxi as we know it, the assist option been for disabled persons, taxis which can embark you with your wheel chair.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn">
					<span class="circle"><span class="icon fa fa-heart-o"></span></span>
					<h3>Minibuses Rental</h3>
					<p>Minibuses accessible, hire from the leading specialists, for airport transfers and all types of travel.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".2s">
					<span class="circle"><span class="icon fa fa-magic"></span></span>
					<h3>Executive cars hire</h3>
					<p>Private car hire with driver, Mercedes-Benz E or V classe, Audi A6, BMW 5 series, first class service.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".4s">
					<span class="circle"><span class="icon fa fa-paperclip"></span></span>
					<h3>Same day couriers</h3>
					<p>Same day delivery gives you options, 365 days a year. Providing flexible, reliable and cost-effective solutions.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn">
					<span class="circle"><span class="icon fa fa-heart-o"></span></span>
					<h3>Coaches rental</h3>
					<p>A wide range of quality vehicles, a simple renting process, rental periods which suit your plan really is the ultimate way to your coaches hire.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".2s">
					<span class="circle"><span class="icon fa fa-magic"></span></span>
					<h3>Vip cars hire</h3>
					<p>Private car hire with driver in VIP vehicle. Mercedes-Benz S, Audi A8, Mercedes-Benz V or similar models for luxury travel.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".4s">
					<span class="circle"><span class="icon fa fa-paperclip"></span></span>
					<h3>Recovery cars</h3>
					<p>You need it on average 1-5 times in your life, why should you pay monthly for decades ? Download our App and pay only when you need it.</p>
				</div>
				<!-- //Item -->
            </div>
        </div>
	</div>

{include file='../common/footer.phtml'}