{include file='../common/header.phtml'}
	
	<!-- Main -->
	<main class="main" role="main">
		<!-- Page info -->
		<header class="site-title color">
			<div class="wrap">
				<div class="container">
					<h1>Coaches rentals and coaches airport transfers - Christian Transfers</h1>
					<nav role="navigation" class="breadcrumbs">
						<ul>
							<li><a href="index.html" title="Home">Home</a></li>
							<li>Coaches</li>
						</ul>
					</nav>
				</div>
			</div>
		</header>
		<!-- //Page info -->
		
		
		<div class="wrap">
			<div class="row">
				
				<!--- Sidebar -->
				<aside class="one-fourth sidebar left">
					<!-- Widget -->
					<div class="widget">
						<h4>Airport transfers</h4>
						<a href="#"><img src="images/uploads/coach airport transfers.jpg" alt="coach airport transfers" title="Coach airport transfers" /></a>
					</div>
					<!-- //Widget -->
					
					<!-- Widget -->
					<div class="widget">
						<h4>Coach rentals</h4>
						<a href="#"><img src="images/uploads/coach rentals.jpg" alt="coach rentals" title="Coach rentals" /></a>
					</div>
					<!-- //Widget -->
					
					<!-- Widget -->
					<div class="widget">
						<h4>How to make a booking?</h4>
						<div class="textwidget">
							<p>If you need to make a booking like an Airport Transfers please use the website booking menu by <a href="/">clicking here</a></p>
							<p>If we dont have yet your transfer on the booking menu or if you need to make a booking like a tour with a special coach rental programme please use the website tailor made menu by <a href="/tailor-made">clicking here</a></p>
							<p>If you need to contact us with other enquiries or to join our team please use the contact form by <a href="/contact">clicking here</a></p>
						</div>
					</div>
					<!-- //Widget -->
					
					<!-- Widget -->
					<div class="widget">
						<h4>Airport transfers</h4>
						<a href="#"><img src="images/uploads/coach airport transfers romania.jpg" alt="coach airport transfers romania" title="Coach airport transfers Romania" /></a>
					</div>
					<!-- //Widget -->
					
					<!-- Widget -->
					<div class="widget">
						<h4>Coach rentals</h4>
						<a href="#"><img src="images/uploads/coach rentals bulgaria.jpg" alt="coach rentals bulgaria" title="Coach rentals Bulgaria" /></a>
					</div>
					<!-- //Widget -->
					
					<!-- Widget -->
					<div class="widget">
						<h4>Tailor made rentals</h4>
						<a href="#"><img src="images/uploads/coach airport transfers serbia.jpg" alt="coach airport transfers serbia" title="Coach airport transfers Serbia" /></a>
					</div>
					<!-- //Widget -->
				</aside>
				<!--- //Sidebar -->
				
				<!--- Content -->
				<div class="three-fourth content">
					<!-- Post -->
					<article class="single hentry">
						<div class="entry-featured">
							<img src="images/uploads/coach rentals and airport transfers.jpg" alt="coach rentals and airport transfers" title="Coach rentals and airport transfers" />
						</div>
						<div class="entry-content">
							<h2>Christian Transfers - Coach transfers and rentals</h2>
							<p class="lead">Christian Transfers offer airport transfers and bus rentals from several Airports.</p>
							<p>Pick-up from all Austria Airports Vienna, Salzburg, Graz, Innsbruck Tirol and going to Vienna, Salzburg, Graz, Zell am See, Kaprun, Saalbach, Hinterglemm, Gasteinertal, Flachau, Flachauwinkel, Kleinarl, Großarl, Wagrain, Maria Alm, Leogang, Dienten, Mühlbach a. Hochkönig, Saalfelden, Piesendorf, Schladming, Kitzbühel, Westendorf, Brixen, Hopfgarten, Wildschönau, Kirchberg, Scheffau, Ellmau, Söll, Obergurgl, Hochgurgl, Sölden, Ischgl, Galtür, Lech, Zürs, St. Anton am Arlberg, Serfaus, Ladis, Fiss, Fulpmes, Hintertux, Igls, Mayrhofen, Neustift, Seefeld, Going, Niederau, Alpbach, St.Johann in Tirol.</p>
							<p>We organize transfer by taxis and minvans or rentals with coaches and buses to all Austria destinations or abroad to Hungary, Slovakia, Czech Republic, Germany, Switzerland, Croatia, Italy, Slovenia, Serbia and Bosnia Hertegovina.</p>
						    <p>Pick-up from all Hungary Airports and cities Budapest, Balaton, Szeged and Debrecen and going to Balatonalmadi, Balatonboglar, Balatonfured, Bekescsaba, Debrecen, Dunaujvaros, Gyor, Kecskemet, Miskolc, Nyiregyhaza, Pecs, Siofok, Sopron, Szeged, Szekesfehervar, Szentes, Szolnok, Szombhately, Veszprem, Timisoara Airport, Arad, Cluj, Oradea, Brasov, Sibiu, Zagreb, Rijeka, Dubrovnik, KRK Airport, National Parc Plitvicer, Osijek, Novalja Pag, Varazdin, Crikvenica, Opatija, Porec, Pula, Sibenik, Split, Umag, Maribor, Zadar, Ljubljana, Belgrad, Novi Sad, Budapest Airport, Pecs, Szeged, Trieste, Udine, Venezia Airport, Graz, Klagenfurt, Linz, Salzburg, Wien.</p>
							<p>We organize transfer by taxis and minvans or rentals with coaches and buses to all Hungary destinations or abroad to Austria, Croatia, Romania, Polska, Germany, Slovakia, Italy, Slovenia, Serbia, Ukraine, Motenegro and Bosnia Hertegovina.</p>
							<p>Pick-up from all Croatia Airports Zagreb, Rijeka, Dubrovnik and going to Zagreb, Rijeka, Dubrovnik, KRK Airport, National Parc Plitvicer, Osijek, Novalja Pag, Varazdin, Crikvenica, Opatija, Porec, Pula, Sibenik, Split, Umag, Maribor, Zadar, Ljubljana, Belgrad, Novi Sad, Budapest Airport, Pecs, Szeged, Trieste, Udine, Venezia Airport, Graz, Klagenfurt, Linz, Salzburg, Wien.</p>
							<p>We organize transfer by taxis and minvans or rentals with coaches and buses to all Croatia destinations or abroad to Austria, Hungary, Italy, Slovenia, Serbia, Motenegro and Bosnia Hertegovina.</p>
							<p>Pick-up from all Germany Airports and cities Munich, Berlin, Frankfurt for events in Hamburg, Stuttgart, Bremen, Dusseldorf, Nuremberg, Strasbourg, Paris, Torino, Milano, Roma, Venezia Copenhagen, Warsaw, Wroclaw, Poznan, Prague, Brno, Wien, Salzburg, Zurich, Berne, Geneva, Amsterdam, Eindhoven, Brussel, Zagreb, Maribor, Ljubljana, Belgrad, Budapest, Bratislava.</p>
							<p>We organize transfer by taxis and minvans or rentals with coaches and buses to all Germany destinations or abroad to France, Belgium, Holland, Luxembourg, Switzerland, Austria, Denmark, Liechtenstein, Czech Republic, Italy, Croatia, Polska, Slovakia, Slovenia.</p>
							<p>Pick-up from Bucharest Otopeni Airport, Constanta Airport, Timisoara Airport Brasov or Sibiu for groups of 5 to unlimited number of persons and transfers to all Bucharest or Romania Hotels or for Bucharest city tour - House of the People, The Village Museum, Triumphal Arch, Romanian Peasant Museum, Romanian Athenaeum, Patriarchal Church. One day tour arround Bucharest - Mogosoaia Palace, Manasteries like: Cernica, Pasarea, Tiganesti, Caldarusani and Snagov.Transilvania Tour - One full day to visit 4 Castles in Transilvania: Peles, Pelisor, Bran, Cantacuzino. After this we go to a very nice dinner in Brasov.</p>
							<p>Inter city transfers with private minivans, mini coaches and coaches for special events, wedings, conferences, parties, private groups or special ceremony.</p>
						</div>
					</article>
					<!-- //Post -->
				</div>
				<!--- //Content -->
			</div>
		</div>
	</main>
	<!-- //Main -->
	
	<!-- Services iconic -->
    <div class="services iconic white">
        <div class="wrap">
            <div class="row">
				<!-- Item -->
				<div class="one-third wow fadeIn">
					<span class="circle"><span class="icon fa fa-heart-o"></span></span>
					<h3>Shuttle Buses</h3>
					<p>Shuttle bus services. These services operate only on specific routes with fixed stops and fixed timetable, with minibuses or coaches.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".2s">
					<span class="circle"><span class="icon fa fa-magic"></span></span>
					<h3>Cars & Minivans hire</h3>
					<p>The cars and the minivans used day by day, for decades, for your business transfers or airport transfers.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".4s">
					<span class="circle"><span class="icon fa fa-paperclip"></span></span>
					<h3>Taxi & taxi assist</h3>
					<p>The classic taxi as we know it, the assist option been for disabled persons, taxis which can embark you with your wheel chair.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn">
					<span class="circle"><span class="icon fa fa-heart-o"></span></span>
					<h3>Minibuses Rental</h3>
					<p>Minibuses accessible, hire from the leading specialists, for airport transfers and all types of travel.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".2s">
					<span class="circle"><span class="icon fa fa-magic"></span></span>
					<h3>Executive cars hire</h3>
					<p>Private car hire with driver, Mercedes-Benz E or V classe, Audi A6, BMW 5 series, first class service.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".4s">
					<span class="circle"><span class="icon fa fa-paperclip"></span></span>
					<h3>Same day couriers</h3>
					<p>Same day delivery gives you options, 365 days a year. Providing flexible, reliable and cost-effective solutions.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn">
					<span class="circle"><span class="icon fa fa-heart-o"></span></span>
					<h3>Coaches rental</h3>
					<p>A wide range of quality vehicles, a simple renting process, rental periods which suit your plan really is the ultimate way to your coaches hire.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".2s">
					<span class="circle"><span class="icon fa fa-magic"></span></span>
					<h3>Vip cars hire</h3>
					<p>Private car hire with driver in VIP vehicle. Mercedes-Benz S, Audi A8, Mercedes-Benz V or similar models for luxury travel.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".4s">
					<span class="circle"><span class="icon fa fa-paperclip"></span></span>
					<h3>Recovery cars</h3>
					<p>You need it on average 1-5 times in your life, why should you pay monthly for decades ? Download our App and pay only when you need it.</p>
				</div>
				<!-- //Item -->
            </div>
        </div>
	</div>

{include file='../common/footer.phtml'}