{include file='../common/header.phtml'}
<header class="site-title color">
    <div class="wrap">
        <div class="container">
            <h1>Partners & Suppliers - Christian Transfers</h1>
            <nav role="navigation" class="breadcrumbs">
                <ul>
                <li><a href="/" title="Home">Home</a></li>
                <li>Partners & Suppliers</li>
                </ul>
            </nav>
        </div>
    </div>
</header>
<!-- //Page info -->


<div class="wrap">
    <div class="row">			
    <!--- Content -->
        <div class="full-width content">
          <!-- Post -->
            <article class="single hentry">
                <div class="entry-content">
				<h3><b>Ground transportation companies - We are interested in selling your service</b></h3>
				  <p>In ground transportation industry every experience in the street may be different due to high expectation of today's client. That's why we need to count on your abilities of being professional at all time, provide a world class experience for our clients, maintain up to date all legal papers required for you and your car.</p>
                  <p>If you are a company that sells private or shared transfers to or from the airports with cars and minivan, minibus and coache rentals for organized groups, shuttle buses companies, towing and recovery cars and you don't have an excellent internet exposure, people are not able to find your service very easy, we invite you to join to our dinamic and fast expanding team.</p>
                  <p>The procedure is very simple as you only have to contact us on the <a href="/contact">contact page by clicking here</a>.</p>
                <h3><b>For private and limo airport transfers providers</b></h3>
                  <p>If you are a company that offer private transfers to or from the airports with cars, taxis, minivans, private rentals for your customer needs, we would love to hear from you and to have you in our team. We can deliver jobs for your areas on top of the work you already have.</p>
				<h3><b>For minibus and coaches rentals companies</b></h3>
                  <p>If you are a company that offer tailor made rentals for clients, tours with minibus or coaches, private transfers to or from the airports we invite you to join our network. During busy periods or summers so many jobs are lost because sometimes we can't find reliable options for transport at all our clients needs.</p>
				<h3><b>For taxi drivers and taxi companies</b></h3>
                  <p>For taxi companies or for independent (self employed) taxis, it is now possible to register for Europe area. Christian Transfers App gives a choice of on-demand and pre-booked options. 
				  Join our team to receive more jobs, to earn more money on the same time in the street. Easy to use partner-driver app, easy and free to join, dowload, register and start drive. 
				  See your work in the home pc or app for iOS and Android, <a href="/taxi"> click here for more details.</a></p>
                <h3><b>For towing and recovery car service providers</b></h3>
                  <p>For towing and recovery car companies service providers, it is now possible to register for Europe area. No registration fees, clear pick-ups and destinations locations, no preferred partners, payment by card in the app, no need to carry cash and recovery cars. Want to see more ? <a href="/recovery-car"> click here for more details.</a></p>
				<h3><b>For Urgent and same day Couriers</b></h3>
                  <p>For same day Couriers with bikes, moto, car or vans and trucks, it is now possible to register for Europe area, Rates adapted to actual market, weekly payments for dispatch or commision based services at one of the best rates from the Uk.
				  Easy to use partner/driver app, easy to join, dowload, register and start drive - Manage your work in the app for iOS and Android. <a href="/couriers"> click here for more details.</a></p>
                <h3><b>Our APP - Christian Transfers App !</b></h3>
                  <p>We have been working for over a year on our application, together with a strong and brilliant team. We have included the most common services that people need today: taxis, airport and city cars and minivans, bicycle&moto courier, van courier, relocation luton, long run trucks and recovery car and towing services.</p>
                <h3><b>Want to join Christian Transfers team ?</b></h3>
                  <p>Please drop us a message using the form on the <a href="/contact">contact page or click here</a>.</p>
				</div>
            </article>
          <!-- //Post -->
        </div>
    <!--- //Content -->
    </div>
</div>
{include file='../common/footer.phtml'}
