{include file='../common/header.phtml'}
	
	<!-- Main -->
	<main class="main" role="main">
		<!-- Page info -->
		<header class="site-title color">
			<div class="wrap">
				<div class="container">
					<h1>Christian Transfers Romania</h1>
					<nav role="navigation" class="breadcrumbs">
						<ul>
							<li><a href="/" title="Christian Transfers - Airport Transfers">Go to Home</a></li>
							<li>We are in Romania</li>
						</ul>
					</nav>
				</div>
			</div>
		</header>
		<!-- //Page info -->
	
	
	<!-- MAIN Gallery including Titles start -->
    <div class="maingallery">
        <h5>Available services for Romania</h5>
          <p class="lead">Christian Transfers offer transfers from Airport and all the cities of Romania.</p>
		  <p>Pick-up from Otopeni Airport, Timisoara Airport, Cluj Airport, Constanta Airport, Suceava Airport, Iasi Airport, Bucharest, Timisoara, Arad, Cluj, Oradea, Sibiu, Brasov, Constanta, Mangalia, all seaside and mountain resorts, as the rest of the cities in Romania.</p>
		  <p>We organize transfer by taxis and minvans or rentals with coaches and buses to all Romania destinations or abroad to Hungary, Bulgaria, Cyprus, Greece, Croatia, Poland, Czech Republic, Germany, Austria, Switzerland, Netherlands, Slovenia, Slovakia, Serbia, Bosnia Hertegovina, Macedonia, Montenegro, Albain, Spain, Italy, Belgium, France, Ireland, Uk.</p>

    <!-- Portfolio Gallery Start -->
    <div class="rowgallery">
        <div class="columngallery">
            <div class="contentgallery">
                
				{include file='../common/sidebar2.phtml'}
				
            </div>
        </div>
		<div class="columngallery">
            <div class="contentgallery">
                <img src="images/romania/otopeni airport.jpg" alt="otopeni airport transfers" title="Otopeni Airport Transfers" style="width:100%">
                <p>Bucharest Otopeni Airport Picture</p>
	            <h3>Otopeni Airport Transfers</h3>
                <p>Christian Transfers offer private transfers from Otopeni Airport to all the cities from Romania or Bulgaria. Private transfers for long trips, with saloon or minivans to Brasov, Sinaia, Predeal to the ski resorts, or to Mamaia, Constanta, Varna, Burgas or Sunny Beach to the Black Sea resorts.</p>
            </div>
        </div>
        <div class="columngallery">
            <div class="contentgallery">
                <img src="images/romania/timisoara airport.jpg" alt="timisoara airport" title="Timisoara Airport Transfers" style="width:100%">
	            <p>Timisoara Airport Picture</p>
                <h3>Timisoara Airport Transfers</h3>
                <p>Christian Transfers offer private transfers from Timisoara Airport to all the cities arround. Private transfers for long trips, with saloon or minivans to Timisoara, Arad, Sibiu, Craiova in Romania or Szeged, Debrecen and Budapest in Hungary and to Belgrade, Novi Sad or Subotica in Serbia.</a></p>
            </div>
        </div>
        <div class="columngallery">
            <div class="contentgallery">
                <img src="images/romania/cluj airport.jpg" alt="cluj airport transfers" title="Cluj Airport Transfers" style="width:100%">
                <p>Cluj Airport Picture</p>
	            <h3>Cluj Airport Transfers</h3>
                <p>Christian Transfers offer private transfers from Cluj Airport to all the cities arround. Private transfers for long trips, with saloon or minivans to Cluj, Oradea, targu Mures, Arad, Szeged, Budapest Airport or Budapest city center, Satu Mare, Baia Mare, Sighetul Marmatiei or Suceava Monasteries.</a></p>
            </div>
        </div>
        <div class="columngallery">
            <div class="contentgallery">
                <img src="images/romania/iasi airport.jpg" alt="iasi airport transfers" title="Iasi Airport Transfers" style="width:100%">
	            <p>Iasi Airport Picture</p>
                <h3>Iasi Airport Transfers</h3>
                <p>Christian Transfers offer private transfers from Iasi Airport to all the cities arround. Private transfers for long trips, with saloon or minivans to Iasi, Bacau, Buzau, Suceava, Targu Mures, Piatra Neamt, Focsani, Bucharest, Brasov, Sinaia or to Chisinau, Odessa, Balti, Cernauti, Tiraspol in Moldova.</a></p>
            </div>
        </div>	
        <div class="columngallery">
            <div class="contentgallery">
                <img src="images/romania/constanta airport.jpg" alt="constanta airport transfers" title="Constanta Airport Transfers" style="width:100%">
	            <p>Constanta Airport Picture</p>
                <h3>Constanta Airport Transfers</h3>
                <p>Christian Transfers offer private transfers from Constanta Airport to all the cities arround. Private transfers for long trips, with saloon or minivans to Constanta, Mamaia, Costinesti, Eforie South or North, Vama Veche from Romania Varna, Burgas, Albena, Balchick, Golden Sands from Bulgaria.</a></p>
            </div>
        </div>
		<div class="columngallery">
            <div class="contentgallery">
                <img src="images/romania/suceava airport.jpg" alt="suceava airport transfers" title="Suceava Airport Transfers" style="width:100%">
	            <p>Suceava Airport Picture</p>
                <h3>Suceava Airport Transfers</h3>
                <p>Christian Transfers offer private transfers from Suceava Airport to all the cities arround. Private transfers for long trips, with saloon or minivans to Suceava, Iasi, Cluj, Bacau, Bucharest, Piatra Neamt, Cernauti or to Humor, Voronet, Moldovita or Sucevita from Moldavian Monasteries.</a></p>
            </div>
        </div>
		
		<div class="columngallery">
            <div class="contentgallery">
                <img src="images/uploads/coach rentals and airport transfers.jpg" alt="coach and minibus rentals" title="Coach and minibus rentals" style="width:100%">
	            <p>Bus rental picture</p>
                <h3>Bus & Minibus Rental</h3>
                <p>Bus & Minibus Rental in Romania from Bucharest, Cluj, Timisoara and Iasi area. How you consider to rent a minibus or a bus vs classic train or bus tickets for a long trip? It's about commodity vs utility? It's about luggages? the price might be better and you'll receive a much better service.</a></p>
            </div>
        </div>
    </div>

        <!-- <div class="contentgallery">
                <img src="images/..." alt="" title="" style="width:100%">
	            <p>...</p>
                <h3>...</h3>
                <p>...</p>
        </div> -->
       <!-- Gallery END -->
	   
	    <p><strong>Taxi App - Maya Mix</strong> app for taxi is the app where you can book a taxi when you need a ride. <strong>For taxi providers</strong> - we are looking to partner with taxi drivers and taxi companies from Otopeni Airport, Timisoara, Cluj, Constanta, Suceava, Iasi, Bucharest, Arad, Oradea, Sibiu, Brasov, Constanta areas.</p>
	    <p><strong>Courier App - Maya Mix</strong> app for courier is the app where you can book a motto, car or van when you need to send an urgent parcel arround the corner or to another city. All deliveries are made for your parcel, we dont wait for other parcel to share the same direction. <strong>For couriers providers</strong> - we are looking to partner with courier drivers and courier companies Otopeni Airport, Timisoara, Cluj, Constanta, Suceava, Iasi, Bucharest, Arad, Oradea, Sibiu, Brasov, Constanta areas.</p>
		<p><strong>Recovery Car App - Maya Mix</strong> app for recovery car is the app where you can book a recovery car when your car break down. You'll can do this after you downloaded the app on your smartphone, it's so easy to use it, like any taxi app. You'll save money by paying only when you need it and not paying monthly for decades. You'll save time by setting the pickup and dropp off point in the app in few touch of the phone buttons, not in 45 minutes over the phone with old fashion providers, you'll choose the recovery car capacity and offcourse you'll see driver details after he accept the job. 
		<strong>For recovery car providers</strong> - we are looking to partner with recovery car owners and recovery car companies Otopeni Airport, Timisoara, Cluj, Constanta, Suceava, Iasi, Bucharest, Arad, Oradea, Sibiu, Brasov, Constanta areas.</p>
		<p><strong>Ground Transportation</strong> - We organize <a href="/airport-transfers"><b>airport transfers</b></a>, <a href="/limousines"><b>executive and vip transfers</b></a>, <a href="/minibus"><b>minibuses rentals</b></a>, <a href="/coaches"><b>coaches rentals</b></a>, <a href="/taxi"><b>taxi app</b></a>, <a href="/couriers"><b>courier app</b></a> and <a href="/recovery-car"><b>recovery car app</b></a> in <a href="/christian-transfers-uk"><b>Uk</b></a>, <a href="/christian-transfers-germany"><b>Germany</b></a>, <a href="/christian-transfers-spain"><b>Spain</b></a>, 
		<a href="/christian-transfers-france"><b>France</b></a>, <a href="/christian-transfers-italy"><b>Italy</b></a>, <a href="/christian-transfers-croatia"><b>Croatia</b></a>, <a href="/christian-transfers-greece"><b>Greece</b></a>, <a href="/christian-transfers-romania"><b>Romania</b></a>, <a href="/christian-transfers-albania"><b>Albania</b></a>, <a href="/christian-transfers-austria"><b>Austria</b></a>, <a href="/christian-transfers-belgium"><b>Belgium</b></a>, <a href="/christian-transfers-bulgaria"><b>Bulgaria</b></a>, <a href="/christian-transfers-cyprus"><b>Cyprus</b></a>, <a href="/christian-transfers-czech"><b>Czech Republic</b></a>, 
		<a href="/christian-transfers-hungary"><b>Hungary</b></a>, <a href="/christian-transfers-ireland"><b>Ireland</b></a>, <a href="/christian-transfers-macedonia"><b>Macedonia</b></a>, <a href="/christian-transfers-montenegro"><b>Montenegro</b></a>, <a href="/christian-transfers-netherlands"><b>Netherlands</b></a>, <a href="/christian-transfers-poland"><b>Poland</b></a>, <a href="/christian-transfers-serbia"><b>Serbia</b></a>, <a href="/christian-transfers-slovakia"><b>Slovakia</b></a>, <a href="/christian-transfers-slovenia"><b>Slovenia</b></a>, <a href="/christian-transfers-switzerland"><b>Switzerland</b></a> in Europe and <a href="/christian-transfers-china"><b>China</b></a>, 
		<a href="/christian-transfers-russia"><b>Russia</b></a>, <a href="/christian-transfers-turkey"><b>Turkey</b></a>, <a href="/christian-transfers-india"><b>India</b></a> in Asia.</p>
	    <p>Train Stations in Romania</p>
		<iframe src="https://public.opendatasoft.com/explore/embed/dataset/europe-railway-station/map/?refine.icc=RO&location=6,45.73686,24.64233&basemap=jawg.streets&dataChart=eyJxdWVyaWVzIjpbeyJjb25maWciOnsiZGF0YXNldCI6ImV1cm9wZS1yYWlsd2F5LXN0YXRpb24iLCJvcHRpb25zIjp7fX0sImNoYXJ0cyI6W3siYWxpZ25Nb250aCI6dHJ1ZSwidHlwZSI6ImxpbmUiLCJmdW5jIjoiQVZHIiwieUF4aXMiOiJmY3N1YnR5cGUiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjRkY1MTVBIn1dLCJ4QXhpcyI6ImJlZ2lubGlmZXMiLCJtYXhwb2ludHMiOiIiLCJ0aW1lc2NhbGUiOiJ5ZWFyIiwic29ydCI6IiJ9XSwiZGlzcGxheUxlZ2VuZCI6dHJ1ZSwiYWxpZ25Nb250aCI6dHJ1ZX0%3D&static=true&datasetcard=true&scrollWheelZoom=true" width="100%" height="500" frameborder="0"></iframe>
    </div>
    <!-- MAIN Gallery including Titles end -->
	</main>
	<!-- //Main -->
	
		<!-- Page info -->
		<header class="site-title color">
			<div class="wrap">
				<div class="container">
					<h1>Christian Transfers Services</h1>
					<nav role="navigation" class="breadcrumbs">
						<ul>
							<li><a href="/" title="Christian Transfers - Airport Transfers">Go to Home</a></li>
							<li>We are in Romania</li>
						</ul>
					</nav>
				</div>
			</div>
		</header>
		<!-- //Page info -->
{include file='../common/sidebar3.phtml'}
{include file='../common/footer.phtml'}