{include file='../common/header.phtml'}
	
	<!-- Main -->
	<main class="main" role="main">
		<!-- Page info -->
		<header class="site-title color">
			<div class="wrap">
				<div class="container">
					<h1>Bratislava - Christian Transfers Slovakia</h1>
					<nav role="navigation" class="breadcrumbs">
						<ul>
							<li><a href="/" title="Christian Transfers - Airport Transfers">Go to Home</a></li>
							<li>We are in Slovakia</li>
						</ul>
					</nav>
				</div>
			</div>
		</header>
		<!-- //Page info -->
		
				<div class="wrap">
			<div class="row">
				
				<!--- Sidebar -->
				<aside class="one-fourth sidebar left">
					<!-- Widget -->
					<div class="widget">
						<h4>Bratislava Transfers</h4>
						<a href="#"><img src="images/slovakia/bratislava.jpg" alt="bratislava transfers" title="Bratislava Transfers" /></a>
					</div>
					<!-- //Widget -->
					
					{include file='../common/sidebar2.phtml'}
					
					<!-- Widget -->
					<div class="widget">
						<h4>Trnava Transfers</h4>
						<a href="#"><img src="images/slovakia/trnava.jpg" alt="trnava transfers" title="Trnava Transfers" /></a>
					</div>
					<!-- //Widget -->
					
					<!-- Widget -->
					<div class="widget">
						<h4>Kosice Transfers</h4>
						<a href="#"><img src="images/slovakia/kosice.jpg" alt="kosice transfers" title="Kosice Transfers" /></a>
					</div>
					<!-- //Widget -->
				</aside>
				<!--- //Sidebar -->
				
				<!--- Content -->
				<div class="three-fourth content">
					<!-- Post -->
					<article class="single hentry">
						<div class="entry-featured">
							<img src="images/slovakia/bratislava aiport.jpg" alt="bratislava aiport transfers" title="Bratislava Aiport Transfers" />
						</div>
						<div class="entry-content">
							<h2>Slovakia transfers - Christian Transfers</h2>
							<p class="lead">Christian Transfers offer transfers from Airport and all the cities of Slovakia.</p>
							<p>Pick-up from Bratislava Airport, Bratislava, Kosice, Trnava and other cities.</p>
							<p>We organize transfer by taxis and minvans or rentals with coaches and buses to all Slovakia destinations or abroad to Romania, Hungary, Bulgaria, Cyprus, Greece, Croatia, Poland, Czech Republic, Germany, Austria, Switzerland, Netherlands, Slovenia, Serbia, Bosnia Hertegovina, Macedonia, Montenegro, Albain, Spain, Italy,Belgium, France, Ireland. Uk.</p>
				            
							<p><strong>Taxi App - Maya Mix</strong> app for taxi is the app where you can book a taxi when you need a ride. <strong>For taxi providers</strong> - we are looking to partner with taxi drivers and taxi companies from Bratislava, Kosice, Trnava, Kosice, Presov areas.</p>
							<p><strong>Courier App - Maya Mix</strong> app for courier is the app where you can book a motto, car or van when you need to send an urgent parcel arround the corner or to another city. All deliveries are made for your parcel, we dont wait for other parcel to share the same direction. <strong>For couriers providers</strong> - we are looking to partner with courier drivers and courier companies from Bratislava, Kosice, Trnava, Kosice, Presov areas.</p>
							<p><strong>Recovery Car App - Maya Mix</strong> app for recovery car is the app where you can book a recovery car when your car break down. You'll can do this after you downloaded the app on your smartphone, it's so easy to use it, like any taxi app. You'll save money by paying only when you need it and not paying monthly for decades. You'll save time by setting the pickup and dropp off point in the app in few touch of the phone buttons, not in 45 minutes over the phone with old fashion providers, you'll choose the recovery car capacity and offcourse you'll see driver details after he accept the job. 
							<strong>For recovery car providers</strong> - we are looking to partner with recovery car owners and recovery car companies from Bratislava, Kosice, Trnava, Kosice, Presov areas.</p>
						    <p><strong>Ground Transportation</strong> - We organize <a href="/airport-transfers"><b>airport transfers</b></a>, <a href="/limousines"><b>executive and vip transfers</b></a>, <a href="/minibus"><b>minibuses rentals</b></a>, <a href="/coaches"><b>coaches rentals</b></a>, <a href="/taxi"><b>taxi app</b></a>, <a href="/couriers"><b>courier app</b></a> and <a href="/recovery-car"><b>recovery car app</b></a> in <a href="/christian-transfers-uk"><b>Uk</b></a>, <a href="/christian-transfers-germany"><b>Germany</b></a>, <a href="/christian-transfers-spain"><b>Spain</b></a>, 
							<a href="/christian-transfers-france"><b>France</b></a>, <a href="/christian-transfers-italy"><b>Italy</b></a>, <a href="/christian-transfers-croatia"><b>Croatia</b></a>, <a href="/christian-transfers-greece"><b>Greece</b></a>, <a href="/christian-transfers-romania"><b>Romania</b></a>, <a href="/christian-transfers-albania"><b>Albania</b></a>, <a href="/christian-transfers-austria"><b>Austria</b></a>, <a href="/christian-transfers-belgium"><b>Belgium</b></a>, <a href="/christian-transfers-bulgaria"><b>Bulgaria</b></a>, <a href="/christian-transfers-cyprus"><b>Cyprus</b></a>, <a href="/christian-transfers-czech"><b>Czech Republic</b></a>, 
							<a href="/christian-transfers-hungary"><b>Hungary</b></a>, <a href="/christian-transfers-ireland"><b>Ireland</b></a>, <a href="/christian-transfers-macedonia"><b>Macedonia</b></a>, <a href="/christian-transfers-montenegro"><b>Montenegro</b></a>, <a href="/christian-transfers-netherlands"><b>Netherlands</b></a>, <a href="/christian-transfers-poland"><b>Poland</b></a>, <a href="/christian-transfers-serbia"><b>Serbia</b></a>, <a href="/christian-transfers-slovakia"><b>Slovakia</b></a>, <a href="/christian-transfers-slovenia"><b>Slovenia</b></a>, <a href="/christian-transfers-switzerland"><b>Switzerland</b></a> in Europe and <a href="/christian-transfers-china"><b>China</b></a>, 
							<a href="/christian-transfers-russia"><b>Russia</b></a>, <a href="/christian-transfers-turkey"><b>Turkey</b></a>, <a href="/christian-transfers-india"><b>India</b></a> in Asia.</p>
							
						</div>
					</article>
					<!-- //Post -->
				</div>
				<!--- //Content -->
			</div>
		</div>
	</main>
	<!-- //Main -->
	
		<!-- Page info -->
		<header class="site-title color">
			<div class="wrap">
				<div class="container">
					<h1>Christian Transfers Services</h1>
					<nav role="navigation" class="breadcrumbs">
						<ul>
							<li><a href="/" title="Christian Transfers - Airport Transfers">Go to Home</a></li>
							<li>We are in Slovakia</li>
						</ul>
					</nav>
				</div>
			</div>
		</header>
		<!-- //Page info -->
	
	{include file='../common/sidebar3.phtml'}

    {include file='../common/footer.phtml'}