{include file='../common/header.phtml'}
	
	<!-- Main -->
	<main class="main" role="main">
		<!-- Page info -->
		<header class="site-title color">
			<div class="wrap">
				<div class="container">
					<h1>Skopje - Christian Transfers Macedonia</h1>
					<nav role="navigation" class="breadcrumbs">
						<ul>
							<li><a href="index.html" title="Home">Home</a></li>
							<li>Transfers</li>
						</ul>
					</nav>
				</div>
			</div>
		</header>
		<!-- //Page info -->
		
				<div class="wrap">
			<div class="row">
				
				<!--- Sidebar -->
				<aside class="one-fourth sidebar left">
					<!-- Widget -->
					<div class="widget">
						<h4>Skopje Airport</h4>
						<a href="#"><img src="images/macedonia/skopje airport.jpg" alt="skopje airport" title="Skopje Airport Transfers" /></a>
					</div>
					<!-- //Widget -->
					
					<!-- Widget -->
					<div class="widget">
						<h4>Ohrid</h4>
						<a href="#"><img src="images/macedonia/ohrid.jpg" alt="ohrid transfers" title="Ohrid Transfers" /></a>
					</div>
					<!-- //Widget -->
					
					<!-- Widget -->
					<div class="widget">
						<h4>Ohrid Airport</h4>
						<a href="#"><img src="images/macedonia/ohrid airport.jpg" alt="ohrid airport transfers" title="Ohrid Airport Transfers" /></a>
					</div>
					<!-- //Widget -->
				</aside>
				<!--- //Sidebar -->
				
				<!--- Content -->
				<div class="three-fourth content">
					<!-- Post -->
					<article class="single hentry">
						<div class="entry-featured">
							<img src="images/macedonia/skopje.jpg" alt="skopje airport transfers" title="Skopje Airport Transfers" />
						</div>
						<div class="entry-content">
							<h2>Macedonia transfers - Christian Transfers</h2>
							<p class="lead">Christian Transfers offer transfers from Airport and all the cities of Macedonia.</p>
							<p>Pick-up from Skopje Airport, Ohrid Airport, Skopje, Ohrid and other cities.</p>
							<p>We organize transfer by taxis and minvans or rentals with coaches and buses to all Macedonia destinations or abroad to Romania, Hungary, Bulgaria, Cyprus, Greece, Poland, Croatia, Czech Republic, Germany, Austria, Switzerland, Italy, Slovakia, Serbia, Bosnia Hertegovina, Montenegro, Uk.</p>
				            <p class="lead">How to make a booking?</p>
							<p>If you need to make a booking like an Airport Transfers please use the website booking menu by <a href="/">clicking here</a></p>
							<p>If we dont have yet your transfer on the booking menu or if you need to make a booking like a tour with a special coach rental programme please use the website tailor made menu by <a href="/tailor-made">clicking here</a></p>
							<p>If you need to contact us with other enquiries or to join our team please use the contact form by <a href="/contact">clicking here</a></p>
							
						</div>
					</article>
					<!-- //Post -->
				</div>
				<!--- //Content -->
			</div>
		</div>
	</main>
	<!-- //Main -->
	
	<!-- Services iconic -->
    <div class="services iconic white">
        <div class="wrap">
            <div class="row">
				<!-- Item -->
				<div class="one-third wow fadeIn">
					<span class="circle"><span class="icon fa fa-heart-o"></span></span>
					<h3>Shuttle Buses</h3>
					<p>Shuttle bus services. These services operate only on specific routes with fixed stops and fixed timetable, with minibuses or coaches.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".2s">
					<span class="circle"><span class="icon fa fa-magic"></span></span>
					<h3>Cars & Minivans hire</h3>
					<p>The cars and the minivans used day by day, for decades, for your business transfers or airport transfers.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".4s">
					<span class="circle"><span class="icon fa fa-paperclip"></span></span>
					<h3>Taxi & taxi assist</h3>
					<p>The classic taxi as we know it, the assist option been for disabled persons, taxis which can embark you with your wheel chair.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn">
					<span class="circle"><span class="icon fa fa-heart-o"></span></span>
					<h3>Minibuses Rental</h3>
					<p>Minibuses accessible, hire from the leading specialists, for airport transfers and all types of travel.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".2s">
					<span class="circle"><span class="icon fa fa-magic"></span></span>
					<h3>Executive cars hire</h3>
					<p>Private car hire with driver, Mercedes-Benz E or V classe, Audi A6, BMW 5 series, first class service.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".4s">
					<span class="circle"><span class="icon fa fa-paperclip"></span></span>
					<h3>Same day couriers</h3>
					<p>Same day delivery gives you options, 365 days a year. Providing flexible, reliable and cost-effective solutions.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn">
					<span class="circle"><span class="icon fa fa-heart-o"></span></span>
					<h3>Coaches rental</h3>
					<p>A wide range of quality vehicles, a simple renting process, rental periods which suit your plan really is the ultimate way to your coaches hire.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".2s">
					<span class="circle"><span class="icon fa fa-magic"></span></span>
					<h3>Vip cars hire</h3>
					<p>Private car hire with driver in VIP vehicle. Mercedes-Benz S, Audi A8, Mercedes-Benz V or similar models for luxury travel.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".4s">
					<span class="circle"><span class="icon fa fa-paperclip"></span></span>
					<h3>Recovery cars</h3>
					<p>You need it on average 1-5 times in your life, why should you pay monthly for decades ? Download our App and pay only when you need it.</p>
				</div>
				<!-- //Item -->
            </div>
        </div>
	</div>
		
	<!-- //Main -->

{include file='../common/footer.phtml'}