{include file='../common/header.phtml'}
<div class="wrap">
    <div class="row">
        <p align="left"><font face="Arial" size="2"><strong>For local transporters in Europe.</strong></font></p>
        <p align="left"><font face="Arial" size="2">We are now expanding to all Europe. All local transportators who are willing to join to a new and dinamic team are welcome. The procedure is very simple as you just have to contact us and start publish your transport services on our website. After this we are all able to receive orders for your local area and we just assign them to you. How ever we cannot promise you a volum depending on your area but we can promise to promote as much as we can the services on the internet or local magazines.</font></p>
        <p align="left"><font face="Arial" size="2"><strong>For tourist agents.</strong></font></p>
        <p align="left"><font face="Arial" size="2">We are now expanding to all Europe. All local tourist agents who are selling entertenmeint transportation like city tours or country tours of any kind are welcome to contact us to see the possibilities of working toghether in order to provide a more efficient service to our valuable coustomers and also to yours. </font></p>
        <p align="left"><font face="Arial" size="2"><strong>We are intrested to sell ...</strong></font></p>
        <p align="left"><font face="Arial" size="2">Private or shared transfers to or from the Airports with limusines, taxies, minivan or coaches. Shuttle buses, trains, boats or feriboats, private or shared jets, private or shared city or country tours and so on. More simple to say almost all kind of transportation that people need but sometimes they are not able to find you.</font></p>
        <div align="center">
            <p><div class="fb-like" data-href="https://www.facebook.com/ChristianTransfers" data-send="true" data-width="700" data-show-faces="false" data-action="recommend"></div></p>
        </div>
    </div>
</div>

{include file='../common/footer.phtml'}