{include file='../common/header.phtml'}
<div class="wrap">
    <div class="row">
        <div align="center">
            <p><div class="fb-like" data-href="https://www.facebook.com/Christian Transfers" data-send="true" data-width="700" data-show-faces="false" data-action="recommend">
            </div>
            </p>
        </div>

        <div align="center">
            <h1>Minibus hire - London, London Heathrow, London Gatwick, Crawley, Brighton, Southampton, Portsmouth, Bournemouth, Dartford, Dover</h1>
        </div>

        <div class="wrapper">
            <article class="cols400">
                <figure><img src="images/2012 Vito Negru Exterior 17.jpg" width="240" alt="minibus mercedes vito 2012 rent with driver" title="Minibus Mercedes Vito 2012" class="pad_bot2"></figure>
                <p class="pad_bot1"><strong>If you have an organized group, do not hesitate to rent a private minibus Mercedes Vito or Viano with driver.</strong></p>
                <p>You can communicate the programme for vehicles rental and we will do as soon as possible a complete offer according with your request. Rent conditions and exceptional value for money make this version a very good alternative.</p>
            </article>

            <article class="cols400 pad_left1">
                <p>Our company provides minivans for any type of event: Transfers to / from airport, city tours, travel in Romania, Bulgaria, Hungary, Serbia and all European Union, business trips, transportation for delegates, conferences, holidays at home and abroad, teambuilding for companies, private tours or special events.</p> 
                <p>We also offer through our local partners vans or mininvans rent in countries like Austria, Germany, Slovenia, Slovakia, Italy and Croatia.</p>
            </article>

            <article class="cols400 pad_left1">
                <figure></figure>
                <figure><img src="images/vito negru.jpg" width="240" alt="minibus mercedes vito 2008 rent with driver" title="Minibus Mercedes Vito 2008" class="pad_bot2"></figure>
                <p>All minibuses offered by us are rented only with our driver. Optional on request we can offer specialized travel guide for languages : Greek, English, French, Spanish, German.</p>
                <a href="contact.html" class="button1"><strong>Contact us</strong></a>
            </article>
        </div>

        <table class="responsive" width="100%" border="0" cellpadding="0" cellspacing="0">
            <tr>
                <td valign="top" align="right" colspan="8">
                    <p><a href="minibus.html"><font color="#000">Back to all Minibus list</font></a></p>
                </td>
            </tr>
        </table>

        <table class="responsive" width="100%" border="5" cellpadding="5" cellspacing="5">
            <tr>
                <th valign="top" align="Left" colspan="8">
                    <p><font color="#1616E9"></font></p>
                </th>
            </tr>
            <tr>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <img src="images/2012 Vito Negru Exterior 15.jpg" width="110" alt="minibus mercedes vito rental with driver london airport" title="Minivan Mercedes Vito rental in london" class="pad_bot2"> 
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Available in</b></br>London</br>London Heathrow</br>London Gatwick</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Minivan 1-6 places</b></br></br>Available for inquiries</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Minibus 1-8 places</b></br></br>Available for inquiries</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Click here</b></br></br><a href="contact.html" class="button1"><strong>Contact us</strong></a></font>
                </td>
            </tr>
            <tr>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <img src="images/crafter 2013 exterior.JPG" width="110" alt="minibus mercedes sprinter rental with driver liverpool" title="Minibus rental in Liverpool" class="pad_bot2"> 
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Available in</b></br>Southampton</br>Portsmouth</br>Bournemouth</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Minivan 1-6 places</b></br></br>Available for inquiries</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Minibus 1-8 places</b></br></br>Available for inquiries</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Click here</b></br></br><a href="contact.html" class="button1"><strong>Contact us</strong></a></font>
                </td>
            </tr>
            <tr>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <img src="images/2012 Vito Negru Exterior 15.jpg" width="110" alt="minibus mercedes vito rental with driver glasgow airport" title="Minivan Mercedes Vito rental in glasgow" class="pad_bot2"> 
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Available in</b></br>Brighton</br>Crawley</br>Dartford</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Minivan 1-6 places</b></br></br>Available for inquiries</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Minibus 1-8 places</b></br></br>Available for inquiries</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Click here</b></br></br><a href="contact.html" class="button1"><strong>Contact us</strong></a></font>
                </td>
            </tr>
        </table>

        <table class="responsive" width="100%" border="0" cellpadding="5" cellspacing="5">
            <tr>
                <td valign="top" align="center" colspan="8">
                    <img src="images/2012 Vito Negru Exterior 5.jpg" width="240" alt="minibus mercedes vito rental with driver in london stansted" title="Minivan Mercedes Vito rental in london" class="pad_bot2">
                    <img src="images/2012 Vito Negru Exterior 12.jpg" width="240" alt="minibus mercedes vito rental with driver in london luton" title="Minivan Mercedes Vito rental in london" class="pad_bot2">
                    </br>
                    <img src="images/2012 Vito Negru Exterior 15.jpg" width="240" alt="minibus mercedes vito rental with driver in london gatwick" title="Minivan Mercedes Vito rental in london" class="pad_bot2">
                    <img src="images/2012 Vito Negru Exterior 17.jpg" width="240" alt="minibus mercedes vito rental with driver in london heathrow" title="Minivan Mercedes Vito rental in london" class="pad_bot2">
                </td>
            </tr>
        </table> 

        <table class="responsive" width="100%" border="0" cellpadding="0" cellspacing="0">
            <tr>
                <td valign="top" align="center"><p>
                        <a href="minibusingermany.html"><font color="#000">Minibus in Germany</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusincroatia.html"><font color="#000">Minibus in Croatia</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusinromania.html"><font color="#000">Minibus in Romania</font></a></p>
                </td>
            </tr>
            <tr>
                <td valign="top" align="center"><p>
                        <a href="minibusinhungary.html"><font color="#000">Minibus in Hungary</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusinaustria.html"><font color="#000">Minibus in Austria</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusinslovakia.html"><font color="#000">Minibus in Slovakia</font></a></p>
                </td>
            </tr>
            <tr>
                <td valign="top" align="center"><p>
                        <a href="minibusinbulgaria.html"><font color="#000">Minibus in Bulgaria</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusinserbia.html"><font color="#000">Minibus in Serbia</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusinmontenegro.html"><font color="#000">Minibus in Montenegro</font></a></p>
                </td>
            </tr>
        </table> 

        <div align="center">
            <p><div class="fb-like" data-href="https://www.facebook.com/Christian Transfers" data-send="true" data-width="700" data-show-faces="false" data-action="recommend">
            </div>
            </p>
        </div>
    </div>
</div>

{include file='../common/footer.phtml'}