{include file='../common/header.phtml'}
<div class="wrap">
    <div class="row">
        <h2>Bucharest city tour - Transilvania tour - Bucovina Heritage tour</h2>
        <div class="wrapper">
            <article class="cols400">
                <figure><img src="images/palatul-parlamentului.jpg" width="240" alt="bucharest city tour parliament palace house of the people casa popurului" title="Parliament Palace also known as House of the people - Casa Popoului" class="pad_bot2"></figure>
                <p class="pad_bot1"><strong>Bucharest City Tour 4 hours.</strong></p>
                <p><strong>Leaving in the morning from Bucharest hotels or guesthouses with route:</strong></br> - Bucharest Hotel</br> - House of the People</br> - The Village Museum</br> - Triumphal Arch</br> - Romanian Peasant Museum</br> -  Romanian Athenaeum</br> -  Patriarchal Church</br> - Bucharest Hotel.</p>
                <p><strong>Prices:</strong></br>Tour 4 hours cost 49 euro for a car for 1-4 persons, 89 for a car of 1-8 persons and 129 euro for a car of 1-16 persons.</p>
                <p>Not incluided in price is the entrance to objectives, parkings and guide. We can provide guide for english, greek, german & french language starting with 75 euro/day.</p>
                <p><strong>One day tour arround Bucharest. </strong></br>Mogosoaia Palace, Manasteries like: Cernica, Pasarea, Tiganesti, Caldarusani and Snagov...</p>
                <a href="contact.html" class="button1"><strong>Contact Us</strong></a>
            </article>
            <article class="cols400 pad_left1">
                <figure><img src="images/bran2.jpg" width="240" alt="transilvania tour bran peles dracula castle" title="Bran Castle also known as Dracula Castle" class="pad_bot2"></figure>
                <p class="pad_bot1"><strong>Transilvania Tour 10 hours.</strong></p>
                <p><strong>Leaving in the morning from Bucharest hotels or guesthouses with route:</strong></br> - Bucharest</br> - Sinaia Monastery</br> - Peles Castle</br> - Pelisor Castle</br> - Bran Castle ( alias Dracula )</br> - Brasov</br> - Bucharest.</p>
                <p><strong>Prices:</strong></br>One full day to visit 4  Castles & Monasteries cost 179 euro for a car for 1-4 persons, 229 for a car of 1-8 persons and 299 euro for a car of 1-16 persons.</p>
                <p>Not incluided in price is the entrance to castles & monasteries, meal for noon, parkings and guide. We can provide guide for english, greek, german & french language starting with 89 euro/day.</p>
                <a href="contact.html" class="button1"><strong>Contact Us</strong></a>
            </article>
            <article class="cols400 pad_left1">
                <figure><img src="images/voronet.jpg" width="240" alt="bucovina tours suceava humor voronet moldovita sucevita" title="Voronet Monastery" class="pad_bot2"></figure>
                <p class="pad_bot1"><strong>Bucovina Monasteries tours 8 hours.</strong></p>
                <p><strong>Leaving in the morning from Suceava hotels or guesthouses with route:</strong></br> - Suceava</br> - Humor Monastery</br> - Voronet Monastery</br> - Moldovita Monastery</br> - Sucevita Monastery</br> - Suceava.</p>
                <p><strong>Prices:</strong></br>One full day to visit 4  Monasteries cost 119 euro for a car for 1-4 persons and 189 for a car of 1-8 persons.</p>
                <p>Not incluided in price is the entrance to monasteries, meal for noon and guide. We can provide guide for english language starting with 25 euro/day.</p>
                <a href="contact.html" class="button1"><strong>Contact Us</strong></a>
            </article>

        </div>
        <div align="center">
            <p><div class="fb-like" data-href="https://www.facebook.com/ChristianTransfers" data-send="true" data-width="700" data-show-faces="false" data-action="recommend"></div></p>
        </div>
    </div>
</div>

{include file='../common/footer.phtml'}