{include file='../common/header.phtml'}
<!-- Page info -->
<header class="site-title color">
        <div class="wrap">
                <div class="container">
                        <h1>Bookings System Help - Christian Transfers</h1>
                        <nav role="navigation" class="breadcrumbs">
                                <ul>
                                        <li><a href="/" title="Home">Home</a></li>
                                        <li>Bookings System Help</li>
                                </ul>
                        </nav>
                </div>
        </div>
</header>
<!-- //Page info -->


<div class="wrap">
        <div class="row">			
                <!--- Content -->
                <div class="full-width content">
                        <!-- Post -->
                        <article class="single hentry">
                                <div class="entry-content">
                                        <h2><b>HOW THE SYSTEM WORK FOR THE RESERVATIONS.</b></h2>

                                        <h3><b>Online reservation</b></h3>
                                        <p>Any customer can make reservations and payments online on our website 24/7/365 (we recommend the bookings to be made with 48 hours before the transfer to have place, Sunday and Saturday excluded from this calculation).</p>
                                        <h3><b>Procesing your reservations.</b></h3>
                                        <p>We proces your reservation during our working hours 09:00-18:00 (GMT +2). We send all the bookings with payments to our local subcontractors/carriers.</p>
                                        <h3><b>Confirmation.</b></h3>
                                        <p>Local subcontractors/carriers send confirmations or infirmations during their working hours usually <b>Monday - Friday</b> 0900-1800,<b> Saturday</b> 10.00-1300, <b>Sunday</b> closed.</p>
                                        <p>According with local subcontractors/carriers confirmations we will send you confirmation or infirmation <b>BY EMAIL</b> for your booking <b>(PLEASE CHECK YOUR SPAM/JUNK FOLDER TOO).</b></p>


                                        <h2><b>USING THE LEFT WEBSITE MENU FOR THE RESERVATIONS.</b></h2>

                                        <h3><b>Page 1 - Choose your country.</b></h3>
                                        <p>See in the left side of the website to the menu the first buton indicate you <b> "Starting Country".</b> Click on it and choose the starting country for your transportation. We reffer here to the transportation with our company.</p>
                                        <h3><b>Choose your starting point.</b></h3>
                                        <p>Next choose your starting city or airport from the list, <b>"Pick up from Airport or City"</b> is the button.</p>
                                        <h3><b>Choose your destination.</b></h3>
                                        <p>Next choose your arrival city or airport from the list <b> "Your Destination".</b> If your desire connection is not listed please use the contact page form to contact us and we will try to offer your destination too, as fast as we can.</p>
                                        <h3><b>Choose one way or return transfer.</b></h3>
                                        <p>Choose next if you need one way transfer or return <b> "Only One or Return Transfer".</b></p>
                                        <h3><b>Choose your date & hours.</b></h3>
                                        <p>You can choose the date with the menu buttons or click on the calendar. Next select the desire hour for transportation. </b>If you will choose shuttle bus transfer do not choose the hour as you will have to be present at the bus schedulle</b>.</p>
                                        <h3><b>Select the passengers number.</b></h3>
                                        <p>Select the number of the passenger who will travel.</p>
                                        <h3><b>Page 2 -Check your booking from first step.</b></h3>
                                        <p>After you made all thoose selection the available cars for this route will appear on the right part of the website. Choose the car with a click on the right button. If you choose shuttle bus transfer please choose form the options if there are more than one shuttle options. If you have return transfer click for both trips on your desire car. Then click the button under the cars <b> "Submit your car and go to next step from you Booking".</b></p>
                                        <h3><b>Complete personal details - Name & Company.</b></h3>
                                        <p>Complete the name of the passenger/s, (example : John Briandth; Raluca Ionescu; Ivonse Larissa; if they are 3 passengers).In case you are travel in business purposse put the company name in next space, if you are travel on your own just put a minus (-).</p>
                                        <h3><b>Complete Phone & Email.</b></h3>
                                        <p>Phone - Please put the mobile phone number <b>(INCLUDING COUNTRY CODE)</b> you will have at the time of your travel to can be called in case of not meeting the driver;</p>
                                        <p>Email - Do Not use <b> AOL.com emails.</b> Please use a valid email adress where you will receive the confirmation for booking and payment.<b> PLEASE CHECK YOUR SPAM/JUNK FOLDER </b> too for confirmation.</p>
                                        </div>

                        </article>
                        <!-- //Post -->
                </div>
                <!--- //Content -->
        </div>
</div>
{include file='../common/footer.phtml'}