{include file='../common/header.phtml'}
<main class="main" role="main">
		<!-- Page info -->
		<header class="site-title color">
			<div class="wrap">
				<div class="container">
					<h1>About Christian Transfers - All about Transportation</h1>
					<nav role="navigation" class="breadcrumbs">
						<ul>
							<li><a href="index.html" title="Home">Home</a></li>
							<li>About Christian Transfers</li>
						</ul>
					</nav>
				</div>
			</div>
		</header>
		<!-- //Page info -->
		
		<div class="wrap">
			<div class="row">
				<!--- Content -->
				<div class="content three-fourth textongrey">
					
					<h3><strong>Christian Transfers in ground transportation.</strong></h3>
					<p>Christian Transfers is the online agency that starting from 2000 has as main activity the reservation of transport services: passenger transport, airport transfers, minivan, minibuses and coaches rentals, daily shuttles, internal and external circuits, goods transport or delivery.</p>
                    <p>Safe and Reliable - If it is for a Airport Transfers or excursions to the countryside, if you order our service just for a short trip or if you book us for all day long, you can always count on our competent, reliable and discrete service to insure your mobility in and around cities.</p>
					<p>No hidden fees - with years of experience in travel and people transfers, we understand to offer a fair and transparent price for your transport solution. Either you choose from an airport transfer or coach rental price have to be clearly explained and agreed.</p>
					 
					<h3><strong>Airport transfers</strong></h3>
					<p>We aim to offer transportation options at your choice with just a few clicks thats why we are covering today more 10.000 private routes in Europe.</p> 
					<p>Our company can provide cars for any type of event: transfers to and from the airport or trips from cities to cities, business trips, transport for delegates, conferences, teambuilding for companies, events or tourist circuits, holidays & excursions.</p>
					<p>The quality, safety and promptness of the services offered are based on qualified, experienced staff, thousands of processed orders and the millions of kilometers traveled.</p>
					
					<h3><strong>Minibus and coach rentals</strong></h3>
					<p>You can communicate the budget for vehicles rental and we will do as soon as possible a complete offer according with your request. Rent conditions and exceptional value for money make this version a very good alternative.</p>
					
					<h3><strong>App for taxi, couriers and recovery cars</strong></h3>
					<p>Being a unique combination of start-up in technology, online service and classic shipping, we are trying to offer a wide range of fast and professional solutions, making it much easier with our new online platform.</p>
					<p>We have included the most common services that people need today: taxis, airport and city cars and minivans, bicycle courier, van courier, relocation luton vans, long run trucks and recovery cars.</p>
				</div>
				<!--- //Content -->
				
				<!--- Sidebar -->
				<aside class="one-fourth sidebar right offset">
					
				{include file='../common/sidebar2.phtml'}
					
				</aside>
				<!--- //Sidebar -->
			</div>
		</div>
	</main>
	<!-- //Main -->
	
{include file='../common/sidebar3.phtml'}

{include file='../common/footer.phtml'}