{include file='../common/header.phtml'}
<!-- Page info -->
<header class="site-title color">
        <div class="wrap">
                <div class="container">
                        <h1>Frequently asked questions - Help - Christian Transfers</h1>
                        <nav role="navigation" class="breadcrumbs">
                                <ul>
                                   <li><a href="/" title="Home">Home</a></li>
                                   <li>Faq - Help</li>
                                </ul>
                        </nav>
                </div>
        </div>
</header>
<!-- //Page info -->

<div class="wrap">
        <div class="row">
                <!--- Sidebar -->
                <aside class="one-fourth sidebar right offset">
                        <!-- Widget -->
                        <div class="widget">
                                <ul class="categories">
                                   <li class="active"><a href="#faqs1" class="anchor">Before you book</a></li>
                                   <li><a href="#faqs2" class="anchor">Before you travel</a></li>
								   <li><a href="#faqs3" class="anchor">After you travel</a></li>
                                   <li><a href="#faqs4" class="anchor">Payment information</a></li>
                                </ul>
                        </div>
                        <!-- //Widget -->
                </aside>
                <!--- //Sidebar -->
				
                <!--- Content -->
                <div class="three-fourth content">
                        
						<h3 id="faqs1">Before you book</h3>
                        <dl class="faqs">
                                <!-- Item -->
                                <dt>How do I contact the Christian Transfers office?</dt>
                                <dd>
								<p>If you need to use the booking form to complete a booking please <a href="/#booking"><b>click this link</b></a>.</p>
								<p>If we dont have your transfer on the booking menu yet or if you need to make an enquiry for a tour with a special coach or minibus rental programme please use the website tailor made menu by <a href="/tailor-made"><b>clicking here</b></a></p>
                                <p>If you need to contact us with other enquiries or to join our team please use the contact form by <a href="/contact"><b>clicking here</b></a></p>
                                </dd>
                                <!-- //Item -->
								
								<!-- //Item -->
                                <dt>What vehicle we have to choose?</dt>
                                <dd>
								<p>All vehicles have certain technical specifications, please be sure you choose the correct vehicle for your party and all your luggages.</p>
                                <p>Taxi 3 = fits 3 passengers along with 2 hand luggage (max 10 kg) and 2 big luggage (max 25 kg).</p>
								<p>Saloon = fits 3 passengers along with 2 hand luggage (max 10 kg) and 2 big luggage (max 25 kg).</p>
								<p>Executive car = fits 3 passengers along with 2 hand luggage (max 10 kg) and 3 big luggage (max 25 kg).</p>
								<p>VIP car = fits 3 passengers along with 2 hand luggage (max 10 kg) and 3 big luggage (max 25 kg).</p>
								<p>Estate car = fits 4 passengers along with 2 hand luggage (max 10 kg) and 3 big luggage (max 25 kg).</p>
								<p>MPV cars = fits 4-6 passengers along with 2-3 hand luggage (max 10 kg) and 3-4 big luggage (max 25 kg).</p>
								<p>Minivan 7 = fits 7 passengers along with 4-5 hand luggage (max 10 kg) and 6-7 big luggage (max 25 kg).</p>
								<p>Minivan 8 = fits 8 passengers along with 4-5 hand luggage (max 10 kg) and 6-8 big luggage (max 25 kg).</p>
								<p>Minibus = fits passengers and for every one come with 1 hand luggage (max 10 kg) and 1 big luggage (max 25 kg).</p>
								<p>Coach = fits passengers and for every one come with 1 hand luggage (max 10 kg) and 1 big luggage (max 25 kg).</p>
                                </dd>
                                <!-- //Item -->
								
                                <!-- //Item -->
                                <dt>Do you offer booster seats or child seats for children or babies?</dt>
                                <dd>
                                <p>We can offer booster seats or child seats on request, please let us know at the time of booking confirmation. Please note that depending on the country of your transfer booster seats or child seats may require a small extra payment.</p>
								<p>Depending on the situation you can choose to use your own booster seats or child seats.</p>
                                </dd>
                                <!-- //Item -->	
                                
								<!-- //Item -->
                                <dt>Are pets or guide dogs allowed in the vehicle?</dt>
                                <dd>
                                <p>Guide dogs are welcome in our cars for all accredited assistance dog users. At the time of your booking please let us know about this situation.</p>
								<p>Other categories of pets are not accepted in our cars.</p>
                                </dd>
                                <!-- //Item -->
								
								<!-- Item -->
                                <dt>How do I make my reservation/booking?</dt>
                                <dd>
                                <p>Reservation must be made online using the menu of the website <a href="/#booking"><b>by clicking this link</b></a>. Website can be accesed by a pc, a tablet or any mobile device. Bookings on any other communication channels like phone calls, what's up, facebook, twitter cannot be accepted at this time.</p>
                                <!-- //Item -->	
                                
								<!-- Item -->
                                <dt>How do I know if I have a reservation?</dt>
                                <dd>
                                <p>At the time of your booking on the website you will receive an automated email with your booking (<b>please see in the spam/junk folder also</b>). Please make a short reply to that email with your confirmation that dates and hours are corect. In next hours we will send confirmation by email that we can operate the requested service.</p>
                                </dd>
                                <!-- //Item -->
                                
								<!-- Item -->
                                <dt>How do I pay for my booking and how do I know if my payment was accepted?</dt>
                                <dd>
                                <p>The payments for all the bookings are made online by card at the thrid step of the booking. An automated email will come to your email confirming your payment. Please go in the email used in the booking and see the email. You dont have to send us the payment email, we receive it also.</p>
								<p>The payments for tailor made bookings will be made by card with a payment link sent direct to your email or by bank transfer.</p>
								<p>The payments in cash to the driver are not welcome.</p>
                                </dd>
								<!-- Item -->
								
								<!-- Item -->
                                <dt>Can I have a REFUND if I cancel my booking for a transfer or a coach/minibus rental?</dt>
                                <dd>
                                <p>If you cancel your transfer or rental with more than 48 hours before the travel time, you'll receive a REFUND of 100% from your card payment. The refund can be made ONLY to the original payment sources.</p>
								<p>If you cancel your transfer or rental less than 48 hours before the travel time NO REFUND can be made.</p>
								<p>Payments made by Bank transfers are NOT refundable.</p>
                                </dd>
                                <!-- //Item -->
                        </dl>
                        
						<h3 id="faqs2">Before you travel</h3>
                        <dl class="faqs">
                                <!-- Item -->
                                <dt>How do I find my driver?</dt>
                                <dd>
                                <p>For the private transfers our driver will be waiting inside of the arrival terminal with a banner with your name or your group leader name. In case of the shuttle bus transfers driver will have the shuttle bus company name on the baner at the meeting point. Details of the meeting point are sent in the confirmation email.</p>
                                </dd>
								<!-- Item -->
								
								<!-- Item -->
                                <dt>What happens if I cannot find my driver?</dt>
                                <dd>
                                <p>If your plane was coming earlier please be patience until the agreed time. Having ensured that you have correctly followed the instructions on your transport reservation, call our agent on the contact number after 10 minutes if you cant see the banner. Usually we instruct all the customers to go near the Information office to the arrival terminals.</p>
                                </dd>
                                <!-- //Item -->
								
                                <!-- Item -->
                                <dt>I have lost my luggage in the plane or airport. Will you collect it for me later ?</dt>
                                <dd>
                                <p>All the airlines have handling agents and they might organize for your luggage to be forwarded to your resort address. We might organize this delivery by our couriers service only with prior arrangements.</p>
                                </dd>
                                <!-- //Item -->
								
                                <!-- Item -->
                                <dt>I have left something in the vehicle. How do I get it back ?</dt>
                                <dd>
                                <p>Please contact our agent on the number provided. We will then endeavour to have the items returned to you. A charge may be applicable for the transportation and NOT as penalty.</p>
                                </dd>
                                <!-- //Item -->
								
								<!-- Item -->
                                <dt>Is the transfer direct or do we stop en route ? Can we stop off at the supermarket or to pick up property keys en route ?</dt>
                                <dd>
								<p>Private transfers are normally direct and door-to-door.</p>
                                <p>Only by prior arrangement with our agent and only if you are travelling by Private Transfer. Subject to availability, additional payments or supplements may apply.</p>
                                </dd>
                                <!-- //Item -->
								
								<!-- Item -->
                                <dt>Does the driver speak English ?</dt>
                                <dd>
                                <p>In most cases our drivers speak English, although scheduling requirements may mean that occasionally a non-English speaking driver may carry out a transfer.</p>
                                </dd>
                                <!-- //Item -->	
                        </dl>
                        
						<h3 id="faqs3">After you travel</h3>
                        <dl class="faqs">
                                <!-- Item -->
                                <dt>Can I have a TAX RECEIPT for my payment ?</dt>
                                <dd>
                                <p>Yes for sure. When you payed online by credit/debit card an email came direct to your email adress, this is the receipt for the payment and you can easy print it for your accounting.</p>
                                </dd>
                                <!-- //Item -->
								
								<!-- Item -->
                                <dt>Can I have an INVOICE for the service ?</dt>
                                <dd>
                                <p>Yes for sure. Either you was paying online by credit/debit card or by bank transfer you'll receive the invoice for the service in 5-10 days after the payment. Please be sure you sent the company details we have to include in the document. Details have to be sent in an email as reply to your booking.</p>
                                </dd>
                                <!-- //Item -->	
                        </dl>
                        
						<h3 id="faqs4">Payment information</h3>
                        <dl class="faqs">
						        
								<!-- Item -->
                                <dt>How do I make the payment on the website for my car?</dt>
                                <dd>
								<p>For all the bookings made on the website payments are made by debit/credit card at last step of the booking. For minibus or coach hire payments can be made by debit/credit card or by bank transfer.</p>
                                <p>In the app the taxis are payed by cash to the driver and couriers or recovery cars are payed by card in the app.</p>
                                </dd>
                                <!-- //Item -->
								
                                <!-- Item -->
                                <dt>How payments works in Christian Transfers Apps?</dt>
                                <dd>
                                <p>You might already have an account with us, made on Christian Transfers website or by downloading one of our apps. If you don't have already one you can make it very easy.</p>
                                <p>After you download the app for iOS or Android you'll can edit your profile including by adding the card details inside of the menu. The infos will be stored safely on Stripe servers.</p>
								<p>Stripe is the card procesing company for this type of Apps operations. The card details <b>CANNOT</b> be accesed by any of our company staff member, or by any other third parties in any way.</p>
								<p>Every time you'll use the app for transport purpose (using products that require your payment by card) the software app will charge at the end of the trip your card according with time and distance spent for that trip.</p>
								</dd>
                                <!-- //Item -->
								
								
                        </dl>
                </div>
                <!--- //Content -->
        </div>
</div>
{include file='../common/footer.phtml'}