{include file='../common/header.phtml'}
<!-- Page info -->
<header class="site-title color">
        <div class="wrap">
                <div class="container">
                        <h1>How it works - Christian Transfers</h1>
                        <nav role="navigation" class="breadcrumbs">
                                <ul>
                                   <li><a href="/" title="Home">Home</a></li>
                                   <li>How it works</li>
                                </ul>
                        </nav>
                </div>
        </div>
</header>
<!-- //Page info -->

<div class="wrap">
        <div class="row"> 
                <!--- Sidebar -->
                <aside class="one-fourth sidebar right offset">
                        <!-- Widget -->
                        <div class="widget">
                                <ul class="categories">
                                   <li class="active"><a href="#faqs1" class="anchor">How it works?</a></li>
                                   <li><a href="#faqs2" class="anchor">How SHARED BOOKINGS works?</a></li>
								   <li><a href="#faqs3" class="anchor">How TAXI APP work?</a></li>
								   <li><a href="#faqs4" class="anchor">How TOWING & RECOVERY CAR works?</a></li>
								   <li><a href="#faqs5" class="anchor">How MINIBUS & COACH works?</a></li>
                                   <li><a href="#faqs6" class="anchor">How EXECUTIVE & VIP TRANSFERS works?</a></li>
                                </ul>
                        </div>
                        <!-- //Widget -->
                </aside>
                <!--- //Sidebar -->
				
				<!--- Content -->
                <div class="three-fourth content">
                        
						<h3 id="faqs1">How it works ?</h3>
                        <dl class="faqs">
                                <!-- Item -->
                                <dt>What is Christian Transfers?</dt>
                                <dd>
								<h4><strong>What is Christian Transfers and what can I book with Christian Transfers?</strong></h4>
								<p><strong>Christian Transfers is a transport agency</strong> and with Christian Transfers you can book ground transportation on our websites and in our apps.</p>
                                <p>You can book ground transportation like <strong>airport transfers, local taxis, urgent couriers, recovery cars for roadside assistance, minibuses and coaches with our driver, shared shuttles buses</strong>.</p>
                                </dd>
                                <!-- //Item --> 
								
								<!-- Item -->
                                <dt>How it works?</dt>
                                <dd>
								<p>Please use the <strong>website menu to make your booking</strong>.</p>
                                <p>In case we don't have your desire transfer ready please use the <strong>contact or tailor made page</strong> to contact us with your transportion inquiry.</p>
								<p>Taxis, couriers and recovery cars can be booked in the Apps.</p>
                                </dd>
                                <!-- //Item --> 
								
								<!-- Item -->
                                <dt>How do I contact the Christian Transfers?</dt>
                                <dd>
								<p>If you want to <strong>make a booking please use the website menu</strong>. If we dont have your transfer on the booking menu or if you need to make an enquiry for a tour with a special coach or minibus rental programme please use the website tailor made menu by <a href="/tailor-made"><b>clicking here</b></a></p>
                                <p>If you need to contact us with other enquiries or to join our team please use the contact form by <a href="/contact"><b>clicking here</b></a></p>
                                </dd>
                                <!-- //Item --> 
								
                                <!-- Item -->
                                <dt>What services might be booked on Christian Transfers Contact & Tailor Made pages?</dt>
                                <dd>
                                <p>On our Contact & Tailor Made pages we usually book al services which require a longer process of booking and a longer amount of data to be shared.</p>
								<p>Executive cars, vip cars, minibuses, coaches or buses might be prebooked by contact us on Contact & Tailor Made pages if there are not already available in the menu.</p>
                                </dd>
								<!-- Item -->
								
								<!-- Item -->
                                <dt>What services are available in Christian Transfers website menu?</dt>
                                <dd>
                                <p>On the Christian Transfers website menu you can make easy bookings, who require just few minutes, you already have all the informations you might need, like date and time of travel, addresses and locations of pickup and drop off.</p>
								<p>On the Christian Transfers website menu you might book, short <strong>airport transfers</strong>, long <strong>transfers from one city to another city</strong>, long <strong>transfers from one country to another country</strong>, <strong>shared transfers</strong> with certain hours and locations of pickup and drop off.</p>
                                </dd>
								<!-- Item -->
								
								<!-- Item -->
                                <dt>How do I make a booking using the Website booking menu?</dt>
                                <dd>
								<p>To complete your booking please use the form by <a href="/#booking"><b>clicking this link</b></a>.</p>
								
								<h3><b>Page 1</b></h3>
								
								<h3><b>Choose RETURN or ONE WAY transfer.</b></h3>
                                <p>Choose next if you need one way transfer or return <b> "RETURN or ONE WAY transfer".</b></p>
								
								<h3><b>Choose the date & hours of your trip.</b></h3>
                                <p>Please choose the date, hours & minutes for both transfers  by clicking in the boxes of DEPARTURE DATE & RETURN DATE. </b>If you will choose shuttle bus transfers, please do not choose the hours of travel as you will have to adapt yourself at the bus schedulle</b>. You can choose your desire time of travel only for private transfers.</p>
								
								<h3><b>Choose the PICKUP POINT (your starting point).</b></h3>
                                <p>Next choose your starting city or airport from the list, by clicking in the boxes of <b>"PICK UP LOCATION"</b>.</p>
                                
								<h3><b>Choose DROP OFF LOCATION (your destination).</b></h3>
                                <p>Next choose your arrival city or airport from the list by clicking in the boxes of <b>"DROP OFF LOCATION".</b> If your desire connection is not listed please use the contact page form to contact us and we will try to offer your destination too, as fast as we can.</p>
                                
								<h3><b>Select the passengers number.</b></h3>
                                <p>Select the number of the passenger who will travel by clicking in the boxes of <b>"HOW MANY PEOPLE?"</b>.</p>
								
								<h3><b>Select the car.</b></h3>
                                <p>Select the desire car by clicking in the radio button near the car. For shuttle transfers please choose one desire transfer from the list.</p>
								
								<h3><b>Click submit button.</b></h3>
                                <p>Click submit button to go to the next step of the booking.</p>
                                
								<h3><b>Page 2</b></h3>
								
								<h3><b>Check your booking from first step.</b></h3>
                                <p>After you made all selection at <b>"PAGE 1"</b> they'll appear on the right part of the website in "BOOKING SUMMARY" window.</b></p>
                                
								<h3><b>Complete PASSENGER DETAILS - Name, Company, Phone & Email.</b></h3>
                                <p><b>Name & Company</b>. Complete the name of the passenger/s, (example : John Briandth; Raluca Ionescu; Ivonse Larissa; if they are 3 passengers).In case you are travel in business purposse put the company name in next space, if you are travel on your own just put a minus (-);</p>
                                <p><b>Phone</b> - Please put the mobile phone number <b>(INCLUDING COUNTRY CODE)</b> you will have at the time of your travel to can be called in case of not meeting the driver;</p>
                                <p><b>Email</b> - Do Not use more than one email in the booking. Please use a valid email adress where you will receive the confirmation for booking and payment.<b> PLEASE CHECK YOUR SPAM/JUNK FOLDER </b> too for our confirmation.</p>
                                
								<h3><b>Complete DETAILS FOR YOUR DEPARTURE/RETURN transfer.</b></h3>
                                <p><b>Pick-up adress</b>. Please complete the pick-up adress;</p>
                                <p><b>FLIGHT NUMBER</b> - In case of a pickup from the airport please provide flight number;</p>
                                <p><b>Adress of your destination</b>. Please complete the dropp-off adress.</p>
								<p><b>Baggage type</b>. Please complete baggage details.</p>
								
								<h3><b>Page 3</b></h3>
								
								<h3><b>Check the details.</b></h3>
                                <p>This page will display the details of your booking. You can check all the details before completing the payment.</p>
								
								<h3><b>Page 4</b></h3>
								
								<h3><b>Payment by CARD.</b></h3>
                                <p>Click the button to complete the payment. You'll be redirected to our card processor company website. You'll complete the payment on a complete secure page.</p>
								
								<h3><b>Last step from your booking.</b></h3>
                                <p>After completing the payment please check the email box for booking email and payment confirmation. Transfer confirmation will come later, being processed manually by our team. Don't forget to confirm the booking by replying to the email.</p>
								
								</dd>
                                <!-- //Item -->
								
                                <!-- Item -->
                                <dt>Online booking, processing & confirming your booking</dt>
                                <dd>
								<h3><b>Online booking</b></h3>
								<p>Any customer can make reservations and payments online on our website 24/7/365 (we recommend all the bookings to be made with 48 hours or more before the transfer time).</p>
                                
								<h3><b>Procesing your booking</b></h3>
                                <p>We proces all reservations during our working hours, daily 09:00-18:00 (GMT +2). We'll process and send all the bookings with valid payments to our local subcontractors/carriers.</p>
                                
								<h3><b>Confirmation of the booking</b></h3>
                                <p>Local subcontractors/carriers send confirmations or infirmations during their working hours usually <b>Monday - Friday</b> 0900-1800,<b> Saturday</b> 10.00-1300, <b>Sunday</b> closed.</p>
                                <p>We will send you confirmation or infirmation <b>BY EMAIL</b> for your booking <b>(PLEASE CHECK YOUR SPAM/JUNK FOLDER TOO).</b></p>
                                </dd>
                                <!-- //Item -->
                        </dl>
                        
						<h3 id="faqs2">How SHARED BOOKINGS works?</h3>
                        <dl class="faqs">
 								<!-- Item -->
                                <dt>How SHARED SHUTTLE bookings works in Christian Transfers website?</dt>
                                <dd>
                                <p>In Christian Transfers website menu client can book shared transporation on some certain routes where this service is available.</p>
                                <p>The price displayed in the website for <strong>SHARED SHUTTLE</strong> is per person.</p>
								<p></p>
								</dd>
                                <!-- //Item -->
								
                        </dl>
						
						<h3 id="faqs3">How TAXI APP BOOKINGS works?</h3>
                        <dl class="faqs">
                           		<!-- Item -->
                                <dt>How Taxi bookings works in Christian Transfers App?</dt>
                                <dd>
                                <p>In Christian Transfers app client can book Taxi and pay by cash direct in the car to the driver.</p>
                                <p>The app will show an approximate price according with initial pick-up point and your destination filled in the app. <strong>Price shown by the taxi meter will stay and will have be paid at the end of the trip</strong>, according with the laws in most of the European countries.</p>
								<p>The price will reflect the exact performed route and time spent in the car, not just an approximate one.</p>
								</dd>
                                <!-- //Item -->
								
								<!-- Item -->
                                <dt>What services are available in Christian Transfers Apps?</dt>
                                <dd>
                                <p>In Christian Transfers app client can book <strong>taxis, airport cars, couriers</strong> & <strong>recovery car</strong>. Thoose options might be different from one location to another.</p>
                                </dd>
                                <!-- //Item -->
                        </dl>
						
						<h3 id="faqs4">How TOWING & RECOVERY CAR works?</h3>
                        <dl class="faqs">
                                <!-- Item -->
                                <dt>How do I book a long trip for my car with a Tow-Truck on Christian Transfers?</dt>
                                <dd>
                                <p>In Christian Transfers contact page the clients make the inquiries for the car transportation by a Tow-Truck. We'll confirm the trip details like pick up location, drop off location and the price..</p>
                                <p>This service is designed for long trips pre-booked for your car or for your motorbyke. This method of pre-booking is used when you need to move the car to another county, another country or you export or import that car.</p>
								<p>Payment will be charged from your card at the time of the booking or for trips booked direct in the app at the end of the trip the software app will charge your card according with time and distance spent for the trip.</p>
								</dd>
                                <!-- //Item -->
								
								<!-- Item -->
                                <dt>How Recovery-Car bookings works in Christian Transfers App?</dt>
                                <dd>
                                <p>In Christian Transfers app client can book a Recovery-Car or Towing-Truck and pay by card in the app.</p>
                                <p>The app will show an approximate price according with initial pick-up point and the destination filed in the app.</p>
								<p>At the end of the trip the software app will charge your card according with time and distance spent for the trip.</p>
								</dd>
                                <!-- //Item -->
                        </dl>
                        
						<h3 id="faqs5">How MINIBUS & COACH TRANSFERS works?</h3>
                        <dl class="faqs">
						        <!-- Item -->
                                <dt>I want to rent a bus, coach or a minibus with your driver, how this work ?</dt>
                                <dd>
                                <p>First step is to have ready all the details (full programme with dates and hours) for your bus or minibus rental.</p>
								<p>Second step is to complete the form from our tailor-made page by <a href="/tailor-made"><b>clicking here</b></a>.</p>
								<p>We'll get back with dispo and commercial offer, in case the offer suites your need the invoice will be issued and sent to your email for payment.</p>
								<p>Payment in cash are not welcome, payment have to be made either online by card or by bank transfer. Only for big amounts payment can be considered to be made in 2 stages. After we receive the payment in full, the booking is made.</p>
                                </dd>
                                <!-- //Item -->
								
                                <!-- Item -->
                                <dt>How do I book a Minibus transfer or daily hire on Christian Transfers website?</dt>
                                <dd>
								<p>Minibuses are designed to carry 16 passengers, 19 passengers or 21 passengers.</p>
								<p>Minibuses can be hired for <strong>airport transfers, city to city transfers, hire by day</strong>. Minibuses can be hired exclusively with our drivers.</p>
								<p><strong>Minibus Transfers</strong>. To book an <strong>airport transfer or a city to city transfer</strong> please use the website menu like for any other transfer booking. In case that minibuses are not listed for your desire locations <a href="/tailor-made"><b>please contact us by clicking here</b></a>.</p>
                                <p><strong>Minibus daily hire</strong>. When you'll need to book the <strong>daily hire service</strong> you'll need to provide full details of your trip; like dates of the trip, locations of pickup, locations of drop off, times and everyday schedule of the car. To book hire by day <a href="/tailor-made"><b>please contact us by clicking here</b></a>.</p>
								</dd>
								<!-- Item -->
								
								<!-- Item -->
                                <dt>How do I book a Coach transfer or daily hire on Christian Transfers website?</dt>
                                <dd>
								<p>Coaches are designed to carry 25 passengers, 30 passengers, 35 passengers or 50 passengers.</p>
								<p>Coaches can be hired for <strong>airport transfers, city to city transfers, hire by day</strong>. Coaches can be hired exclusively with our drivers.</p>
								<p><strong>Coach Transfers</strong>. To book an <strong>airport transfer or a city to city transfer</strong> please use the website menu like for any other transfer booking. In case that coaches are not listed for your desire locations <a href="/tailor-made"><b>please contact us by clicking here</b></a>.</p>
                                <p><strong>Coach Daily Hire</strong>. When you'll need to book the <strong>daily hire service</strong> you'll need to provide full details of your trip; like dates of the trip, locations of pickup, locations of drop off, times and everyday schedule of the car. To book hire by day <a href="/tailor-made"><b>please contact us by clicking here</b></a>.</p>
								</dd>
								<!-- Item -->
								
								
                        </dl>
						
						<h3 id="faqs6">How EXECUTIVE & VIP TRANSFERS works?</h3>
                        <dl class="faqs">
						        <!-- Item -->
                                <dt>How do I book an Executive or VIP car transfer or daily rental on Christian Transfers website?</dt>
                                <dd>
                                <p>On the Christian Transfers website you can book airport transfers and long transfers with Executive or VIP car in the locations where the service is available.</p>
								<p>Services on day (or half a day) rental have to by booked by Christian Transfers contact page by <a href="/tailor-made"><b>clicking here</b></a></p>
                                </dd>
								<!-- Item -->
								
                        </dl>
                </div>
                <!--- //Content -->	
        </div>
</div>
{include file='../common/footer.phtml'}