{include file='../common/header.phtml'}
<!-- Page info -->
<header class="site-title color">
        <div class="wrap">
                <div class="container">
                        <h1>Christian Transfers - We received your booking and it's payment</h1>
                        <nav role="navigation" class="breadcrumbs">
                           <ul>
                             <li><a href="/" title="Home">Home</a></li>
                             <li>Thank you</li>
                           </ul>
                        </nav>
                </div>
        </div>
</header>
<!-- //Page info -->


<div class="wrap">
        <div class="row">			
                <!--- Content -->
                <div class="full-width content">
                        <!-- Post -->
                        <article class="single hentry">
						   <div class="entry-content" align="middle">
						      <h3><b>Thank you for your payment</b></h3>
                              <a href="/" title="Christian Transfers - Airport Transfers"><img src="/images/logo1.png" alt="Christian Transfers logo" /></a>
						   </div>
                           <div class="entry-content">
						   
							  <p><b>We received the payment for your booking and one of our agents will process this booking as soon as possible.</b></p>
							  <p>The email with the booking was generated and sent to your e-mail address, please login and double check at dates, hours of travel and other sensitive details.</p>
                              <p>The final confirmation for the service will be sent by e-mail, please check the e-mail (including spam/junk folder) for details.</p> 
						      <p><b>In case you need to change something in your booking please make replies to the email with your booking. Always use the number of your booking in the title of emails</b>.</p>
						   </div>
					       
                        </article>
                        <!-- //Post -->
                </div>
                <!--- //Content -->
        </div>
</div>
{include file='../common/footer.phtml'}