{include file='../common/header.phtml'}
<!-- Page info -->
<header class="site-title color">
        <div class="wrap">
                <div class="container">
                        <h1>Terms & Conditions - Christian Transfers</h1>
                        <nav role="navigation" class="breadcrumbs">
                                <ul>
                                        <li><a href="/" title="Home">Home</a></li>
                                        <li>Terms & Conditions</li>
                                </ul>
                        </nav>
                </div>
        </div>
</header>
<!-- //Page info -->


<div class="wrap">
        <div class="row">			
                <!--- Content -->
                <div class="full-width content">
                        <!-- Post -->
                        <article class="single hentry">
                                <div class="entry-content">
                                        <h3><b>General description</b></h3>
                                        <p>The following terms and conditions apply to all passengers who make booking on all <b>Christian Transfers</b> websites with no exceptions.</p>
                                        <p>All passengers are automatically considered to have read and accepted all the Terms and Conditions listed below.</p>
                                        <p><b>Christian Transfers</b> is property of <b>Christian Transfers Ltd</b> who is registered in London.</p>
                                        <p>We operate the transfers for the bookings made on our websites with our<b> OWN CARS</b> or with <b>SUBCONTRACTORS CARS.</b></p>
                                        <p>Our office program is daily 08.00 - 20.00 GMT +2, Bucharest Hour.</p>
                                        <p>Our transfers and transportation program is <strong>Non Stop</strong> depend on the customers bookings. We operate transfers 24 hours a day, 7 days a week, 365 days a year, except free legal days like Christmas and Eastern.</p>

                                        <h3><b>Terms and conditions of price & payments</b></h3>
                                        <p>All the price on the website are in <b>Euro.</b></p>
                                        <p>For all the transportation bookings made on our website payment have to be made in advance.</p>
                                        <p>Payments can be made by Online by Card, bank transfer or bank deposit.</p>
                                        <p>Companies who have sign contract with our company can pay to the end of the month, or twice a month, for all transfers in privious period of calculation in Ron (Lei) romanian currency.</p>
                                        <p>For all the Tranportation service booked and payed on our website you will receive the invoice by email few days after. The receipt is issued automaticaly at the time of your online payment.</p>
                                        <p>All the price on the website for people transportations are final. A commission of 5% from the price (for cover the online card payment system) is add to the final step of the booking and charged at the time of the payment. This commission is part of your transfer price.</p>
                                        <p>The prices are the same for late in night pickups, weekends and legal holidays if you receive a confirmation in this matter.</p>
                                        <p>All the price for transfers outside <b>EU</b> can be recalculated when the conditions are different.</p>

                                        <h3><b>Terms and conditions of reservations</b></h3>
                                        <p>All booking and payments have to be made online on our website using the left website menu.</p>
                                        <p>All the transfers for bookings made by our company will be operate with our own cars or subcontractor cars like in the final confirmation sent to the email adress registred in your original reservation.</p>
                                        <p>Any change that you request for one of your booking have to be made online with a reply to your email with your orginial booking without changing the original email title.</p>
                                        <p>At the time of booking is mandatory for every passenger to provide a mobile phone number available at the time of the transfer.</p>

                                        <h3><b>Terms and conditions to cancel/reschedule a reservation</b></h3>
                                        <p>You can reschedule a transfer for another date/hour no later than 48 hours before the event have to take place if we have free seats available.</p>
                                        <p>You <b>can</b> cancel a transfer booking no later than 48 hours before the event have to take place.</p>
                                        <p>You can cancel a booking with less than 48 hours before the event have to take place but no refund of the payment is available in this case.</p>

                                        <h3><b>Terms and conditions to cancel a payment for a reservation</b></h3>
                                        <p>You <b>can't</b> cancel a payment if the transfer has already taken place.</p>
                                        <p>You can cancel a payment at any time <b>NO </b>later than 48 hours before the transfer/transportation with 90% refund. The 10% of the payment represent the bank transfers costs and cannot be refunded.</p>
                                        <p>Cancellation of a payment less than 48 hours to the transfer booking will lead to a fee of 100% of the amount in question. NO refund is possible in this situation.</p>
                                        <p>In case of <b>NO SHOW</b> or cancellations made less than 48 hours prior to your pick-up the payment made in advance for the booking is <b>NON-REFUNDABLE.</b></p>

                                        <h3><b>General terms and conditions for all kind of transportation</b></h3>
                                        <p>In all our cars is not allowed to smoke, drink alcool or eat.</p>
                                        <p>Main provider and his subcontractors assume full responsibility for complete bookings with complete payments to operate the transfers.</p>
                                        <p>We promise that all Transfer services you purchase from our web site will be performed with reasonable skill and care and, as far as reasonably possible, in accordance with our agreement. We will do our best to ensure that all materials and information published on our web site are accurate, but regrettably errors do occur, and we reserve the right to rectify such errors before your booking is confirmed.</p>
                                        <p>All passengers are obliged to comply with the General Conditions of Carriage and applicable provisions of the Transport Act Romania and all other countries where they will travel in our cars.</p>
                                        <p>Passengers are obliged to comply with transit countries, on the documents for entry and customs regulations, financial and administrative, on his person or in his lagguage.</p>
                                        <p>Main provider and his subcontractors does not assume any responsibility if a passenger does not comply with these provisions. If one or more passengers are detained and landed on grounds border crossing formalities and luggage unlawful or illegal, problem solving and time exceeds 30 minutes, the car will continue its journey without the passenger with problems.</p>
                                        <p>Main provider and his subcontractors does not assume any responsibility for delays of transportation and for losses incurred by passengers as a result of these delays. Arrival times depend on the waiting time at the border and the traffic on the roads.</p>
                                        <p>Main provider and his subcontractors assume no responsibility for incomplete bookings with NO payments and have <b>NO</b> obligation to book the car or to operate this transfers.</p>
                                        <p>Main provider and his subcontractors reserves the right to refuse service to drunk, intoxicated or abusive customers.</p>
                                        <p>The Transfer services are provided to you for private domestic use only and this is a consumer contract. Accordingly, we accept no liability for any business loss (which includes without limitation any loss of contracts, loss of profits, loss of revenue or loss of anticipated savings in expenditure or any loss or corruption of data) however caused, even if foreseeable. These exclusions do not apply to any liability we may have for death or personal injury resulting from our negligence and for which our liability is unlimited.</p>

                                        <h3><b>Specific terms and conditions for private Taxi & Minivans transportation</b></h3>
                                        <p>On private transportation the client establishes the time and location of pick up and dropp of.</p>
                                        <p>The vehicle will be private and no share with other unknown passengers.</p>
                                        <p>Prices quoted are total, per vehicle.</p>
                                        <p>If your outbound flight is delayed, your Transfer service will automatically be amended and your taxi will collect you at your revised time of arrival. Please note additional night supplements for the driver may be applicable.</p>
                                        <p>If your outbound flight is diverted for any reason, we will use reasonable endeavours to rearrange a taxi to collect you from your original destination airport at the revised landing time. In situation where notification of the diversion of the flight is too late to prevent the taxi driver from traveling to the airport or from waiting for the flight to arrive at the original landing time, you may have to book another taxi and pay additional charges.</p>

                                        <h3><b>Specific terms and conditions for Shuttle & Shared transportation</b></h3>
                                        <p>The vehicle will be shared with other unknown passengers.</p>
                                        <p>Prices quoted are per person and not per vehicle.</p>
                                        <p>On shuttle/shared transportation the clients have to adapt their programme after the car programme for the chosen route.</p>
                                        <p>The clients have to go to the bus/shuttle station for the chosen route which are public on the programme pages.</p>
                                        <p>Main provider and his subcontractors have <b>NO</b> responsibility to pickup or dropp off the clients to/from the clients adresses, unless we confirm this option in the confirmation emails.</p>
                                        <p>Passengers who book travel ticket for another passenger is responsible to the main provider and his subcontractors for any harmless from any damage caused by them.</p>
                                        <p>Children under 18 must travel accompanied by an adult. Children are only allowed on board buses supervised by adults or if they have an affidavit proving the parent or guardian permission to make the trip, and only if the country of destination and / or country transited during the trip and Conditions of main provider and his subcontractors permit</p>
                                        <p>It is forbidden to use radios, tape recorders of the mini-televisions, cameras or musical instruments on the bus. Using a walkman, CD player or laptop is allowed only if the volume is right at such a level that it does not disturb other passengers.</p>
                                        <p>Passengers who travel should refrain from deterioration or spoilage coach, consumption of alcohol, obstructing in any way the driver or other persons of the crew in the performance of their work in good conditions, causing discomfort or discomfort to other passengers in the bus or participants traffic.</p>
                                        <p>Behavior that does not comply or disregard the provisions of the Regulation entitles the leading provider of service or company authorized to carry or continue to prohibit passenger carrying journey, without the right to compensation or reimbursement of the ticket price.</p>
                                        <p>Carrier may refuse to transport or to discontinue no right to compensation or reimbursement of the ticket price in the following cases: 1 - passenger violates existing laws in Romania, Bulgaria, Hungary, Austria, Germany or the other countries where travels; 2 - is in a state indicating a contagious disease; 3 - has a discourteous behavior towards others in the bus or endanger the safety of passengers and other travelers such disturbing journey.</p>
                                        <p>No smoking is allowed in all public transport buses. We rae covered by the law to ask travelers who violates this rule or defying request not to smoke, to descend from the bus immediately without the right to compensation or reimbursement of the ticket price.</p>
                                        <p>If scheduled stops on the route, travelers must return to coach during the announcement before stopping. Otherwise, the bus will leave the station without traveling undisclosed leading provider of services and its carriers does not bear any responsibility for the consequences of that.</p>
                                        <p>Throughout the trip, the traveler must respect the conditions and safety rules on board the bus.</p>

                                        <h3><b>Data protection and security</b></h3>
                                        <p>Personal booking data is <b>NOT</b> collected when you make a booking at our websites. The credit/debit card data is protected by a secure online connection (SSL) between the purchaser s and the connected computer, namely according to browser configuration up to 128 bit. You can find further information about our data protection rules here on our privacy policy page.</p>

                                        <h3><b>Miscellaneous</b></h3>
                                        <p>Due to the technical specifications of the Internet we cannot guarantee the availability of all booking modules at our websites at all times. If separate clauses are or become invalid, all other clauses shall remain in force. Governing law is the England law. Place of jurisdiction is London.</p>

                                        <h3><b>Final description</b></h3>
                                        <p>We may alter these terms and conditions from time to time and post the new version on our web site, following which all use of our web site will be governed by that version. You must check the terms and conditions on the web site regularly. The terms governing the purchase of any <b>Transfer</b> service will be the terms in place at the time of your order.</p>
                                        <p>These terms and conditions together with your order form and payment method instructions, are the whole agreement between you and Christian Transfers.</p>
                                        <p>A person who is not a party to our agreement and dont have any reservation prepaid with us has no rights under the <b>Contracts.</b></p>
                                        <p>These terms and conditions, together with the privacy policy, any order form and payment method instructions, if any, replace all other terms and conditions previously applicable to the use of our web site and/or sale of the Service.</p>
                        </article>
                        <!-- //Post -->
                </div>
                <!--- //Content -->
        </div>
</div>
{include file='../common/footer.phtml'}