{include file='../common/header.phtml'}
<!-- Page info -->
<header class="site-title color">
    <div class="wrap">
        <div class="container">
            <h1>Recovery Cars - Christian Transfers</h1>
            <nav role="navigation" class="breadcrumbs">
                <ul>
                    <li><a href="/" title="Home">Home</a></li>
                    <li>Recovery Cars</li>
                </ul>
            </nav>
        </div>
    </div>
</header>
<!-- //Page info -->

<div class="wrap">
			<div class="row">
				
				<!--- Sidebar -->
				<aside class="one-fourth sidebar left">
					
					<!-- Widget -->
					<div class="widget">
						<h4>Recovery cars</h4>
						<a href="#"><img src="images/uploads/recovery cars london.jpg" alt="recovery cars" title="Recovery cars London" /></a>
					</div>
					<!-- //Widget -->
					
						<!-- Widget -->
					<div class="widget">
						<h4>Recovery truck</h4>
						<a href="#"><img src="images/uploads/recovery truck.jpg" alt="recovery truck" title="Recovery truck" /></a>
					</div>
					<!-- //Widget -->
					


					<!-- Widget -->
					<div class="widget">
						<h4>How to make a booking?</h4>
						<div class="textwidget">
							<p>Please dowload the MayaMix Andoid App </br></br><a href="https://play.google.com/store/apps/details?id=christian.transfers.maya&hl=en_IN" target="_blank"><img src="/images/zcards/_app-google.png" alt="maya mix app for android"></a></p>
							<p>Please dowload the MayaMix iOS App </br></br><a href="https://itunes.apple.com/us/app/maya-mix/id1330460397?mt=8" target="_blank"><img src="/images/zcards/_app-apple.png" alt="maya mix app for ios"></a></p>
							<p>If you need to contact us with other enquiries or to join our team please use the contact form by <a href="http://www.mayamix.co.uk/contacts.html" target="_blank">clicking here</a></p>
						</div>
					</div>
					<!-- //Widget -->
					
					<!-- Widget -->
					<div class="widget">
						<h4>Recovery cars</h4>
						<a href="#"><img src="images/uploads/recovery cars crawley.png" alt="recovery cars" title="Recovery cars Crawley" /></a>
					</div>
					<!-- //Widget -->
					
						<!-- Widget -->
					<div class="widget">
						<h4>Heavy recovery</h4>
						<a href="#"><img src="images/uploads/heavy recovery.jpg" alt="heavy recovery" title="Heavy recovery" /></a>
					</div>
					<!-- //Widget -->
				</aside>
				<!--- //Sidebar -->
				
				<!--- Content -->
				<div class="three-fourth content">
					<!-- Post -->
					<article class="single hentry">
						<div class="entry-featured">
							<img src="images/uploads/recovery cars christian transfers.jpg" alt="recovery cars london" title="Recovery cars London" />
						</div>
						<div class="entry-content">
					<h2>If your vehicle has broken down, don't worry.</h2>
					<p>MayaMix App is the new digital point of contact between you and any contractor—anywhere.</p> 
					<p>There’s no cost to use this service and you're under no obligation to employ anyone MayaMix Appconnects you with.</p> 
					<p>As soon as we find someone available in your area, we'll connect you for a free consultation.</p> 
					<p>A vehicle recovery specialist can help you restart it, or they can recover your car and transport it wherever you need when necessary.</p>
					<p>Our aim is to give you an efficient and cost effective car service that is local to you.</p> 
					<p>We understand the frustration when you’re left without a working vehicle and so we aim to solve the problem quickly and without fuss allowing you to return to your daily life.</p>
					<p>That’s why at any time of the day or night we aim to be just minutes away so you can call us safe in the knowledge that this problem will soon be over.</p> 
					<p>We understand how frustrating and worrying it is to be stuck without transportation, so we ensure we get to you as quick as we can so you can be home in no time.</p>
					<p>For massive savings on main dealer prices call us now or book online</p> 
					<p>MayaMix App Easily Accessible Service</p>
					
					<h3><strong>For recovery car owners</strong></h3>
					<p>Like meeting new people in interesting circumstances?</p> 
					<p>You’ll be a welcome face to those stuck by the side of the road.</p> 
					<p>You’ll be recovering vehicles that have broken down, crashed or been involved in crime.</p> 
					<p>And you’ll be independent, patient and able to use your initiative, as well as being friendly and helpful.</p>
					<p>For recovery drivers, every day is different. You’ll never be bored.</p> 
					<p>Think driving is a pleasure, not a chore – even in London, Manchester, Dublin, Cardiff or Glasgow? Then we want to hear from you.</p>
						</div>
					</article>
					<!-- //Post -->
				</div>
				<!--- //Content -->
			</div>
		</div>
	</main>

    <!-- Services iconic -->
    <div class="services iconic white">
        <div class="wrap">
            <div class="row">
				<!-- Item -->
				<div class="one-third wow fadeIn">
					<span class="circle"><span class="icon fa fa-heart-o"></span></span>
					<h3>Shuttle Buses</h3>
					<p>Shuttle bus services. These services operate only on specific routes with fixed stops and fixed timetable, with minibuses or coaches.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".2s">
					<span class="circle"><span class="icon fa fa-magic"></span></span>
					<h3>Cars & Minivans hire</h3>
					<p>The cars and the minivans used day by day, for decades, for your business transfers or airport transfers.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".4s">
					<span class="circle"><span class="icon fa fa-paperclip"></span></span>
					<h3>Taxi & taxi assist</h3>
					<p>The classic taxi as we know it, the assist option been for disabled persons, taxis which can embark you with your wheel chair.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn">
					<span class="circle"><span class="icon fa fa-heart-o"></span></span>
					<h3>Minibuses Rental</h3>
					<p>Minibuses accessible, hire from the leading specialists, for airport transfers and all types of travel.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".2s">
					<span class="circle"><span class="icon fa fa-magic"></span></span>
					<h3>Executive cars hire</h3>
					<p>Private car hire with driver, Mercedes-Benz E or V classe, Audi A6, BMW 5 series, first class service.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".4s">
					<span class="circle"><span class="icon fa fa-paperclip"></span></span>
					<h3>Same day couriers</h3>
					<p>Same day delivery gives you options, 365 days a year. Providing flexible, reliable and cost-effective solutions.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn">
					<span class="circle"><span class="icon fa fa-heart-o"></span></span>
					<h3>Coaches rental</h3>
					<p>A wide range of quality vehicles, a simple renting process, rental periods which suit your plan really is the ultimate way to your coaches hire.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".2s">
					<span class="circle"><span class="icon fa fa-magic"></span></span>
					<h3>Vip cars hire</h3>
					<p>Private car hire with driver in VIP vehicle. Mercedes-Benz S, Audi A8, Mercedes-Benz V or similar models for luxury travel.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".4s">
					<span class="circle"><span class="icon fa fa-paperclip"></span></span>
					<h3>Recovery cars</h3>
					<p>You need it on average 1-5 times in your life, why should you pay monthly for decades ? Download our App and pay only when you need it.</p>
				</div>
				<!-- //Item -->
            </div>
        </div>
	</div>
	
        {include file='../common/footer.phtml'}