{include file='../common/header.phtml'}
<div class="wrap">
    <div class="row"><div align="center">
            <p><div class="fb-like" data-href="https://www.facebook.com/Christian Transfers" data-send="true" data-width="700" data-show-faces="false" data-action="recommend">
            </div>
            </p>
        </div>

        <div align="center">
            <h1>Minivan and minibus hire with driver in Slovakia - Pickups from Airports Bratislava, Vienna, Budapest or Prague</h1>
        </div>

        <div class="wrapper">
            <article class="cols400">
                <figure><img src="images/slovakia/slovakia bratislava aiport.jpg" width="240" alt="bratislava aiport" title="Bratislava Aiport" class="pad_bot2"></figure>
                <p class="pad_bot1"><strong>If you have an organized group, do not hesitate to contact us to rent a private minivan, minibus or coach with our chauffeur included.</strong></p>
                <p>You can communicate the programme for vehicles rental and we will do as soon as possible a complete offer according with your request. Rent conditions and exceptional value for money make this version a very good alternative.</p>
            </article>

            <article class="cols400 pad_left1">
                <p>In Slovakia we provides transportation for any type of event: Transfers to / from airport, city tours, travel to Austria, Hungary, Czech Republic or Germany or other countries in region, business trips, transportation for delegates, conferences, holidays at home and abroad, teambuilding for companies, private tours or special events.</p> 
                <p>All the cars and minibuses offered in Slovakia can be rented only with our chauffeur service included. At this time we don't have the option to rent a car to be driven by client. On request we can offer specialized travel guide for english or german language.</p>
            </article>

            <article class="cols400 pad_left1">
                <figure></figure>
                <figure><img src="images/slovakia/slovakia bratislava.jpg" width="240" alt="bratislava city center" title="Bratislava city center" class="pad_bot2"></figure>
                <p>We offer pickups from both major airports serve the country Bratislava Airport and Vienna Airport, to all destinations you may need, just some of them been Bratislava, Nitra, Trnava, Vienna, Budapest, Prague, Brno.</p>
                <a href="contact.html" class="button1"><strong>Contact us</strong></a>
            </article>
        </div>

        <table class="responsive" width="100%" border="0" cellpadding="0" cellspacing="0">
            <tr>
                <td valign="top" align="right" colspan="8">
                    <p><a href="minibus.html"><font color="#000">Back to all Minibus list</font></a></p>
                </td>
            </tr>
        </table>

        <table class="responsive" width="100%" border="5" cellpadding="5" cellspacing="5">
            <tr>
                <th valign="top" align="Left" colspan="8">
                    <p><font color="#1616E9"></font></p>
                </th>
            </tr> 
            <tr>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <img src="images/crafter 2013 exterior.JPG" width="110" alt="minibus rental with driver" title="Minibus for rent in Slovakia Bratislava" class="pad_bot2"> 
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Available pick-up</b></br>Bratislava Airport</br>Bratislava</br>Vienna Airport</br>Vienna</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Minivan 8 seater</br></br>Minibus 15 seater</b></br></br>Available for inquiries</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Minibus 20 seater</br></br>Coach 50 seater</b></br></br>Available for inquiries</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Send your request</b></br></br><a href="contact.html" class="button1"><strong>Contact us</strong></a></font>
                </td>
            </tr>
        </table>
        <table class="responsive" width="100%" border="0" cellpadding="5" cellspacing="5">
            <tr>
                <td valign="top" align="center" colspan="8">
                    <img src="images/slovakia/slovakia bratislava hrad castle.jpg" width="220" alt="bratislava hrad castle" title="Bratislava Castle - Slovakia" class="pad_bot2">
                    <img src="images/slovakia/slovakia spis castle.jpg" width="220" alt="spis castle" title="Spis Castle - Slovakia" class="pad_bot2">
                    <img src="images/slovakia/slovakia bojnice castle.jpg" width="220" alt="bojnice castle" title="Bojnice Castle - Slovakia" class="pad_bot2">
                </td>
            </tr>
        </table>

        <table class="responsive" width="100%" border="0" cellpadding="0" cellspacing="0">
            <tr>
                <td valign="top" align="center"><p>
                        <a href="minibusingermany.html"><font color="#000">Minibus in Germany</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusincroatia.html"><font color="#000">Minibus in Croatia</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusinromania.html"><font color="#000">Minibus in Romania</font></a></p>
                </td>
            </tr>
            <tr>
                <td valign="top" align="center"><p>
                        <a href="minibusinhungary.html"><font color="#000">Minibus in Hungary</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusinaustria.html"><font color="#000">Minibus in Austria</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusinslovakia.html"><font color="#000">Minibus in Slovakia</font></a></p>
                </td>
            </tr>
            <tr>
                <td valign="top" align="center"><p>
                        <a href="minibusinbulgaria.html"><font color="#000">Minibus in Bulgaria</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusinserbia.html"><font color="#000">Minibus in Serbia</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusinmontenegro.html"><font color="#000">Minibus in Montenegro</font></a></p>
                </td>
            </tr>
        </table> 

        <div align="center">
            <p><div class="fb-like" data-href="https://www.facebook.com/Christian Transfers" data-send="true" data-width="700" data-show-faces="false" data-action="recommend">
            </div>
            </p>
        </div>
    </div>
</div>

{include file='../common/footer.phtml'}