{include file='../common/header.phtml'}
<div class="wrap">
    <div class="row">
        <div align="center">
            <p><div class="fb-like" data-href="https://www.facebook.com/Christian Transfers" data-send="true" data-width="700" data-show-faces="false" data-action="recommend">
            </div>
            </p>
        </div>

        <div align="center">
            <h1>Minivan and minibus hire with driver in Austria - Pickups from Airports Vienna, Salzburg, Graz, Innsburck</h1>
        </div>

        <div class="wrapper">
            <article class="cols400">
                <figure><img src="images/austria/austria vienna airport flughafen.jpg" width="240" alt="austria vienna airport flughafen" title="Vienna Airport" class="pad_bot2"></figure>
                <p class="pad_bot1"><strong>If you have an organized group, do not hesitate to contact us to rent a private minivan, minibus or coach with our chauffeur included.</strong></p>
                <p>You can communicate the programme for vehicles rental and we will do as soon as possible a complete offer according with your request. Rent conditions and exceptional value for money make this version a very good alternative.</p>
            </article>

            <article class="cols400 pad_left1">
                <p>In capital of Austria Vienna, which is host for many major international organizations, including the United Nations and OPEC, number one destination for international congresses and conventions between 2005 and 2013, our company provides minivans, minbuses or coaches for any type of event: transfers to / from airport, private city tours, business trips, transportation for delegates, teambuilding for companies or special events.</p> 
                <p>All the cars and minibuses offered in Austria can be rented only with our chauffeur service included. At this time we don't have the option to rent a car to be driven by client. On request we can offer specialized travel guide for english language.</p>
            </article>

            <article class="cols400 pad_left1">
                <figure></figure>
                <figure><img src="images/austria/austria vienna un building vereinte nationen.jpg" width="240" alt="austria vienna un building vereinte nationen" title="Vienna UN building" class="pad_bot2"></figure>
                <p>We offer pickups from all major airports serve the country Vienna, Graz, Salzburg, Innsbruck to all destinations you may need, just some of them been Vienna, Graz, Salburg, Kaprun, Badgastein, Zell am See.</p>
                <a href="contact.html" class="button1"><strong>Contact us</strong></a>
            </article>
        </div>

        <table class="responsive" width="100%" border="0" cellpadding="0" cellspacing="0">
            <tr>
                <td valign="top" align="right" colspan="8">
                    <p><a href="minibus.html"><font color="#000">Back to all Minibus list</font></a></p>
                </td>
            </tr>
        </table>

        <table class="responsive" width="100%" border="5" cellpadding="5" cellspacing="5">
            <tr>
                <th valign="top" align="Left" colspan="8">
                    <p><font color="#1616E9"></font></p>
                </th>
            </tr> 
            <tr>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <img src="images/crafter 2013 exterior.JPG" width="110" alt="minibus volkswagen crafter 2013 rental with driver" title="Minibus Volkswagen Crafter 2013" class="pad_bot2"> 
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Available pick-up</b></br>Vienna Airport</br>Vienna</br>Graz</br>Salzburg</br>Innsbruck</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Minivan 8 seater</br></br>Minibus 14 seater</b></br></br>Available for inquiries</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>MiniCoach 26 seater</br></br>Coach 50 seater</b></br></br>Available for inquiries</font>
                </td>
                <td valign="top" align="center" width="20%" bgcolor="#F0DDBD">
                    <font color="#000"><b>Send your request</b></br></br><a href="contact.html" class="button1"><strong>Contact us</strong></a></font>
                </td>
            </tr>
        </table>
        <table class="responsive" width="100%" border="0" cellpadding="5" cellspacing="5">
            <tr>
                <td valign="top" align="center" colspan="8">
                    <img src="images/austria/austria vienna prater ernst happel stadion.jpg" width="220" alt="austria vienna prater ernst happel stadion" title="Vienna Prater Ernst Happel Arena - Austria" class="pad_bot2">
                    <img src="images/austria/austria zell am see.jpg" width="220" alt="austria zell am see" title="Zell am See ski resort- Austria" class="pad_bot2">
                    <img src="images/austria/austria salzburg old town.jpg" width="220" alt="austria salzburg old town" title="Salzburg old town - Austria" class="pad_bot2">
                    </br>
                    <img src="images/austria/austria badgastein centre.jpg" width="220" alt="austria badgastein centre" title="Badgastein city centre - Austria" class="pad_bot2">
                    <img src="images/austria/austria badgastein slopes.jpg" width="220" alt="austria badgastein slopes" title="Badgastein slopes - Austria" class="pad_bot2">
                    <img src="images/austria/austria vienna belvedere.jpg" width="220" alt="austria vienna belvedere" title="Vienna Belvedere - Austria" class="pad_bot2">
                </td>
            </tr>
        </table>

        <table class="responsive" width="100%" border="0" cellpadding="0" cellspacing="0">
            <tr>
                <td valign="top" align="center"><p>
                        <a href="minibusingermany.html"><font color="#000">Minibus in Germany</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusincroatia.html"><font color="#000">Minibus in Croatia</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusinromania.html"><font color="#000">Minibus in Romania</font></a></p>
                </td>
            </tr>
            <tr>
                <td valign="top" align="center"><p>
                        <a href="minibusinhungary.html"><font color="#000">Minibus in Hungary</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusinaustria.html"><font color="#000">Minibus in Austria</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusinslovakia.html"><font color="#000">Minibus in Slovakia</font></a></p>
                </td>
            </tr>
            <tr>
                <td valign="top" align="center"><p>
                        <a href="minibusinbulgaria.html"><font color="#000">Minibus in Bulgaria</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusinserbia.html"><font color="#000">Minibus in Serbia</font></a></p>
                </td>
                <td valign="top" align="center"><p>
                        <a href="minibusinmontenegro.html"><font color="#000">Minibus in Montenegro</font></a></p>
                </td>
            </tr>
        </table> 

        <div align="center">
            <p><div class="fb-like" data-href="https://www.facebook.com/Christian Transfers" data-send="true" data-width="700" data-show-faces="false" data-action="recommend">
            </div>
            </p>
        </div>
    </div>
</div>
{include file='../common/footer.phtml'}