{include file='../common/header.phtml'}
<!-- Page info -->
<header class="site-title color">
    <div class="wrap">
        <div class="container">
            <h1>Taxi & Taxi Assist - Christian Transfers</h1>
            <nav role="navigation" class="breadcrumbs">
                <ul>
                    <li><a href="/" title="Home">Home</a></li>
                    <li>Taxi & Taxi Assist</li>
                </ul>
            </nav>
        </div>
    </div>
</header>
<!-- //Page info -->

<div class="wrap">
			<div class="row">
				
				<!--- Sidebar -->
				<aside class="one-fourth sidebar left">
					
					<!-- Widget -->
					<div class="widget">
						<h4>Taxi</h4>
						<a href="#"><img src="images/uploads/taxi1.jpg" alt="taxi" title="Taxi" /></a>
					</div>
					<!-- //Widget -->
					
						<!-- Widget -->
					<div class="widget">
						<h4>Taxi  Assist</h4>
						<a href="#"><img src="images/uploads/taxi assist.jpg" alt="taxi assist" title="Taxi Assist" /></a>
					</div>
					<!-- //Widget -->
					
					<!-- Widget -->
					<div class="widget">
						<h4>How to make a booking?</h4>
						<div class="textwidget">
							<p>Please dowload the MayaMix Andoid App </br></br><a href="https://play.google.com/store/apps/details?id=christian.transfers.maya&hl=en_IN" target="_blank"><img src="/images/zcards/_app-google.png" alt="maya mix app for android"></a></p>
							<p>Please dowload the MayaMix iOS App </br></br><a href="https://itunes.apple.com/us/app/maya-mix/id1330460397?mt=8" target="_blank"><img src="/images/zcards/_app-apple.png" alt="maya mix app for ios"></a></p>
							<p>If you need to contact us with other enquiries or to join our team please use the contact form by <a href="http://www.mayamix.co.uk/contacts.html" target="_blank">clicking here</a></p>
						</div>
					</div>
					<!-- //Widget -->
					
					<!-- Widget -->
					<div class="widget">
						<h4>Maya Mix</h4>
						<a href="#"><img src="images/uploads/maya mix.jpg" alt="mayamix.eu and mayamix.co.uk" title="MayaMix.eu and MayaMix.co.uk" /></a>
					</div>
					<!-- //Widget -->
					
                      <!-- Widget -->
					<div class="widget">
						<h4>Download the app</h4>
						<a href="#"><img src="images/uploads/download the app.jpg" alt="download the app" title="Download the MayaMix App" /></a>
					</div>
					<!-- //Widget -->
					
					  <!-- Widget -->
					<div class="widget">
						<h4>Taxi, Courier or Recovery car service</h4>
						<a href="#"><img src="images/uploads/taxi courier or recovery car service.jpg" alt="taxi courier or recovery car service" title="Taxi, Courier or Recovery car service" /></a>
					</div>
					<!-- //Widget -->
				</aside>
				<!--- //Sidebar -->
				
				<!--- Content -->
				<div class="three-fourth content">
					<!-- Post -->
					<article class="single hentry">
						<div class="entry-featured">
							<img src="images/uploads/taxi and taxi assist london crawley brighton.jpg" alt="taxi and taxi assist london crawley brighton" title="Taxi and Taxi Assist London Crawley Brighton" />
						</div>
						<div class="entry-content">
					<h2>Not sure what to choose?</h2>
                                <p>A new category in city travel, that makes daily commuting more reliable,comfortable and stress free at a price point similar to public transport.</p> 
                                <p>Smart mobility, quality, on-demand shuttles at everyday prices.</p>
                                <p>Are you looking for access to hundreds of different vehicles, from black taxi to executive cars?</p> 
                                <p>Safety ,from start to finish, a ride you can trust.</p> 
                                <p>Pay by App.</p> 
                                <p>Add a payment method to your account (credit card or PayPal) and pay for your journey with the app. With guaranteed security and at your fingertips – it couldn’t be simpler!</p> 
                                <p>Fill out the form below and we'll help you find the solution that's right for you.</p> 
                                <p>Enjoy the ride!</p> 

                                <h3><strong>For licensed taxi and assist taxi owners</strong></h3>
                                <p>Whether you're a black cab driver or a courier driver, it's quick and easy to start working with us.</p> 
                                <p>Refer a friend programme.</p>
                                <p>Why become a MayaMix driver?</p> 
                                <p>Earn more with MayaMix App. More jobs = more money.</p> 
                                <p>Get the free driver app - Manage your work in the app for iOS and Android.</p> 
                                <p>Secure card payments - No need to handle cash.</p> 
                                <p>Refer a friend programme.</p> 
                                <p>It's easy to join MayaMix App</p> 
                                <p>Sign up - Download the app.</p> 
                                <p>We're always on the lookout for talented, Driven by Quality people, to share our passion for innovation. Join our team and be part of one of the most exciting global startups!</p>
                                <p>You are one of us if...</p> 
                                <p>You work hard, you play hard, you are driven by quality.</p> 
                                <p>You have a sense for the little things and understand consumer needs.</p> 
                                <p>You are a team player, positive, humble and have a ‘can do ’attitude.</p> 
                                <p>Ideally connected.</p> 
                                <p>Simply intuitive.</p> 
                                <p>We and our drivers have developed what is probably the most intuitive app on the market.</p>
						</div>
					</article>
					<!-- //Post -->
				</div>
				<!--- //Content -->
			</div>
		</div>
	</main>

    <!-- Services iconic -->
    <div class="services iconic white">
        <div class="wrap">
            <div class="row">
				<!-- Item -->
				<div class="one-third wow fadeIn">
					<span class="circle"><span class="icon fa fa-heart-o"></span></span>
					<h3>Shuttle Buses</h3>
					<p>Shuttle bus services. These services operate only on specific routes with fixed stops and fixed timetable, with minibuses or coaches.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".2s">
					<span class="circle"><span class="icon fa fa-magic"></span></span>
					<h3>Cars & Minivans hire</h3>
					<p>The cars and the minivans used day by day, for decades, for your business transfers or airport transfers.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".4s">
					<span class="circle"><span class="icon fa fa-paperclip"></span></span>
					<h3>Taxi & taxi assist</h3>
					<p>The classic taxi as we know it, the assist option been for disabled persons, taxis which can embark you with your wheel chair.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn">
					<span class="circle"><span class="icon fa fa-heart-o"></span></span>
					<h3>Minibuses Rental</h3>
					<p>Minibuses accessible, hire from the leading specialists, for airport transfers and all types of travel.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".2s">
					<span class="circle"><span class="icon fa fa-magic"></span></span>
					<h3>Executive cars hire</h3>
					<p>Private car hire with driver, Mercedes-Benz E or V classe, Audi A6, BMW 5 series, first class service.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".4s">
					<span class="circle"><span class="icon fa fa-paperclip"></span></span>
					<h3>Same day couriers</h3>
					<p>Same day delivery gives you options, 365 days a year. Providing flexible, reliable and cost-effective solutions.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn">
					<span class="circle"><span class="icon fa fa-heart-o"></span></span>
					<h3>Coaches rental</h3>
					<p>A wide range of quality vehicles, a simple renting process, rental periods which suit your plan really is the ultimate way to your coaches hire.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".2s">
					<span class="circle"><span class="icon fa fa-magic"></span></span>
					<h3>Vip cars hire</h3>
					<p>Private car hire with driver in VIP vehicle. Mercedes-Benz S, Audi A8, Mercedes-Benz V or similar models for luxury travel.</p>
				</div>
				<!-- //Item -->
				
				<!-- Item -->
				<div class="one-third wow fadeIn" data-wow-delay=".4s">
					<span class="circle"><span class="icon fa fa-paperclip"></span></span>
					<h3>Recovery cars</h3>
					<p>You need it on average 1-5 times in your life, why should you pay monthly for decades ? Download our App and pay only when you need it.</p>
				</div>
				<!-- //Item -->
            </div>
        </div>
	</div>
{include file='../common/footer.phtml'}
