{include file='../common/header.phtml'}
	<!-- Main -->
	<!-- Page info -->
	<main class="main" role="main">
		<!-- Page info -->
		<header class="site-title color">
			<div class="wrap">
				<div class="container">
					<h1>Coach airport transfers and coach rentals - Christian Transfers</h1>
					<nav role="navigation" class="breadcrumbs">
						<ul>
							<li><a href="/" title="Christian Transfers - Airport Transfers">Go to Home</a></li>
							<li>You are on Coaches</li>
						</ul>
					</nav>
				</div>
			</div>
		</header>
	<!-- //Page info -->
		
		<div class="wrap">
			<div class="row">
				
				<!--- Sidebar -->
				<aside class="one-fourth sidebar left">
					<!-- Widget -->
					<div class="widget">
						<h4>Airport transfers</h4>
						<a href="#"><img src="images/uploads/coach airport transfers.jpg" alt="coach airport transfers" title="Coach airport transfers" /></a>
					</div>
					<!-- //Widget -->
					
					<!-- Widget -->
					<div class="widget">
						<h4>Coach rentals</h4>
						<a href="#"><img src="images/uploads/coach rentals.jpg" alt="coach rentals" title="Coach rentals" /></a>
					</div>
					<!-- //Widget -->
					
					{include file='../common/sidebar2.phtml'}
					
					<!-- Widget -->
					<div class="widget">
						<h4>Airport transfers</h4>
						<a href="#"><img src="images/uploads/coach airport transfers romania.jpg" alt="coach airport transfers romania" title="Coach airport transfers Romania" /></a>
					</div>
					<!-- //Widget -->
					
					<!-- Widget -->
					<div class="widget">
						<h4>Coach rentals</h4>
						<a href="#"><img src="images/uploads/coach rentals bulgaria.jpg" alt="coach rentals bulgaria" title="Coach rentals Bulgaria" /></a>
					</div>
					<!-- //Widget -->
					
					<!-- Widget -->
					<div class="widget">
						<h4>Tailor made rentals</h4>
						<a href="#"><img src="images/uploads/coach airport transfers serbia.jpg" alt="coach airport transfers serbia" title="Coach airport transfers Serbia" /></a>
					</div>
					<!-- //Widget -->
				</aside>
				<!--- //Sidebar -->
				
				<!--- Content -->
				<div class="three-fourth content">
					<!-- Post -->
					<article class="single hentry">
						<div class="entry-featured">
							<img src="images/uploads/coach rentals and airport transfers.jpg" alt="coach rentals and airport transfers" title="Coach rentals and airport transfers" />
						</div>
						<div class="entry-content">
							<h2>Coach airport transfers and coach rentals - Christian Transfers</h2>
							<p class="lead">Christian Transfers offer airport transfers and bus rentals from several Airports.</p>
							<p>Pick-up from all Austria Airports Vienna, Salzburg, Graz, Innsbruck Tirol and going to Vienna, Salzburg, Graz, Zell am See, Kaprun, Saalbach, Hinterglemm, Gasteinertal, Flachau, Flachauwinkel, Kleinarl, Großarl, Wagrain, Maria Alm, Leogang, Dienten, Mühlbach a. Hochkönig, Saalfelden, Piesendorf, Schladming, Kitzbühel, Westendorf, Brixen, Hopfgarten, Wildschönau, Kirchberg, Scheffau, Ellmau, Söll, Obergurgl, Hochgurgl, Sölden, Ischgl, Galtür, Lech, Zürs, St. Anton am Arlberg, Serfaus, Ladis, Fiss, Fulpmes, Hintertux, Igls, Mayrhofen, Neustift, Seefeld, Going, Niederau, Alpbach, St.Johann in Tirol.</p>
							<p>We organize transfer by taxis and minvans or rentals with coaches and buses to all Austria destinations or abroad to Hungary, Slovakia, Czech Republic, Germany, Switzerland, Croatia, Italy, Slovenia, Serbia and Bosnia Hertegovina.</p>
						    <p>Pick-up from all Hungary Airports and cities Budapest, Balaton, Szeged and Debrecen and going to Balatonalmadi, Balatonboglar, Balatonfured, Bekescsaba, Debrecen, Dunaujvaros, Gyor, Kecskemet, Miskolc, Nyiregyhaza, Pecs, Siofok, Sopron, Szeged, Szekesfehervar, Szentes, Szolnok, Szombhately, Veszprem, Timisoara Airport, Arad, Cluj, Oradea, Brasov, Sibiu, Zagreb, Rijeka, Dubrovnik, KRK Airport, National Parc Plitvicer, Osijek, Novalja Pag, Varazdin, Crikvenica, Opatija, Porec, Pula, Sibenik, Split, Umag, Maribor, Zadar, Ljubljana, Belgrad, Novi Sad, Budapest Airport, Pecs, Szeged, Trieste, Udine, Venezia Airport, Graz, Klagenfurt, Linz, Salzburg, Wien.</p>
							<p>We organize transfer by taxis and minvans or rentals with coaches and buses to all Hungary destinations or abroad to Austria, Croatia, Romania, Polska, Germany, Slovakia, Italy, Slovenia, Serbia, Ukraine, Motenegro and Bosnia Hertegovina.</p>
							<p>Pick-up from all Croatia Airports Zagreb, Rijeka, Dubrovnik and going to Zagreb, Rijeka, Dubrovnik, KRK Airport, National Parc Plitvicer, Osijek, Novalja Pag, Varazdin, Crikvenica, Opatija, Porec, Pula, Sibenik, Split, Umag, Maribor, Zadar, Ljubljana, Belgrad, Novi Sad, Budapest Airport, Pecs, Szeged, Trieste, Udine, Venezia Airport, Graz, Klagenfurt, Linz, Salzburg, Wien.</p>
							<p>We organize transfer by taxis and minvans or rentals with coaches and buses to all Croatia destinations or abroad to Austria, Hungary, Italy, Slovenia, Serbia, Motenegro and Bosnia Hertegovina.</p>
							<p>Pick-up from all Germany Airports and cities Munich, Berlin, Frankfurt for events in Hamburg, Stuttgart, Bremen, Dusseldorf, Nuremberg, Strasbourg, Paris, Torino, Milano, Roma, Venezia Copenhagen, Warsaw, Wroclaw, Poznan, Prague, Brno, Wien, Salzburg, Zurich, Berne, Geneva, Amsterdam, Eindhoven, Brussel, Zagreb, Maribor, Ljubljana, Belgrad, Budapest, Bratislava.</p>
							<p>We organize transfer by taxis and minvans or rentals with coaches and buses to all Germany destinations or abroad to France, Belgium, Holland, Luxembourg, Switzerland, Austria, Denmark, Liechtenstein, Czech Republic, Italy, Croatia, Polska, Slovakia, Slovenia.</p>
							<p>Pick-up from Bucharest Otopeni Airport, Constanta Airport, Timisoara Airport Brasov or Sibiu for groups of 5 to unlimited number of persons and transfers to all Bucharest or Romania Hotels or for Bucharest city tour - House of the People, The Village Museum, Triumphal Arch, Romanian Peasant Museum, Romanian Athenaeum, Patriarchal Church. One day tour arround Bucharest - Mogosoaia Palace, Manasteries like: Cernica, Pasarea, Tiganesti, Caldarusani and Snagov.Transilvania Tour - One full day to visit 4 Castles in Transilvania: Peles, Pelisor, Bran, Cantacuzino. After this we go to a very nice dinner in Brasov.</p>
							<p>Inter city transfers with private minivans, mini coaches and coaches for special events, wedings, conferences, parties, private groups or special ceremony.</p>
						</div>
					</article>
					<!-- //Post -->
				</div>
				<!--- //Content -->
			</div>
		</div>
	</main>
	<!-- //Main -->
	
	<!-- Page info -->
		<header class="site-title color">
			<div class="wrap">
				<div class="container">
					<h1>Christian Transfers Services</h1>
					<nav role="navigation" class="breadcrumbs">
						<ul>
							<li><a href="/" title="Christian Transfers - Airport Transfers">Go to Home</a></li>
							<li>You are on Coaches</li>
						</ul>
					</nav>
				</div>
			</div>
		</header>
	<!-- //Page info -->
{include file='../common/sidebar3.phtml'}
{include file='../common/footer.phtml'}