{include file='../common/header.phtml'}
    <!-- Main -->
	<!-- Page info -->
	<main class="main" role="main">
		<!-- Page info -->
		<header class="site-title color">
            <div class="wrap">
                <div class="container">
                    <h1>Urgent and same day courier service Gatwick Crawley London</h1>
                    <nav role="navigation" class="breadcrumbs">
                        <ul>
                            <li><a href="/" title="Christian Transfers - Airport Transfers">Go to Home</a></li>
                            <li>You are on Urgent Couriers</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
    <!-- //Page info -->

        <div class="wrap">
			<div class="row">
				
				<!--- Sidebar -->
				<aside class="one-fourth sidebar left">
					
					<!-- Widget -->
					<div class="widget">
						<h4>Bike courier</h4>
						<a href=""><img src="images/uploads/bike courier.jpg" alt="bike courier gatwick airport and crawley" title="Bike courier in Gatwick Airport and Crawley area"/></a>
					</div>
					<!-- //Widget -->
					
					<!-- Widget -->
					<div class="widget">
						<h4>Moto courier</h4>
						<a href=""><img src="images/uploads/moto courier.png" alt="moto courier gatwick airport and crawley" title="Moto courier in Gatwick Airport and Crawley area"/></a>
					</div>
					<!-- //Widget -->
					
					{include file='../common/sidebar2.phtml'}
					
					<!-- Widget -->
					<div class="widget">
						<h4>Van courier</h4>
						<a href=""><img src="images/uploads/van courier.jpg" alt="van courier gatwick airport and crawley" title="Van courier in Gatwick Airport and Crawley area"/></a>
					</div>
					<!-- //Widget -->
					
					<!-- Widget -->
					<div class="widget">
						<h4>Truck courier</h4>
						<a href=""><img src="images/uploads/truck courier.jpg" alt="truck courier gatwick airport and crawley" title="Truck courier in Gatwick Airport and Crawley area"/></a>
					</div>
					<!-- //Widget -->
				</aside>
				<!--- //Sidebar -->
				
				<!--- Content -->
				<div class="three-fourth content">
					<!-- Post -->
					<article class="single hentry">
						<div class="entry-featured">
							<img src="images/uploads/same day courier and urgent courier.jpg" alt="urgent and same day courier in gatwick airport and crawley" title="Urgent and same day courier in Gatwick Airport and Crawley area"/>
						</div>
						<div class="entry-content">
						
						<h2>Urgent and same day courier service Gatwick Crawley London</h2>
						<p>Christian Transfers provide local courier services in Gatwick Airport and Crawley area, as well as urgent national parcel deliveries. We deliver from Crawley and Gatwick Airport to London, Brighton, Eastbourne, Chicester, Southampton, Porstmouth, Bournemouth, Dover, Cambridge, Birmingham, Manchester, Bristol and not only.</p> 
						<p>To see the price or to order a parcel delivery please dowload the MayaMix app to request the deliveries. It is available in App Store (for iOS) or Google Play Store (for Android devices).</p> 
						<p>Our app is easy to use, super helpful, providing flexible, reliable and cost-effective solutions.</p> 
                        <p>We understand the need for speed and we have the experience and resources to make it happen. We take this very seriously and recognise that we are an extension of our clients.</p> 
                        
						<p><strong>How it works ?</strong></p>
                        <p>- Download the app from App store or Google Play.</p> 
                        <p>- Make your account using your email and phone number.</p>
                        <p>- Update your profile in the app.</p>
                        <p>- Make a job request and see the price estimation for your choosen locations for different types of service: by bike, moto, car or van.</p> 
						
						<p><strong>Dimensions</strong></p> 
						<p>For Bike = Maximum parcel weight: 10 Kg, Maximum parcel size: 40cm X 40cm X 30cm</p>
						<p>For Moto = Maximum parcel weight: 15 Kg, Maximum parcel size: 60cm X 40cm X 30cm</p>
						<p>For Cars = Maximum parcel weight: 150 Kg, Maximum parcel size: 100cm X 100cm X 50cm</p>
						<p>For Vans = Maximum parcel weight: 800 Kg, Maximum parcel size: 200cm X 200cm X 100cm</p>
						<p><strong>Examples of what we carry with bike and moto include</strong>: Documents, parcels, letters, tenders, legal documents, conveyancing documents, spare parts, printing proofs, clothes, passports, laptops, mobile phones, tablets, VAT returns, business annual returns, income tax returns, decorative samples, veterinary samples, medical samples, medical items, blood samples, keys.</p>
						<p><strong>Examples of what we carry with car and van include</strong>: Documents, parcels, letters, tenders, legal documents, decorative samples, veterinary samples, medical samples, medical items, blood samples, beds, sofa, windows, big stuff.</p>
                        
						<h3><strong>For bike and moto courier owners.</strong></h3>
						<p>No matter what vehicle type you have, we'll have work to suit you. We work with pushbike, scooter or motorbike couriers.</p>
						
						<h3><strong>For car and van courier owners.</strong></h3>
                        <p>We want you! We are growing fast and are on the hunt for people like you to join our fleet. Being self-employed means you are your own boss and can work to a schedule that is totally chosen by you.</p> 
                        <p>We don't just let you get on with it, we want you to be totally confident with the technology and our operations so we'll give you full training and day to day support, allowing you to focus on maximising your earnings.</p>
                        <p>All jobs are distributed fairly and evenly by our bespoke app system.</p> 
                        <p>Meaning consistent, regular and financially rewarding work for you.</p>
                        <p>No matter what vehicle type you have, we'll have work to suit you. We work with pushbike, scooter, motorbike, car and van couriers.</p> 
                        <p>Think driving is a pleasure, not a chore – even in London, Bristol, Birmingham, Manchester, Dublin, Cardiff or Glasgow? Then we want to hear from you.</p> 
						<p>If you want to join our team or to contact us with other enquiries please use the Maya Mix contact form by <a href="http://www.mayamix.co.uk/contacts.html" target="_blank">clicking here</a></p>
						</div>
					</article>
					<!-- //Post -->
				</div>
				<!--- //Content -->
			</div>
		</div>
	</main>
	<!-- //Main -->
	
	<!-- Page info -->
		<header class="site-title color">
			<div class="wrap">
				<div class="container">
					<h1>Christian Transfers Services</h1>
					<nav role="navigation" class="breadcrumbs">
						<ul>
							<li><a href="/" title="Christian Transfers - Airport Transfers">Go to Home</a></li>
                            <li>You are on Urgent Couriers</li>
						</ul>
					</nav>
				</div>
			</div>
		</header>
	<!-- //Page info -->
{include file='../common/sidebar3.phtml'}
{include file='../common/footer.phtml'}