{include file='../common/header.phtml'}
    <!-- Main -->
	<!-- Page info -->
	<main class="main" role="main">
		<!-- Page info -->
		<header class="site-title color">
         <div class="wrap">
             <div class="container">
                <h1>Executive and vip airport transfers and private car rentals</h1>
                <nav role="navigation" class="breadcrumbs">
                    <ul>
                        <li><a href="/" title="Christian Transfers - Airport Transfers">Go to Home</a></li>
                        <li>You are on Executive & VIP</li>
                    </ul>
                </nav>
             </div>
         </div>
        </header>
    <!-- //Page info -->

        <div class="wrap">
			<div class="row">
				
				<!--- Sidebar -->
				<aside class="one-fourth sidebar left">
					
					<!-- Widget -->
					<div class="widget">
						<h4>Limousines executive</h4>
						<a href="#"><img src="images/uploads/limousines executive.jpg" alt="limousines executive" title="Limousines executive" /></a>
					</div>
					<!-- //Widget -->
					
					{include file='../common/sidebar2.phtml'}
					
					<!-- Widget -->
					<div class="widget">
						<h4>Vip cars</h4>
						<a href="#"><img src="images/uploads/vip cars.jpg" alt="vip cars" title="Vip cars" /></a>
					</div>
					<!-- //Widget -->
					
					<!-- Widget -->
					<div class="widget">
						<h4>Vip minivan</h4>
						<a href="#"><img src="images/uploads/vip minivan.jpg" alt="vip minivan" title="Vip minivan" /></a>
					</div>
					<!-- //Widget -->
					
					
				</aside>
				<!--- //Sidebar -->
				
				<!--- Content -->
				<div class="three-fourth content">
					<!-- Post -->
					<article class="single hentry">
						<div class="entry-featured">
							<img src="images/uploads/limousines executive and vip cars.jpg" alt="limousines executive and vip cars" title="Limousines executive and vip cars" />
						</div>
						<div class="entry-content">
						<h2>Executive and vip airport transfers and private car rentals - Christian Transfers</h2>
						<p>If it is for an Airport Transfer or a tailor made rental for an excursions to the countryside, if you order our service just for a short trip or if you book us for all day long, you can always count on our competent, reliable and discrete service to insure your mobility in and around cities.</p> 
                        <p>We also serve your guests ! If you like, we pick them up at the airport and safely transport them to meetings, evening events, to the hotel and on the next day, back to the airport.</p> 
                        <p>Inter city transfers with executive minivans or limousines for special events, wedings, conferences, parties, private groups, special ceremonies.</p> 
                        <p>Trust our experience for your safe journey. Punctuality and discretion are as important to us as security and satisfied customers.</p> 
                        <p>Executive and VIP Airport Transfers in: Paris, Madrid, Dusseldorf, Munich, Glasgow, London, Wienn, Brussels, Bucharest, Timisoara, Constanta, Belgrade, Novi Sad, Skopje, Zagreb, Dubrovnik.</p>
						</div>
					</article>
					<!-- //Post -->
				</div>
				<!--- //Content -->
			</div>
		</div>
	</main>
 	<!-- //Main -->
	
	<!-- Page info -->
		<header class="site-title color">
			<div class="wrap">
				<div class="container">
					<h1>Christian Transfers Services</h1>
					<nav role="navigation" class="breadcrumbs">
						<ul>
							<li><a href="/" title="Christian Transfers - Airport Transfers">Go to Home</a></li>
                            <li>You are on Executive & VIP</li>
						</ul>
					</nav>
				</div>
			</div>
		</header>
	<!-- //Page info -->
{include file='../common/sidebar3.phtml'}	
{include file='../common/footer.phtml'}