{include file='../common/header.phtml'}
    <!-- Main -->
	<!-- Page info -->
	<main class="main" role="main">
		<!-- Page info -->
		<header class="site-title color">
			<div class="wrap">
				<div class="container">
					<h1>Minibus airport transfers and minibus rentals - Christian Transfers</h1>
					<nav role="navigation" class="breadcrumbs">
						<ul>
							<li><a href="/" title="Christian Transfers - Airport Transfers">Go to Home</a></li>
							<li>You are on Minibus</li>
						</ul>
					</nav>
				</div>
			</div>
		</header>
	<!-- //Page info -->
		
		<div class="wrap">
			<div class="row">
				
				<!--- Sidebar -->
				<aside class="one-fourth sidebar left">
					<!-- Widget -->
					<div class="widget">
						<h4>Minibus rentals</h4>
						<a href="#"><img src="images/uploads/minibus rentals.jpg" alt="minibus rentals" title="Minibus rentals" /></a>
					</div>
					<!-- //Widget -->
					
					{include file='../common/sidebar2.phtml'}
					
					<!-- Widget -->
					<div class="widget">
						<h4>Airport transfers</h4>
						<a href="#"><img src="images/uploads/minibus airport transfers.jpg" alt="minibus airport transfers" title="Minibus airport transfers" /></a>
					</div>
					<!-- //Widget -->
				</aside>
				<!--- //Sidebar -->
				
				<!--- Content -->
				<div class="three-fourth content">
					<!-- Post -->
					<article class="single hentry">
						<div class="entry-featured">
							<img src="images/uploads/minibus rentals and airport transfers.jpg" alt="minibus rentals and airport transfers" title="Minibus rentals and airport transfers" />
						</div>
						<div class="entry-content">
							<h2>Minibus airport transfers and minibus rentals (only with our driver) - Christian Transfers</h2>
							<p class="lead">If you have an organized group, do not hesitate to rent a private minibus with driver. </p>
							<p>All minibuses offered by us are renting only with driver. Optional on request we can offer specialized travel guide for foreign languages.</p>
							<p>Our company provides minivans for any type of event: Transfers to / from airport, city tours, travel in Germany, Croatia, Austria, Slovakia, Romania, Bulgaria, Hungary, Serbia, Montenegro or abroad, business trips, transportation for delegates, conferences, holidays at home and abroad, teambuilding for companies, private tours or special events.</p>
							<p>We provide minivans of various types and sizes at highly competitive rates in the countries listed below with few days confirmation.</p>
                            <p>You can communicate the budget for vehicles rental and we will do as soon as possible a complete offer according with your request. Rent conditions and exceptional value for money make this version a very good alternative.</p>
						</div>
					</article>
					<!-- //Post -->
				</div>
				<!--- //Content -->
			</div>
		</div>
	</main>
	<!-- //Main -->
	
	<!-- Page info -->
		<header class="site-title color">
			<div class="wrap">
				<div class="container">
					<h1>Christian Transfers Services</h1>
					<nav role="navigation" class="breadcrumbs">
						<ul>
							<li><a href="/" title="Christian Transfers - Airport Transfers">Go to Home</a></li>
							<li>You are on Minibus</li>
						</ul>
					</nav>
				</div>
			</div>
		</header>
	<!-- //Page info -->
{include file='../common/sidebar3.phtml'}
{include file='../common/footer.phtml'}