{include file='../common/header.phtml'}
    <!-- Main -->
	<!-- Page info -->
	<main class="main" role="main">
		<!-- Page info -->
		<header class="site-title color">
            <div class="wrap">
                <div class="container">
                     <h1>Recovery car app in Gatwick London Birmingham Bristol Manchester</h1>
                     <nav role="navigation" class="breadcrumbs">
                        <ul>
                           <li><a href="/" title="Christian Transfers - Airport Transfers">Go to Home</a></li>
                           <li>You are on Recovery Cars</li>
                        </ul>
                     </nav>
                </div>
            </div>
        </header>
    <!-- //Page info -->

        <div class="wrap">
			<div class="row">
				
				<!--- Sidebar -->
				<aside class="one-fourth sidebar left">
					
					<!-- Widget -->
					<div class="widget">
						<h4>Recovery cars</h4>
						<a href=""><img src="images/uploads/recovery cars london.jpg" alt="recovery cars" title="Recovery cars London" /></a>
					</div>
					<!-- //Widget -->
					
						<!-- Widget -->
					<div class="widget">
						<h4>Recovery truck</h4>
						<a href=""><img src="images/uploads/recovery truck.jpg" alt="tow truck service" title="Tow truck service" /></a>
					</div>
					<!-- //Widget -->
					
					{include file='../common/sidebar2.phtml'}
					
					<!-- Widget -->
					<div class="widget">
						<h4>Recovery cars</h4>
						<a href=""><img src="images/uploads/recovery cars crawley.png" alt="recovery cars" title="Recovery cars Crawley" /></a>
					</div>
					<!-- //Widget -->
					
						<!-- Widget -->
					<div class="widget">
						<h4>Heavy recovery</h4>
						<a href=""><img src="images/uploads/heavy recovery.jpg" alt="roadside assistance" title="Roadside assistance" /></a>
					</div>
					<!-- //Widget -->
				</aside>
				<!--- //Sidebar -->
				
				<!--- Content -->
				<div class="three-fourth content">
					<!-- Post -->
					<article class="single hentry">
						<div class="entry-featured">
							<img src="images/uploads/recovery cars christian transfers.jpg" alt="recovery cars london" title="Recovery cars London" />
						</div>
						<div class="entry-content">
					<h2>Digital roadside assistance service - recovery car & towing trucks.</h2>
					<p>Goodbye breakdown membership. <b>Hello Recovery Car on demand</b>.</p>
					<p>Christian Transfers revolutionising breakdown assistance. So say goodbye to monthly and annual fees, membership cards and exhausting phone calls at the roadside. Download our app, Maya Mix and pay only for the tow you need.</p>
					<p>If your vehicle has experienced a breakdown or mechanical disablement, Christian Transfers is available to provide the roadside help you need - 24/7/365. A nationwide network of qualified roadside assistance professionals is providing the fastest, safest, an innovative roadside assistance in towing services.</p>
					<p>MayaMix App is the new digital point of contact between you and tow subcontractor. In MayaMix app you see upfront pricing, smart connections to the nearest available towing truck, and live tracking and ETA on your smartphone, digital roadside assistance service is the most reliable help for when you need help getting back on the road.</p>
					<p>Our aim is to give you an efficient and cost effective car service that is local to you. A vehicle recovery specialist can help you restart it, or they can recover your car and transport it wherever you need when necessary.</p>
					<p>We understand how frustrating and worrying it is to be stuck without transportation, so we ensure we get to you as quick as we can so you can be home in no time.</p>
					<p>MayaMix App easily connect you to the nearest towing truck, so the following services can be offered: commercial vehicle recovery, car recovery, light commercial recovery, heavy commercial vehicle recovery. Services and types of trucks might vary from one location to another, the app will let you know what's available when you are requesting.</p>
					<p>We recently introduced car transportation on long distance, from Uk to Netherland, Belgium, Switzerland, Germany, Poland, Austria, Slovakia, Hungary, Romania & Bulgaria.</p>
					<h3><strong>For recovery car owners, towing provider & parteners companies</strong></h3>
					<p>Get more towing leads. More Jobs. More Money. Download our partner app and contact us to join the revolution.</p> 
					<p>Like meeting new people in interesting circumstances? You’ll be a welcome face to those stuck by the side of the road.</p> 
					<p>You’ll be recovering vehicles that have broken down, crashed or been involved in a crime. And you’ll be independent, patient and able to use your initiative, as well as being friendly and helpful.</p>
					<p>For recovery drivers, every day is different. You’ll never be bored. Think driving is a pleasure, not a chore – even in London, Manchester, Dublin, Cardiff or Glasgow? Then we want to hear from you.</p>
					<p>If you want to join our team or to contact us with other enquiries please use the contact form by <a href="/contact">clicking here</a></p>
						</div>
					</article>
					<!-- //Post -->
				</div>
				<!--- //Content -->
			</div>
		</div>
	</main>
    <!-- //Main -->
	
	<!-- Page info -->
		<header class="site-title color">
			<div class="wrap">
				<div class="container">
					<h1>Christian Transfers Services</h1>
					<nav role="navigation" class="breadcrumbs">
						<ul>
							<li><a href="/" title="Christian Transfers - Airport Transfers">Go to Home</a></li>
                           <li>You are on Recovery Cars</li>
						</ul>
					</nav>
				</div>
			</div>
		</header>
	<!-- //Page info -->
{include file='../common/sidebar3.phtml'}
{include file='../common/footer.phtml'}