{include file='../common/header.phtml'}
    <!-- Main -->
	<!-- Page info -->
	<main class="main" role="main">
		<!-- Page info -->
		<header class="site-title color">
        <div class="wrap">
            <div class="container">
                <h1>Taxi app for Gatwick London Crawley Brighton Redhill Portsmouth</h1>
                <nav role="navigation" class="breadcrumbs">
                    <ul>
                       <li><a href="/" title="Christian Transfers - Airport Transfers">Go to Home</a></li>
                       <li>You are on Taxi</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <!-- //Page info -->

        <div class="wrap">
			<div class="row">
				
				<!--- Sidebar -->
				<aside class="one-fourth sidebar left">
					
					<!-- Widget -->
					<div class="widget">
						<h4>Taxi</h4>
						<a href=""><img src="images/uploads/taxi1.jpg" alt="taxi" title="Taxi" /></a>
					</div>
					<!-- //Widget -->
					
						<!-- Widget -->
					<div class="widget">
						<h4>Taxi  Assist</h4>
						<a href=""><img src="images/uploads/taxi assist.jpg" alt="taxi assist" title="Taxi Assist" /></a>
					</div>
					<!-- //Widget -->
					
					{include file='../common/sidebar2.phtml'}
					
					<!-- Widget -->
					<div class="widget">
						<h4>Maya Mix</h4>
						<a href=""><img src="images/uploads/maya mix.jpg" alt="mayamix.eu and mayamix.co.uk" title="MayaMix.eu and MayaMix.co.uk" /></a>
					</div>
					<!-- //Widget -->
					
                      <!-- Widget -->
					<div class="widget">
						<h4>Download the app</h4>
						<a href=""><img src="images/uploads/download the app.jpg" alt="download the app" title="Download the MayaMix App" /></a>
					</div>
					<!-- //Widget -->
					
					  <!-- Widget -->
					<div class="widget">
						<h4>Taxi, Courier or Recovery car service</h4>
						<a href=""><img src="images/uploads/taxi courier or recovery car service.jpg" alt="taxi courier or recovery car service" title="Taxi, Courier or Recovery car service" /></a>
					</div>
					<!-- //Widget -->
				</aside>
				<!--- //Sidebar -->
				
				<!--- Content -->
				<div class="three-fourth content">
					<!-- Post -->
					<article class="single hentry">
						<div class="entry-featured">
							<img src="images/uploads/taxi and taxi assist london crawley brighton.jpg" alt="taxi and taxi assist london crawley brighton" title="Taxi and Taxi Assist London Crawley Brighton" />
						</div>
						<div class="entry-content">
					            <h2>Taxi app for Gatwick London Crawley Brighton Redhill Portsmouth</h2>
                                <p>A new category in city travel, that makes daily commuting more reliable,comfortable and stress free at a price point similar to public transport.</p> 
                                <p>Smart mobility, quality, on-demand shuttles at everyday prices.</p>
                                <p>Are you looking for access to hundreds of different vehicles, from black taxi to executive cars?</p> 
                                <p>Safety ,from start to finish, a ride you can trust.</p> 
                                <p>Pay by App.</p> 
                                <p>Add a payment method to your account (credit card or PayPal) and pay for your journey with the app. With guaranteed security and at your fingertips – it couldn’t be simpler!</p> 
                                <p>Fill out the form below and we'll help you find the solution that's right for you.</p> 
                                <p>Enjoy the ride!</p> 

                                <h3><strong>For licensed taxi and assist taxi owners</strong></h3>
                                <p>Whether you're a black cab driver or a courier driver, it's quick and easy to start working with us.</p> 
                                <p>Refer a friend programme.</p>
                                <p>Why become a MayaMix driver?</p> 
                                <p>Earn more with MayaMix App. More jobs = more money.</p> 
                                <p>Get the free driver app - Manage your work in the app for iOS and Android.</p> 
                                <p>Secure card payments - No need to handle cash.</p> 
                                <p>Refer a friend programme.</p> 
                                <p>It's easy to join MayaMix App</p> 
                                <p>Sign up - Download the app.</p> 
                                <p>We're always on the lookout for talented, Driven by Quality people, to share our passion for innovation. Join our team and be part of one of the most exciting global startups!</p>
                                <p>You are one of us if...</p> 
                                <p>You work hard, you play hard, you are driven by quality.</p> 
                                <p>You have a sense for the little things and understand consumer needs.</p> 
                                <p>You are a team player, positive, humble and have a ‘can do ’attitude.</p> 
                                <p>Ideally connected.</p> 
                                <p>Simply intuitive.</p> 
                                <p>We and our drivers have developed what is probably the most intuitive app on the market.</p>
						</div>
					</article>
					<!-- //Post -->
				</div>
				<!--- //Content -->
			</div>
		</div>
	</main>
	<!-- //Main -->
	
	<!-- Page info -->
		<header class="site-title color">
			<div class="wrap">
				<div class="container">
					<h1>Christian Transfers Services</h1>
					<nav role="navigation" class="breadcrumbs">
						<ul>
							<li><a href="/" title="Christian Transfers - Airport Transfers">Go to Home</a></li>
                            <li>You are on Taxi</li>
						</ul>
					</nav>
				</div>
			</div>
		</header>
	<!-- //Page info -->
{include file='../common/sidebar3.phtml'}
{include file='../common/footer.phtml'}