{include file='../common/header.phtml'}
	<!-- Main -->
	<!-- Page info -->
	<main class="main" role="main">
		<!-- Page info -->
		<header class="site-title color">
			<div class="wrap">
				<div class="container">
					<h1>Airport transfers and private rentals with cars and minivans</h1>
					<nav role="navigation" class="breadcrumbs">
						<ul>
							<li><a href="/" title="Christian Transfers - Airport Transfers">Go to Home</a></li>
							<li>You are on Airport Transfers</li>
						</ul>
					</nav>
				</div>
			</div>
		</header>
	<!-- //Page info -->
		
		<div class="wrap">
			<div class="row">
				
				<!--- Sidebar -->
				<aside class="one-fourth sidebar left">
					<!-- Widget -->
					<div class="widget">
						<h4>Airport transfers</h4>
						<a href="#"><img src="images/uploads/airport transfers1.jpg" alt="airport transfers" title="Airport transfers" /></a>
					</div>
					<!-- //Widget -->
					
					<!-- Widget -->
					<div class="widget">
						<h4>Minivan airport transfers</h4>
						<a href="#"><img src="images/uploads/minivan airport transfers.jpg" alt="minivan airport transfers" title="Minivan Airport Transfers" /></a>
					</div>
					<!-- //Widget -->
					
					{include file='../common/sidebar2.phtml'}
					
					<!-- Widget -->
					<div class="widget">
						<h4>Minibus Airport transfers</h4>
						<a href="#"><img src="images/uploads/minibus airport transfers 1.jpg" alt="minibus airport transfers" title="Minibus airport transfers" /></a>
					</div>
					<!-- //Widget -->
					
					<!-- Widget -->
					<div class="widget">
						<h4>Coach airport transfers</h4>
						<a href="#"><img src="images/uploads/coach airport transfers 1.jpg" alt="coach airport transfers" title="Coach airport transfers" /></a>
					</div>
					<!-- //Widget -->
					
					<!-- Widget -->
					<div class="widget">
						<h4>Tailor made transfers</h4>
						<a href="#"><img src="images/uploads/minibus rentals.jpg" alt="tailor made airport transfers" title="Tailor made airport transfers" /></a>
					</div>
					<!-- //Widget -->
				</aside>
				<!--- //Sidebar -->
				
				<!--- Content -->
				<div class="three-fourth content">
					<!-- Post -->
					<article class="single hentry">
						<div class="entry-featured">
							<img src="images/uploads/renault.jpg" alt="minivan airport transfers" title="Minivan airport transfers" />
						</div>
						<div class="entry-content">
							<h2>Airport transfers and private rentals with cars and minivans - Christian Transfers</h2>
							<p class="lead">Christian Transfers offer airport transfers from several Europe Airports.</p>
							<p>Pick-up from all Austria Airports Vienna, Salzburg, Graz, Innsbruck Tirol and going to Vienna, Salzburg, Graz, Zell am See, Kaprun, Saalbach, Hinterglemm, Gasteinertal, Flachau, Flachauwinkel, Kleinarl, Grobarl, Wagrain, Maria Alm, Leogang, Dienten, Muhlbacha. Hochkonig, Saalfelden, Piesendorf, Schladming, Kitzbuhel, Westendorf, Brixen, Hopfgarten, Wildschonau, Kirchberg, Scheffau, Ellmau, Soll, Obergurgl, Hochgurgl, Solden, Ischgl, Galtur, Lech, Zurs, St. Anton am Arlberg, Serfaus, Ladis, Fiss, Fulpmes, Hintertux, Igls, Mayrhofen, Neustift, Seefeld, Going, Niederau, Alpbach, St.Johann in Tirol.</p>
							<p>We organize transfer by taxis and minvans or rentals with coaches and buses to all Austria destinations or abroad to Hungary, Slovakia, Czech Republic, Germany, Switzerland, Croatia, Italy, Slovenia, Serbia and Bosnia Hertegovina.</p>
						    <p>Pick-up from all Hungary Airports and cities Budapest, Balaton, Szeged and Debrecen and going to Balatonalmadi, Balatonboglar, Balatonfured, Bekescsaba, Debrecen, Dunaujvaros, Gyor, Kecskemet, Miskolc, Nyiregyhaza, Pecs, Siofok, Sopron, Szeged, Szekesfehervar, Szentes, Szolnok, Szombhately, Veszprem, Timisoara Airport, Arad, Cluj, Oradea, Brasov, Sibiu, Zagreb, Rijeka, Dubrovnik, KRK Airport, National Parc Plitvicer, Osijek, Novalja Pag, Varazdin, Crikvenica, Opatija, Porec, Pula, Sibenik, Split, Umag, Maribor, Zadar, Ljubljana, Belgrad, Novi Sad, Budapest Airport, Pecs, Szeged, Trieste, Udine, Venezia Airport, Graz, Klagenfurt, Linz, Salzburg, Wien.</p>
							<p>We organize transfer by taxis and minvans or rentals with coaches and buses to all Hungary destinations or abroad to Austria, Croatia, Romania, Poland, Germany, Slovakia, Italy, Slovenia, Serbia, Ukraine, Motenegro and Bosnia Hertegovina.</p>
							<p>Pick-up from all Croatia Airports Zagreb, Rijeka, Dubrovnik and going to Zagreb, Rijeka, Dubrovnik, KRK Airport, National Parc Plitvicer, Osijek, Novalja Pag, Varazdin, Crikvenica, Opatija, Porec, Pula, Sibenik, Split, Umag, Maribor, Zadar, Ljubljana, Belgrad, Novi Sad, Budapest Airport, Pecs, Szeged, Trieste, Udine, Venezia Airport, Graz, Klagenfurt, Linz, Salzburg, Wien.</p>
							<p>We organize transfer by taxis and minvans or rentals with coaches and buses to all Croatia destinations or abroad to Austria, Hungary, Italy, Slovenia, Serbia, Motenegro and Bosnia Hertegovina.</p>
							<p>Pick-up from all Germany Airports and cities Munich, Berlin, Frankfurt for events in Hamburg, Stuttgart, Bremen, Dusseldorf, Nuremberg, Strasbourg, Paris, Torino, Milano, Roma, Venezia Copenhagen, Warsaw, Wroclaw, Poznan, Prague, Brno, Wien, Salzburg, Zurich, Berne, Geneva, Amsterdam, Eindhoven, Brussel, Zagreb, Maribor, Ljubljana, Belgrad, Budapest, Bratislava.</p>
							<p>We organize transfer by taxis and minvans or rentals with coaches and buses to all Germany destinations or abroad to France, Belgium, Netherland, Luxembourg, Switzerland, Austria, Denmark, Liechtenstein, Czech Republic, Italy, Croatia, Poland, Slovakia, Slovenia.</p>
							<p>Pick-up from Bucharest Otopeni Airport, Constanta Airport, Timisoara Airport, Brasov or Sibiu for transfers to all Bucharest or Romania Hotels or for Bucharest city tour - House of the People, The Village Museum, Triumphal Arch, Romanian Peasant Museum, Romanian Athenaeum, Patriarchal Church. One day tour arround Bucharest - Mogosoaia Palace, Manasteries like: Cernica, Pasarea, Tiganesti, Caldarusani and Snagov.Transilvania Tour - One full day to visit 4 Castles in Transilvania: Peles, Pelisor, Bran, Cantacuzino. After this we go to a very nice dinner in Brasov.</p>
							<p>Pick-up in Bulgaria from Sofia Airport for transfers to Sofia, Pleven, Plovdiv, Russe, Veliko Tarnovo, Burgas, Sunny Beach, Skopje, Thessaloniki. Pickups from Varna Airport and going to Constanta, Mamaia, Vama Veche, Albena, Golden Sands, Kavarna, Balcik, Sunny Beach, Obzor, Nessebar or Sozopol.</p>
							<p>Pick-up in Serbia from Belgrade Airport for transfers to Belgrade, Novi Sad, Subotica, Nis, Sofia, Timisoara, Arad, Budapest, Szeged, Prishtina.</p>
							<p>Pick-up in Slovakia from Bratislava Airport for transfers to Bratislava, Vienna, Trnava, Nitra, Brno, Prague, Budapest, Gyor and all other cities in the region.</p>
							<p>Pick-up in Slovenia from Ljubliana Airport for transfers to Ljubliana, Maribor, Trieste, Venice, Zagreb, Pula, Rovinj, Umag, Opatija, Porec, Rijeka.</p>
							<p>Pick-up in Montenegro from Podgorita Airport for transfers to Podgorita, Kotor, Budva, Herceg Novi, Bar, Ulcinj, Dubrovnik Airport or Dubrovnik Port.</p>
							<p>Pick-up in Macedonia from Skopje Airport for transfers to Skopje, Ohrid, Sofia, Tirana, Thessaloniki, Prishtina.</p>
							<p>Pick-up in Spain from Madrid Airport for transfers to Madrid, Barcelona Airport for transfers to Barcelona from Valencia Airport for transfers to Valencia.</p>
							<p>Pick-up in France from Paris CDG and Paris Orly Airports for transfers to Paris, Disneyland. Lyon Airport to Lyon city and mountin resorts, from Nice Airport to Nice and all coast resorts.</p>
						</div>
					</article>
					<!-- //Post -->
				</div>
				<!--- //Content -->
			</div>
		</div>
	</main>
	<!-- //Main -->
	
	<!-- Page info -->
		<header class="site-title color">
			<div class="wrap">
				<div class="container">
					<h1>Christian Transfers Services</h1>
					<nav role="navigation" class="breadcrumbs">
						<ul>
							<li><a href="/" title="Christian Transfers - Airport Transfers">Go to Home</a></li>
							<li>You are on Airport Transfers</li>
						</ul>
					</nav>
				</div>
			</div>
		</header>
	<!-- //Page info -->
{include file='../common/sidebar3.phtml'}
{include file='../common/footer.phtml'}