{include file='../common/header.phtml'}
<article class="col2">
    <p align="left"><font color="#C9000" face="Arial" size="2"><strong>HOW THE SYSTEM WORK FOR THE RESERVATIONS.</strong></font></p>
    <p align="left"><font face="Arial" size="2"><strong>Online reservation.</strong></font></p>
	<p align="left"><font face="Arial" size="2">Any customer can make reservations and payments online on our website 24/7/365 (we recommend the bookings to be made with 48 hours before the transfer to have place, Sunday and Saturday excluded from this calculation).</font></p>
	<p align="left"><font face="Arial" size="2"><strong>Procesing your reservations.</strong></font></p>
	<p align="left"><font face="Arial" size="2">We proces your reservation during our working hours 09:00-18:00 (GMT +2). We send all the bookings with payments to our local subcontractors/carriers.</font></p>
	<p align="left"><font face="Arial" size="2"><strong>Confirmation.</strong></font></p>
	<p align="left"><font face="Arial" size="2">Local subcontractors/carriers send confirmations or infirmations during their working hours usually Monday - Friday 0900-1800, Saturday 10.00-1300, Sunday closed.</font></p>
	<p align="left"><font face="Arial" size="2">According with local subcontractors/carriers confirmations we will send you confirmation or infirmation BY EMAIL for your booking (PLEASE CHECK YOUR SPAM/JUNK FOLDER TOO).</font></p>
	<p align="left"><font color="#C9000" face="Arial" size="2"><strong>USING THE LEFT WEBSITE MENU FOR THE RESERVATIONS.</strong></font></p>
	<p align="left"><font face="Arial" size="2"><strong>Page 1 - Choose your country.</strong></font></p>
	<p align="left"><font face="Arial" size="2">See in the left side of the website to the menu the first buton indicate you "Starting Country". Click on it and choose the starting country for your transportation. We reffer here to the transportation with our company.</font></p>
	<p align="left"><font face="Arial" size="2"><strong>Choose your starting point.</strong></font></p>
	<p align="left"><font face="Arial" size="2">Next choose your starting city or airport from the list, "Pick up from Airport or City" is the button.</font></p>
	<p align="left"><font face="Arial" size="2"><strong>Choose your destination.</strong></font></p>
	<p align="left"><font face="Arial" size="2">Next choose your arrival city or airport from the list "Your Destination". If your desire connection is not listed please use the contact page form to contact us and we will try to offer your destination too, as fast as we can.</font></p>
	<p align="left"><font face="Arial" size="2"><strong>Choose one way or return transfer.</strong></font></p>
	<p align="left"><font face="Arial" size="2">Choose next if you need one way transfer or return "Only One or Return Transfer".</font></p>
	<p align="left"><font face="Arial" size="2"><strong>Choose your date & hours.</strong></font></p>
	<p align="left"><font face="Arial" size="2">You can choose the date with the menu buttons or click on the calendar. Next select the desire hour for transportation. </b>If you will choose shuttle bus transfer do not choose the hour as you will have to be present at the bus schedulle</b>.</font></p>
	<p align="left"><font face="Arial" size="2"><strong>Select the passengers number.</strong></font></p>
	<p align="left"><font face="Arial" size="2">Select the number of the passenger who will travel.</font></p>
	<p align="left"><font face="Arial" size="2"><strong>Choose you car.</strong></font></p>
	<p align="left"><font face="Arial" size="2">After you made all thoose selection the available cars for this route will appear on the right part of the website. Choose the car with a click on the right button. If you choose shuttle bus transfer please choose form the options if there are more than one shuttle options. If you have return transfer click for both trips on your desire car. Then click the button under the cars "Submit your car and go to next step from you Booking".</font></p>
    
	<p align="left"><font face="Arial" size="2"><strong>Page 2 - Check your booking from first step.</strong></font></p>
	<p align="left"><font face="Arial" size="2">Before complete any details please see in the center part of the page the details already completed at the first step. If there are any mistakes please come back and recomplete them according with your desire transportation needs.</font></p>
	<p align="left"><font face="Arial" size="2"><strong>Complete personal details - Name & Company.</strong></font></p>
	<p align="left"><font face="Arial" size="2">
	- Complete the name of the passenger/s, (example : John Briandth; Raluca Ionescu; Ivonse Larissa; if they are 3 passengers).</br>
	- In case you are travel in business purposse put the company name in next space, if you are travel on your own just put a minus (-).</font></p>
	<p align="left"><font face="Arial" size="2"><strong>Complete Phone & Email.</strong></font></p>
	<p align="left"><font face="Arial" size="2">
	- Phone - Please put the mobile phone number (INCLUDING COUNTRY CODE) you will have at the time of your travel to can be called in case of not meeting the driver;</br>
	- Email - Do Not use AOL.com emails. Please use a valid email adress where you will receive the confirmation for booking and payment. PLEASE CHECK YOUR SPAM/JUNK FOLDER too for confirmation.</font></p>


<div align="center">
	<p><div class="fb-like" data-href="https://www.facebook.com/ChristianTransfers" data-send="true" data-width="700" data-show-faces="false" data-action="recommend"></div></p>
    </div>
</article>
	</div>
	</section>
</div>

{include file='../common/footer.phtml'}